### ISSUE TITLE
AccessDeniedException: /opt/thehive/RUNNING_PID 

### ISSUE THREAD

**Issue by martinacen** [TheHive-Project/TheHive#1018]
### Request Type
Bug

### Work Environment
Ubuntu 18.04.2 LTS
TheHive installed by DEB

### Problem Description
Cannot start TheHive. The error is the following:

> Oops, cannot start the server.
java.nio.file.AccessDeniedException: /opt/thehive/RUNNING_PID
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at play.core.server.ProdServerStart$.createPidFile(ProdServerStart.scala:136)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:43)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)

### Steps to Reproduce
1. cd opt/thehive
2. bin/thehive -Dconfig.file=/etc/thehive/application.conf

### Complementary information
This is my application.conf file:

```
 # maximum number of similar cases
maxSimilarCases = 100
play.http.secret.key="KEY"
# ElasticSearch
search {
  # Name of the index
  index = the_hive
  # Name of the ElasticSearch cluster
  cluster = hive
  # Address of the ElasticSearch instance
  host = ["127.0.0.1:9300"]
  # Scroll keepalive
  keepalive = 1m
  # Size of the page for scroll
  pagesize = 50
  # Arbitrary settings
  settings {
    # Maximum number of nested fields
    mapping.nested_fields.limit = 50
  }
}
# Datastore
datastore {
  # Size of stored data chunks
  chunksize = 50k
  hash {
    # Main hash algorithm /!\ Don't change this value
    main = "SHA-256"
    # Additional hash algorithms (used in attachments)
    extra = ["SHA-1", "MD5"]
  }
  attachment.password = "malware"
}
auth {
	# "provider" parameter contains authentication provider. It can be multi-valued (useful for migration)
	# available auth types are:
	# local : passwords are stored in user entity (in ElasticSearch). No configuration are required.
	# ad : use ActiveDirectory to authenticate users. Configuration is under "auth.ad" key
	# ldap : use LDAP to authenticate users. Configuration is under "auth.ldap" key
	provider = [local]
	ad {
		# The name of the Microsoft Windows domaine using the DNS format. This parameter is required.
		#domainFQDN = "mydomain.local"
    # Optionally you can specify the host names of the domain controllers. If not set, TheHive uses "domainFQDN".
    #serverNames = [ad1.mydomain.local, ad2.mydomain.local]
		# The Microsoft Windows domain name using the short format. This parameter is required.
		#domainName = "MYDOMAIN"
		# Use SSL to connect to the domain controller(s).
		#useSSL = true	}
	ldap {
		# LDAP server name or address. Port can be specified (host:port). This parameter is required.
		#serverName = "ldap.mydomain.local:389"
    # If you have multiple ldap servers, use the multi-valued settings.
    #serverNames = [ldap1.mydomain.local, ldap2.mydomain.local]
		# Use SSL to connect to directory server
		#useSSL = true
		# Account to use to bind on LDAP server. This parameter is required.
		#bindDN = "cn=thehive,ou=services,dc=mydomain,dc=local"
		# Password of the binding account. This parameter is required.
		#bindPW = "***secret*password***"
		# Base DN to search users. This parameter is required.
		#baseDN = "ou=users,dc=mydomain,dc=local"
		# Filter to search user {0} is replaced by user name. This parameter is required.
		#filter = "(cn={0})"
	}
}
# Maximum time between two requests without requesting authentication
session {
  warning = 5m
  inactivity = 1h
}
# Streaming
stream.longpolling {
  # Maximum time a stream request waits for new element
  refresh = 1m
  # Lifetime of the stream session without request
  cache = 15m
  nextItemMaxWait = 500ms
  globalMaxWait = 1s
}
# Cortex configuration
########
## Enable the Cortex module
play.modules.enabled += connectors.cortex.CortexConnector
cortex {
  #"CORTEX-SERVER-ID" {
  #  # URL of Cortex server
  #  url = "http://127.0.0.1:9001"
  # Key of the Cortex user, mandatory for Cortex 2
    key = "KEY"
  #  #HTTP client configuration, more details in section 8
  #  ws {
  #    ws.useProxyProperties = true
  #    proxy {
  #      # The hostname of the proxy server.
  #      #host = ""
  #      # The port of the proxy server.
  #      #post = 0
  #      # The protocol of the proxy server.  Use "http" or "https".  Defaults to "http" if not specified.
  #      #protocol = "http"
  #      # The username of the credentials for the proxy server.
  #      #user = ""
  #      # The password for the credentials for the proxy server.
  #      #password = ""
  #      # The password for the credentials for the proxy server.
  #      #ntlmDomain = ""
  #      # The realm's charset.
  #      #encoding = ""
  #      # The list of host on which proxy must not be used.
  #      #nonProxyHosts = ""
  #    }
  #    ssl {
  #      keyManager { # used for client certificate authentication
  #        stores = [{
  #          type: "pkcs12" // JKS or PEM
  #          path: "mycert.p12"
  #          password: "password1"
  #        }]
  #      }
  #      # Add certificate authorities to trust remote certificate  
  #      trustManager {
  #        stores = [{
  #          type: "JKS" // JKS or PEM
  #          path: "keystore.jks"
  #          password: "password1"
  #        }]
  #     }
  #     debug = {
  #       ssl = false
  #       trustmanager = false
  #       keymanager = false
  #       sslctx = false
  #       handshake = false
  #       verbose = false
  #       data = false
  #       certpath = false
  #     }
  #
  #     # default SSL protocol
  #     #protocol = "TLSv1.2"
  #
  #     # list of enabled SSL protocols
  #     #ws.ssl.enabledProtocols = ["TLSv1.2", "TLSv1.1", "TLSv1"]
  #
  #     # SSL Cipher suite
  #     #enabledCipherSuites = [
  #     #  "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",
  #     #  "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
  #     #  "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384",
  #     #  "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
  #     #]
  #    }
  #  }
  #}
}
# MISP configuration
########
misp {
  #"MISP-SERVER-ID" {
  #  # URL of MISP server
  #  url = ""
  #  # authentication key
  #  key = ""
  #  #tags to be added to imported artifact
  #  tags = ["misp"]
  #
  #  # filters:
  #  # the maximum number of attributes (max-attributes)
  #  #max-attributes = 1000
  #  # the maximum size of the event json message
  #  #max-size = 1 MiB
  #  # the age of the last publication
  #  #max-age = 7 days
  #  exclusion {
  #  # the organisation is black-listed  
  #  #organisation = ["bad organisation", "other orga"]
  #  # one of the tags is black-listed
  #  #tags = ["tag1", "tag2"]
  #  }
  #
  #  ws {
  #    ws.useProxyProperties = true
  #    proxy {
  #      # The hostname of the proxy server.
  #      #host = ""
  #      # The port of the proxy server.
  #      #post = 0
  #      # The protocol of the proxy server.  Use "http" or "https".  Defaults to "http" if not specified.
  #      #protocol = "http"
  #      # The username of the credentials for the proxy server.
  #      #user = ""
  #      # The password for the credentials for the proxy server.
  #      #password = ""
  #      # The password for the credentials for the proxy server.
  #      #ntlmDomain = ""
  #      # The realm's charset.
  #      #encoding = ""
  #      # The list of host on which proxy must not be used.
  #      #nonProxyHosts = ""
  #    }
  #
  #    ssl {
  #      keyManager { # used for client certificate authentication
  #        stores = [{
  #          type: "pkcs12" // JKS or PEM
  #          path: "mycert.p12"
  #          password: "password1"
  #        }]
  #      }
  #      # Add certificate authorities to trust remote certificate  
  #      trustManager {
  #        stores = [{
  #          type: "JKS" // JKS or PEM
  #          path: "keystore.jks"
  #          password: "password1"
  #        }]
  #     }
  #     debug = {
  #       ssl = false
  #       trustmanager = false
  #       keymanager = false
  #       sslctx = false
  #       handshake = false
  #       verbose = false
  #       data = false
  #       certpath = false
  #     }
  #
  #     # default SSL protocol
  #     #protocol = "TLSv1.2"
  #
  #     # list of enabled SSL protocols
  #     #ws.ssl.enabledProtocols = ["TLSv1.2", "TLSv1.1", "TLSv1"]
  #
  #     # SSL Cipher suite
  #     #enabledCipherSuites = [
  #     #  "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",
  #     #  "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
  #     #  "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384",
  #     #  "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
  #     #]
  #    }
  #  }
  #}
  # Interval between two MISP event import
  interval = 1h
}
# Metrics configuration
########
metrics {
  name = default
  enabled = false
  rateUnit = SECONDS
  durationUnit = SECONDS
  jvm = true
  logback = true
  graphite {
    enabled = false
    host = "127.0.0.1"
    port = 2003
    prefix = thehive
    rateUnit = SECONDS
    durationUnit = MILLISECONDS
    period = 10s
  }
  ganglia {
    enabled = false
    host = "127.0.0.1"
    port = 8649
    mode = UNICAST
    ttl = 1
    version = 3.1
    prefix = thehive
    rateUnit = SECONDS
    durationUnit = MILLISECONDS
    tmax = 60
    dmax = 0
    period = 10s
  }
  influx {
    enabled = false
    url = "http://127.0.0.1:8086"
    user = root
    password = root
    database = thehive
    retention = default
    consistency = ALL
    #tags = {
    #	tag1 = value1
    #	tag2 = value2
    #}
    period = 10s
  }
}
```

Thank you!

**Comment by crackytsi** [comment]
Hi @martinacen 
If the permission is denied that could be produced by several reasons.
Why don't you install a binary precompiled package as it is described in the documentation?
If something on start fails it could happen that there is still hanging process, so I recommend to double check that everything is finished before you start it.
I also recommend not to publish your secret-key on Github...
It does not look like an issue of the config-file for me.

BTW: The metrics DB topics are removed on TheHive 3.4 RC1, not sure which version you installed... You missed that information.

**Comment by martinacen** [comment]
> Hi @martinacen
> If the permission is denied that could be produced by several reasons.
> Why don't you install a binary precompiled package as it is described in the documentation?
> If something on start fails it could happen that there is still hanging process, so I recommend to double check that everything is finished before you start it.
> I also recommend not to publish your secret-key on Github...
> It does not look like an issue of the config-file for me.
> 
> BTW: The metrics DB topics are removed on TheHive 3.4 RC1, not sure which version you installed... You missed that information.

Hi @crackytsi thanks for your reply. I hadn't any RUNNING_PID file in opt/thehive but, after some attempts, I can start TheHive now. 
I don't know if this is the real issue but, everytime I want to start TheHive by 

> bin/thehive -Dconfig.file=/etc/thehive/application.conf

I have to use 

> sudo service thehive stop

before.

**Comment by crackytsi** [comment]
Why don't you use the init script?
systemctl stop thehive
systemctl start thehive
Or /etc/init.d/thehive start
/etc/init.d/thehive stoppt

It seems that something did not correcly cleaned up...

**Comment by nadouani** [comment]
Why do you have to use `bin/thehive -Dconfig.file=/etc/thehive/application.conf`?

If you use .DEB packages, it will enable a `thehive` service you can start and stop using systemctl.
