### ISSUE TITLE
Cannot start Thehive 3.4.0-RC1

### ISSUE THREAD

**Issue by jordisk** [TheHive-Project/TheHive#1020]
# After installing from bintray (3.4.0-RC1) The hive service is unable to start

### Request Type
Bug

### Work Environment

| Question              | Answer
|--------------------|--------------------
| OS version (server)       | RedHat
| OS version (client)       |10
| TheHive version / git hash   | 3.4.0-RC1
| Package Type              | Binary

### Problem Description
 After installing from bintray (3.4.0-RC1) The hive service is unable to start

```
2019-06-18 16:30:43,601 [WARN] from akka.util.ManifestInfo in application-akka.actor.default-dispatcher-2 - Detected possible incompatible versions on the classpath. Please note that a given Akka version MUST be the same across all modules of Akka that you are using, e.g. if you use [2.5.21] all other modules that are released together MUST be of the same version. Make sure you're using a compatible set of libraries. Possibly conflicting versions [2.5.21, 2.5.19] in libraries [akka-protobuf:2.5.21, akka-actor:2.5.21, akka-slf4j:2.5.21, akka-remote:2.5.19, akka-cluster:2.5.19, akka-stream:2.5.21, akka-cluster-tools:2.5.19]
2019-06-18 16:30:44,995 [ERROR] from akka.actor.OneForOneStrategy in application-akka.actor.default-dispatcher-16 - Unable to provision, see the following errors:

1) Error injecting constructor, com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'search.uri'
  at org.elastic4play.database.DBConfiguration.<init>(DBConfiguration.scala:41)
  at org.elastic4play.database.DBConfiguration.class(DBConfiguration.scala:40)
  while locating org.elastic4play.database.DBConfiguration
    for the 1st parameter of org.elastic4play.services.SequenceSrv.<init>(SequenceSrv.scala:10)
  at org.elastic4play.services.SequenceSrv.class(SequenceSrv.scala:10)
  while locating org.elastic4play.services.SequenceSrv
    for the 5th parameter of models.CaseModel.<init>(Case.scala:62)
  at models.CaseModel.class(Case.scala:61)
  while locating models.CaseModel
    for the 1st parameter of models.TaskModel.<init>(Task.scala:38)
  at models.TaskModel.class(Task.scala:37)
  while locating models.TaskModel
    for the 1st parameter of models.LogModel.<init>(Log.scala:35)
  at models.LogModel.class(Log.scala:34)
  while locating models.LogModel
  while locating services.AuditedModel annotated with @com.google.inject.internal.Element(setName=,uniqueId=7, type=MULTIBINDER, keyType=)
  while locating java.util.Set<services.AuditedModel>
  at global.TheHive.configure(TheHive.scala:34) (via modules: com.google.inject.util.Modules$OverrideModule -> global.TheHive -> net.codingwell.scalaguice.ScalaMultibinder$RealScalaMultibinder)
  while locating scala.collection.immutable.Set<services.AuditedModel>
    for the 2nd parameter of models.AuditModel.<init>(Audit.scala:59)
  at models.AuditModel.class(Audit.scala:47)
  while locating models.AuditModel
    for the 1st parameter of services.AuditActor.<init>(AuditSrv.scala:101)
  at services.AuditActor.class(AuditSrv.scala:101)
  while locating services.AuditActor
```

**Comment by crackytsi** [comment]
Hi,
Read the migration guide to 3.4 RC1, there it is described what you need to do...

I think especially something like:

`search.uri = "http://127.0.0.1:9200"`

is missing in your /etc/thehive/application.conf
