### ISSUE TITLE
Error while starting TheHive 3.4.0-RC1 with Docker

### ISSUE THREAD

**Issue by remiallain** [TheHive-Project/TheHive#1033]
# Error while starting TheHive 3.4.0-RC1 with Docker

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 9 
| OS version (client)       | Debian 9 
| TheHive version / git hash   | 3.4.0-RC1
| Package Type              | Docker

### Problem Description
When starting TheHive 3.4.0-RC1 with Docker, the following error `Recursive load of: models.CaseModel` appears several times until TheHive turns off.

I've already modify the configuration file as described in the migration guide.

```
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recursive load of: models.CaseModel.<init>(),
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2048),
    at com.google.common.cache.LocalCache.get(LocalCache.java:3850),
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3874),
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4799),
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4805),
    at com.google.inject.internal.FailableCache.get(FailableCache.java:51),
    at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:48),
    at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:595),
    at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:932),
    at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155),
    at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:852)
```

**Comment by JamesCullum** [comment]
See the comments here: https://github.com/TheHive-Project/TheHive/commit/d3c15bb1ea30e65898fc283ecc3b19be6d0e3239

> The docker image tagges as "latest" for cortex and thehive do not contain the 3.4 release, but elasticsearch was upgraded. This means that running this script (at least for me) doesnt work, until the 3.4 version is tagged as latest.

**Comment by remiallain** [comment]
The image I used was correctly set to 3.4.0-RC1. 

Below you have an extract of my compose file:


```yml
  thehive:
    image: thehiveproject/thehive:3.4.0-RC1
    depends_on:
      - cortex
    configs:
      - source: thehive-conf
        target: /etc/thehive/application.conf
    ports:
      - target: 9001
        published: 9011
        protocol: tcp
        mode: host
    networks: 
     - thehive-internal
    command: --cortex-url http://cortex:9001 --cortex-key {{CTX_KEY}} 
```

**Comment by To-om** [comment]
@remiallain, I can't reproduce your issue. Do you have, in your application.conf, something that can produce the recursive load (maybe a play.modules.enabled) ?

**Comment by remiallain** [comment]
Here is my application.conf: 

```conf
play {
    http {
        secret {
            key = "****"
        }
    }
    modules {
        enabled = [connectors.misp.MispConnector, connectors.cortex.CortexConnector]
    }
}

cortex {
    cortex1 {
        url = "http://cortex:9001"
        key = "****"
    }
}

webhooks {
    webhook1 {
        url = "http://webhooks:5000/webhook"
    }
}

misp {
    misplabo {
        url = "https://****"
        key = "****"
        tags = ["****"]  
    }
}

search {
  uri = "http://***.***.***.***:9200?cluster.name=****"
}

session {
  warning = 5m
  inactivity = 1h
}

auth {
    provider = [local]
}
```

**Comment by To-om** [comment]
You must not set `play.module.enabled` because default modules will be removed. You should only append value:
```
[...]
    modules {
        enabled += connectors.misp.MispConnector
        enabled += connectors.cortex.CortexConnector
    }
[...]
```
