### ISSUE TITLE
upgrade to 3.4.0-RC1 from 3.3.0-RC6 - mapper_parsing_exception

### ISSUE THREAD

**Issue by Idriel** [TheHive-Project/TheHive#1034]
On testing env everything went Ok, on prod. some errors. 

 => ElasticError(mapper_parsing_exception,Failed to parse mapping [doc]: No handler for type [join] declared on field [relations],None,None,None,List(ElasticError(mapper_parsing_exception,No handler for type [join] declared on field [relations],None,None,None,null,None)),Some(CausedBy(mapper_parsing_exception,No handler for type [join] declared on field [relations],Map())))
[error] o.e.s.MigrationSrv - Migration fail
org.elastic4play.InternalError: Unknown error: ElasticError(mapper_parsing_exception,Failed to parse mapping [doc]: No handler for type [join] declared on field [relations],None,None,None,List(ElasticError(mapper_parsing_exception,No handler for type [join] declared on field [relations],None,None,None,null,None)),Some(CausedBy(mapper_parsing_exception,No handler for type [join] declared on field [relations],Map())))
        at org.elastic4play.database.DBConfiguration.$anonfun$execute$2(DBConfiguration.scala:148)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
[info] o.e.ErrorHandler - POST /api/maintenance/migrate returned 500
org.elastic4play.InternalError: Unknown error: ElasticError(mapper_parsing_exception,Failed to parse mapping [doc]: No handler for type [join] declared on field [relations],None,None,None,List(ElasticError(mapper_parsing_exception,No handler for type [join] declared on field [relations],None,None,None,null,None)),Some(CausedBy(mapper_parsing_exception,No handler for type [join] declared on field [relations],Map())))
        at org.elastic4play.database.DBConfiguration.$anonfun$execute$2(DBConfiguration.scala:148)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)

**Comment by Idriel** [comment]
Upgraded elastic to 5.6, then there are handlers.
