### ISSUE TITLE
No reports available

### ISSUE THREAD

**Issue by yorchaac** [TheHive-Project/TheHive#1044]
| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 19.4(cortex), centos7 (the hive)
| TheHive version / git hash   | 3.3.1,

### Problem Description
Hello 
someone could help me, when I try to get a report on thehive I don't get nothing, I have the last report templates installed on my thehive; so I reviewed some issues reported before and I type some commands to get the next:
cortex and the-hive communication is OK!!

![imagen](https://user-images.githubusercontent.com/48779885/60842947-f80abe80-a19a-11e9-8ff5-e02078f7b343.png)

**Config of cortex in thehive**
cortex {
  "CORTEX" {
    url = "http://192.168.1.8:9001"
     key= "VCUKC8ji6ec8bmLzhadXyN9tAPFOa2lH"
  }
  # Check job update time interval
    refreshDelay = 1 minute
  # Maximum number of successive errors before give up
    maxRetryOnError = 3
  # Check remote Cortex status time interval
    statusCheckInterval = 1 minute
}
**If I ask by the status of api**
curl -H "Authorization: hive czb1i103jsR4UbIfkyOPKpJmBUTGX4Cd" http://192.168.1.8:9001/api/status
{"versions":{"Cortex":"2.1.3-1","Elastic4Play":"1.7.2","Play":"2.6.20","Elastic4s":"5.6.6","ElasticSearch client":"5.6.9","ElasticSearch cluster":"5.6.16"},"config":{"authType":["key","local"],"capabilities":["authByKey","changePassword","setPassword"]}}r

**If a try to get analyzers list from cortex**
curl -H "Authorization: hive czb1i103jsR4UbIfkyOPKpJmBUTGX4Cd" http://192.168.1.8:9001/api/analyzer
{"type":"AuthenticationError","message":"Authentication failure"}

From thehive is the same behavior

Cortex log
2019-07-08 14:17:42,853 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispatcher-16 - Authentication failure:
        session: AuthenticationError User session not found
        pki: AuthenticationError Certificate authentication is not configured
        key: AuthenticationError Only bearer authentication is supported
        basic: AuthenticationError Only basic authentication is supported
        init: AuthenticationError Use of initial user is forbidden because users exist in database
2019-07-08 14:17:42,854 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-16 - GET /api/analyzer returned 401
org.elastic4play.AuthenticationError: Authentication failure
        at org.elastic4play.controllers.Authenticated.$anonfun$getContext$4(Authenticated.scala:254)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by saadkadhi** [comment]
The API key you use to authenticate against Cortex corresponds to what kind of user? Superadmins cannot use/list analyzers. Only org admins and regular users can do so.

PS: you may want to change the API key which you provided for everyone to see here.

**Comment by yorchaac** [comment]
belong to user with roles of read,analyze
![imagen](https://user-images.githubusercontent.com/48779885/60917189-f9e58800-a255-11e9-8862-0dc86b1629c3.png)

**Comment by yorchaac** [comment]
please tell me If you need some extra information to send you

**Comment by nadouani** [comment]
Do you see the jobs starting in Cortex?

**Comment by yorchaac** [comment]
Just right now is working, something of my security infrastructure was blocking the communication between cortex and thehive, but now is working, thank you so much
