### ISSUE TITLE
Error downloading attachments with UTF-8 filenames

### ISSUE THREAD

**Issue by david-neal-ms** [TheHive-Project/TheHive#1068]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat
| OS version (client)       | Windows 7
| TheHive version    | 3.2.1-1
| Package Type              | From source
| Browser type & version    | Chrome

### Problem Description
The Hive can store an attachment with UTF-8 chars in the filename but it's unable to download it.

### Steps to Reproduce
1. Add a task log with an attachment containing a UTF-8 char in the filename
1. Attempt to download the file
1. Error "Character nnnnn cannot match AsciiSet because it is out of range" should be displayed.

### Complementary information
Log excerpt
```
Caused by: java.lang.IllegalArgumentException: Character 8211 cannot match AsciiSet because it is out of range
	at play.core.utils.AsciiBitSet.get(AsciiSet.scala:81)
	at play.core.server.common.ServerResultUtils.loop$1(ServerResultUtils.scala:122)
	at play.core.server.common.ServerResultUtils.validateString(ServerResultUtils.scala:126)
	at play.core.server.common.ServerResultUtils.validateHeaderValueChars(ServerResultUtils.scala:116)
	at play.core.server.akkahttp.AkkaModelConversion.$anonfun$convertHeaders$1(AkkaModelConversion.scala:287)
```

**Comment by github-pba** [comment]
@nadouani @saadkadhi Would you please mark this issue as a Bug? Thank you.
