### ISSUE TITLE
TheHive 3.4.0 setup fails at database initialization

### ISSUE THREAD

**Issue by iwitz** [TheHive-Project/TheHive#1180]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  RHEL 7
| OS version (client)       | Windows 10
| TheHive version / git hash   | 3.4.0
| Package Type              | RPM
| Browser type & version    | Firefox
| ElasticSearch Version    | Tried both 5.6 and 6.8

### Problem Description

When trying to install TheHive 3.4.0 on a new server with the RPM package, it seems that the database intialization is broken and, as such, **prevents the creation of the init user**.
Here's what I have in the logs after installing and starting TheHive and ElasticSearch and clicking the "Upgrade database" button :
`
2019-12-03 12:25:50,867 [ERROR] from models.Migration in application-akka.actor.default-dispatcher-2 - Failed to create dashboard /opt/thehive/migration/12/dashboards/Observable_statistics .json during migration
org.elastic4play.AttributeCheckingError: [Unknown attribute dashboard._version: {"type":"JsonInputValue","value":3}][Unknown attribute dashboard._id: {"type":"JsonInputValue","value":"fze65f4z135fe6zef43e2f"}][Unknown attribute dashboard._routing: {"type":"JsonInputValue","value":"fze65f4z135fe6zef43e2f"}][Unknown attribute dashboard._parent: {"type":"JsonInputValue","value":null}]
        at org.elastic4play.services.FieldsSrv.$anonfun$parse$7(FieldsSrv.scala:33)
        at org.scalactic.Bad.transform(Or.scala:1386)
        at org.elastic4play.services.FieldsSrv.parse(FieldsSrv.scala:33)
        at org.elastic4play.services.CreateSrv.create(CreateSrv.scala:105)
        at org.elastic4play.services.CreateSrv.apply(CreateSrv.scala:67)
        at services.DashboardSrv.create(DashboardSrv.scala:32)
        at models.Migration.$anonfun$addDashboards$8(Migration.scala:107)
        at scala.Option.map(Option.scala:146)
        at models.Migration.$anonfun$addDashboards$6(Migration.scala:104)
        at scala.collection.TraversableLike$WithFilter.$anonfun$flatMap$2(TraversableLike.scala:770)
        at scala.collection.Iterator.foreach(Iterator.scala:944)
        at scala.collection.Iterator.foreach$(Iterator.scala:944)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$WithFilter.flatMap(TraversableLike.scala:769)
        at models.Migration.$anonfun$addDashboards$2(Migration.scala:102)
        at services.UserSrv.inInitAuthContext(UserSrv.scala:56)
        at models.Migration.$anonfun$addDashboards$1(Migration.scala:99)
        at models.Migration.$anonfun$addDashboards$1$adapted(Migration.scala:97)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
`

After that, if I create the init account and try to log in, here's what's in the logs :

`
2019-12-03 14:54:08,589 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispatcher-16 - Authentication failure:
        session: AuthenticationError User session not found
        pki: AuthenticationError Certificate authentication is not configured
        key: AuthenticationError Authentication header not found
        init: AuthenticationError Use of initial user is forbidden because users exist in database
2019-12-03 14:54:08,589 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-16 - GET /api/list/ui_settings returned 401
org.elastic4play.AuthenticationError: Authentication failure
        at org.elastic4play.controllers.Authenticated.$anonfun$getContext$4(Authenticated.scala:272)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2019-12-03 14:54:08,594 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispatcher-16 - Authentication failure:
        session: AuthenticationError User session not found
        pki: AuthenticationError Certificate authentication is not configured
        key: AuthenticationError Authentication header not found
        init: AuthenticationError Use of initial user is forbidden because users exist in database
2019-12-03 14:54:08,594 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-16 - GET /api/user/current returned 401
org.elastic4play.AuthenticationError: Authentication failure
        at org.elastic4play.controllers.Authenticated.$anonfun$getContext$4(Authenticated.scala:272)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2019-12-03 14:54:08,597 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-6 - GET /api/stream/ofzeofnz65fze returned 401
org.elastic4play.AuthenticationError: Authentication header not found
        at org.elastic4play.controllers.Authenticated.$anonfun$getFromApiKey$1(Authenticated.scala:143)
        at scala.Option.fold(Option.scala:158)
        at org.elastic4play.controllers.Authenticated.getFromApiKey(Authenticated.scala:143)
        at controllers.StreamCtrl$$anonfun$1.applyOrElse(StreamCtrl.scala:103)
        at controllers.StreamCtrl$$anonfun$1.applyOrElse(StreamCtrl.scala:103)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:413)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
`

### Steps to Reproduce
1. Start TheHive and ElasticSearch
2. Open TheHive in a Web browser and click "Upgrade database"
3. Create an admin account
4. Try to log in with that account. It doesn't work.

I did not run into that issue when upgrading an existing TheHive installation to version 3.4.0.

### Possible Solutions
I tried to install TheHive 3.4.0 with either ES 5.6 and ES 6.8, I encountered the same issue with both.

**Comment by iwitz** [comment]
#1051 is similar

**Comment by iwitz** [comment]
I managed to log in with the admin using ES6 and TheHive 3.4 despite the errors by using the following ElasticSearch configuration :
```
transport.host: 127.0.0.1
script.allowed_types: inline
cluster.name: hive
http.host: 127.0.0.1
thread_pool.index.queue_size: 100000
thread_pool.search.queue_size: 100000
thread_pool.bulk.queue_size: 100000
```
I'm updating the [issue](https://github.com/TheHive-Project/TheHiveDocs/issues/133) I created about the Elasticsearch configuration.
