### ISSUE TITLE
[Feature Request] Implement case merging feature

### ISSUE THREAD

**Issue by yorkvik** [TheHive-Project/TheHive#1264]
When trying to merge cases, got this error in the logs:

```
[warn] o.t.s.ErrorHandler - POST /api/case/40976496/_merge/81973472 returned 404
org.thp.scalligraph.NotFoundError: /api/case/40976496/_merge/81973472
	at org.thp.scalligraph.ScalligraphRouter$$anonfun$2.$anonfun$applyOrElse$4(ScalligraphRouter.scala:102)
	at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.$anonfun$invokeBlock$2(SessionAuthSrv.scala:84)
	at scala.Option.fold(Option.scala:251)
	at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.invokeBlock(SessionAuthSrv.scala:82)
	at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.invokeBlock(SessionAuthSrv.scala:79)
	at org.thp.scalligraph.ScalligraphRouter$$anonfun$2.$anonfun$applyOrElse$3(ScalligraphRouter.scala:102)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:441)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:439)
	at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:379)
	at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
```

**Comment by To-om** [comment]
Currently, case merge is not implemented. The result of the merge of two shared cases is not specified yet.
First, we will implement the merge of unshared cases.

**Comment by david-neal-ms** [comment]
Do you have an estimate on when this functionality will be added?

**Comment by zohkoo** [comment]
We were working on migrating our instance from TheHive 3.4.4 to TheHive 4.0.4. The migration worked well but during our regression tests, we discovered that it was not possible to merge cases together. As we have workflows relying on this functionality, it will be difficult for us to use TheHive 4 in production for the moment. 

Could this functionality be added in a future milestone ?

P.S. : Are there other great functionalities like this one from TheHive 3 that are not implemented in TheHive 4 ?
