### ISSUE TITLE
[Bug] error when closing a reopened case

### ISSUE THREAD

**Issue by sisecbe** [TheHive-Project/TheHive#1271]
Getting an error when trying to close a case after reopening it:

[error] o.t.s.m.Database - Exception raised, rollback (Too many elements in result (2 found))

Unable to close the case.

**Comment by sisecbe** [comment]
Full error log:
```
[error] o.t.s.u.Retry - uncaught error, not retrying
org.thp.scalligraph.InternalError: Too many elements in result (2 found)
	at org.thp.scalligraph.steps.BaseTraversal.atMostOneOf(BaseTraversal.scala:48)
	at org.thp.scalligraph.steps.BaseTraversal.atMostOneOf$(BaseTraversal.scala:45)
	at org.thp.scalligraph.steps.BaseElementSteps.atMostOneOf(ModelSteps.scala:34)
	at org.thp.thehive.services.CaseSteps.$anonfun$richCase$2(CaseSrv.scala:523)
	at gremlin.scala.GremlinScala.$anonfun$map$1(GremlinScala.scala:166)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.LambdaMapStep.map(LambdaMapStep.java:42)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.MapStep.processNextStart(MapStep.java:37)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.fill(Traversal.java:180)
```
