### ISSUE TITLE
[Bug] SSL cert with SAN does not work

### ISSUE THREAD

**Issue by vimtechnologies** [TheHive-Project/TheHive#1304]
Bug
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian, 
| OS version (client)       | 10, 
| Browser type & version    | All

### Problem Description
When you create a keystore, set the password, create a private key, create a CSR, and import a certificate where the certificate is not specified the SAN(subject alternative name) it works fine, the certificate is installed. However, when you create a Keystore and in the certificate, a SAN is specified it does not work at all and fails to load the webpage. The application logs report the following 

`2020-04-30 15:08:10,206 [ERROR] from akka.actor.OneForOneStrategy in application-akka.actor.default-dispatcher-15 - Cannot recover key
akka.actor.ActorInitializationException: akka://application/system/StreamSupervisor-0/flow-87-1: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:193)
        at akka.actor.ActorCell.create(ActorCell.scala:673)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:527)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:549)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.security.UnrecoverableKeyException: Cannot recover key
        at java.base/sun.security.provider.KeyProtector.recover(KeyProtector.java:304)
        at java.base/sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:144)
        at java.base/sun.security.util.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:90)
        at java.base/java.security.KeyStore.getKey(KeyStore.java:1057)
        at java.base/sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:145)`

### Steps to Reproduce
1. create a private key
2. create a Keystore 
3. import key 
4. create a CSR 
5. import certificate
6. change application.conf with 

https.port: 9443
play.server.https.keyStore {
  path: "/path/thehive.jks"
  type: "JKS"
  password: "password"
}

**Comment by To-om** [comment]
Managing SSL directly by TheHive is not supported (#1260, #813). Configure a reverse proxy in front of TheHive: https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#101-https-using-a-reverse-proxy
