### ISSUE TITLE
[Bug] AD authentication failure / Clarification on AD Authentication

### ISSUE THREAD

**Issue by nicpenning** [TheHive-Project/TheHive#1453]
# Documentation Clarification on AD Authentication

### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Windows 10
| TheHive version / git hash   | 4.0.0-1
| Package Type              |  DEB
| Browser type & version    | Chrome

### Problem Description
We are failing to authenticate to Active Directory with the format of user@acme.org.

### Steps to Reproduce
1. Setup TheHive and modify the application.conf to use the ad provider
auth {
        providers = [
          {name: session}
          {name: ad, hosts: ["server1.acme.local", "server2.acme.local"], dnsDomain: "acme.local", winDomain: "ACME"}
          {name: basic, realm: thehive}
          {name: local}
          {name: key}
        ]

}
2. Start TheHive and try and login with a user that exists in TheHive - user@acme.org
3. Fail to login:

[error] o.t.s.a.ADAuthSrv - AD authentication failure
javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C090442, comment: AcceptSecurityContext error, data 52e, v3839]
        at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3154)
        at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3100)
        at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2886)
        at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2800)
        at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:319)
        at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
        at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
        at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
        at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
        at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
[error] o.t.t.s.TOTPAuthSrv - Authentication failure
org.thp.scalligraph.AuthenticationError: Operation not supported
        at org.thp.scalligraph.auth.AuthSrv.authenticate(AuthSrv.scala:55)
        at org.thp.scalligraph.auth.AuthSrv.authenticate$(AuthSrv.scala:52)
        at org.thp.scalligraph.auth.KeyAuthSrv.authenticate(KeyAuthSrv.scala:11)
        at org.thp.scalligraph.auth.MultiAuthSrv.$anonfun$authenticate$1(MultiAuthSrv.scala:71)
        at org.thp.scalligraph.auth.MultiAuthSrv$$anonfun$$nestedInanonfun$forAllAuthProvider$1$1.applyOrElse(MultiAuthSrv.scala:59)
        at org.thp.scalligraph.auth.MultiAuthSrv$$anonfun$$nestedInanonfun$forAllAuthProvider$1$1.applyOrElse(MultiAuthSrv.scala:57)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
        at scala.util.Failure.recoverWith(Try.scala:236)
        at org.thp.scalligraph.auth.MultiAuthSrv.$anonfun$forAllAuthProvider$1(MultiAuthSrv.scala:57)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[warn] o.t.s.ErrorHandler - POST /api/login returned 401: Authentication failure

### Possible Solutions
Not sure if this has been fully implemented yet but if it has, any direction on how to get it to work would be great!

### Complementary information
We have not been able to get any type of AD authentication to work with various configuration changes. Will supply any details need to resolve!

**Comment by nadouani** [comment]
Hello @nicpenning We will take a look and let ou know if something is wrong in your side.

**Comment by To-om** [comment]
TheHive stores user login in email format.
@nicpenning in the login page, do you use the short format of the login (left part of email format, without '@') ? Your user does it exist in AD and in TheHive ?

**Comment by nicpenning** [comment]
Hello @To-om ,

My user is in TheHive and in AD. However, in TheHive the user name is the full address with the following format: user.name@acme.state.local

We cannot use the short format because the user account must be in the long format as shown above. 

Does that help?

**Comment by To-om** [comment]
I'll fix the login format problem.
In the meantime, you can set `auth.defaultUserDomain: "acme.state.local"` in your application.conf and use the short user name to login.

**Comment by nicpenning** [comment]
That worked for our short user name! Which is obviously much different than email address, so instead of user.name@acme.state.state.local we were able to use acmeuser123 with the configuration changes you supplied above.

**Comment by meelich** [comment]
Are there any updates on this? We are still having issues authenticating against AD.
Unfortunately, the workaround does not work for us, we're still getting the above referenced authentication error  javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C090442, comment: AcceptSecurityContext error, data 52e, v3839]

Thanks.

**Comment by Andraaada** [comment]
Hello @To-om ,

I have applied the workaround that you suggested. Works perfectly fine for the AD users, but I can see this user trying to authenticate from time to time **system@mydomain.local**, which indeed is not part of my domain - is this a hive default user working in the background?

2020-10-13 18:53:35,636 [WARN] from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-7049 [00004b66|] **GET /api/v1/user/system@mydomain.local returned 404**
org.thp.scalligraph.NotFoundError: **User not found**
        at org.thp.scalligraph.steps.StepsOps$TraversalOps.$anonfun$getOrFail$1(StepsOps.scala:384)
        at scala.Option.fold(Option.scala:251)
        at org.thp.scalligraph.steps.StepsOps$TraversalOps.getOrFail(StepsOps.scala:384)
        at org.thp.thehive.controllers.v1.UserCtrl.$anonfun$get$2(UserCtrl.scala:130)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$authRoTransaction$2(Entrypoint.scala:136)
        at org.thp.scalligraph.janus.JanusDatabase.roTransaction(JanusDatabase.scala:133)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$authRoTransaction$1(Entrypoint.scala:136)

**Comment by nicpenning** [comment]
@meelich You need post your current config as I don't think you have the correct settings from the other issue posted.

Make sure you have this field:
auth.defaultUserDomain: "acme.state.local"

To be more complete, do this in your config for TheHive 4:
```
auth.defaultUserDomain: "internalcompany.net"
auth {
	providers: [
		{name: session} # required !
		{name: basic, realm: thehive}
		{name: ad, hosts: ["dc.internalcompany.net"], dnsDomain: "internalcompany.net", winDomain: "COMPANY"}
		{name: local}
		{name: key}
	]
}
```

**Comment by meelich** [comment]
@nicpenning : It finally works, thanks for taking the time to see me through it.
I am not sure what exactly caused the issue, but after removing everything, copying and pasting your config and then replacing it with our values finally seemed to fix the issue. - I must have done this a dozen times, but apparently the x-th time was the charm. 
Thanks.

**Comment by nicpenning** [comment]
@meelich, no problem! I think it was that you had provider instead providers in your config. Glad it works!

**Comment by nicpenning** [comment]
Hey @To-om! Just curious when this will be addressed. I see it was removed from the 4.0.1 release. 😁

**Comment by nicpenning** [comment]
Closing as deprecated.
