### ISSUE TITLE
TheHive4 not listening on port 9000 in RedHat 

### ISSUE THREAD

**Issue by jjoseph8008** [TheHive-Project/TheHive#1462]
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat
| OS version (client)       | Windows 10
| TheHive version / git hash   | 4 (beta)
| Package Type              | RPM
| Browser type & version    | If applicable

### Problem Description
I installed TheHive 4 and Cassandra using the steps in https://github.com/TheHive-Project/TheHiveDocs/blob/master/TheHive4/Installation/Install_rpm.md#installation-1
I am able to start cassandra and TheHive. Cassandra ports are listening and show up under netstat. TheHive shows started, but ports are not listening. I tried both stable and beta versions of thehive 4. Below is the application log file. I was wondering if someone has any solution for this. 
2020-08-05 10:46:25,453 [INFO] from org.thp.scalligraph.ScalligraphModule in main [|] Loading scalligraph module
2020-08-05 10:46:34,904 [INFO] from akka.event.slf4j.Slf4jLogger in application-akka.actor.default-dispatcher-6 [|] Slf4jLogger started
2020-08-05 10:46:35,337 [INFO] from akka.remote.artery.tcp.ArteryTcpTransport in application-akka.actor.default-dispatcher-6 [|] Remoting started with transport [Artery tcp]; listening on address [akka://application@127.0.0.1:38803] with UID [-8092047785448443625]
2020-08-05 10:46:35,362 [INFO] from akka.cluster.Cluster in application-akka.actor.default-dispatcher-6 [|] Cluster Node [akka://application@127.0.0.1:38803] - Starting up, Akka version [2.6.5] ...
2020-08-05 10:46:35,599 [INFO] from akka.cluster.Cluster in application-akka.actor.default-dispatcher-6 [|] Cluster Node [akka://application@127.0.0.1:38803] - Registered cluster JMX MBean [akka:type=Cluster]
2020-08-05 10:46:35,599 [INFO] from akka.cluster.Cluster in application-akka.actor.default-dispatcher-6 [|] Cluster Node [akka://application@127.0.0.1:38803] - Started up successfully
2020-08-05 10:46:35,669 [INFO] from akka.cluster.Cluster in application-akka.actor.default-dispatcher-6 [|] Cluster Node [akka://application@127.0.0.1:38803] - No downing-provider-class configured, manual cluster downing required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#downing
2020-08-05 10:46:35,669 [INFO] from akka.cluster.Cluster in application-akka.actor.default-dispatcher-6 [|] Cluster Node [akka://application@127.0.0.1:38803] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#joining
2020-08-05 10:46:37,157 [INFO] from com.datastax.driver.core in main [|] DataStax Java driver 3.9.0 for Apache Cassandra
2020-08-05 10:46:37,161 [INFO] from com.datastax.driver.core.GuavaCompatibility in main [|] Detected Guava >= 19 in the classpath, using modern compatibility layer
2020-08-05 10:46:37,356 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,441 [INFO] from com.datastax.driver.core.NettyUtil in main [|] Found Netty's native epoll transport in the classpath, using it
2020-08-05 10:46:37,594 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,612 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,628 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,641 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,654 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,670 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,685 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,711 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,723 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,768 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,797 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,819 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,843 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,856 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,871 [INFO] from com.datastax.driver.core.ClockFactory in application-akka.actor.default-dispatcher-6 [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,901 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:37,948 [ERROR] from akka.actor.OneForOneStrategy in application-akka.actor.default-dispatcher-6 [|] Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CQLStoreManager
  at org.thp.scalligraph.janus.JanusDatabase.<init>(JanusDatabase.scala:71)
  at org.thp.scalligraph.janus.JanusDatabase.class(JanusDatabase.scala:56)
  while locating org.thp.scalligraph.janus.JanusDatabase
  while locating org.thp.scalligraph.models.Database
    for the 1st parameter of org.thp.thehive.models.DatabaseProvider.<init>(SchemaUpdaterActor.scala:20)
  at org.thp.thehive.models.DatabaseProvider.class(SchemaUpdaterActor.scala:19)
  while locating org.thp.thehive.models.DatabaseProvider
  while locating org.thp.scalligraph.models.Database annotated with @com.google.inject.name.Named(value=with-thehive-schema)
    for the 4th parameter of org.thp.thehive.services.AuditSrv.<init>(AuditSrv.scala:28)
  at org.thp.thehive.services.AuditSrv.class(AuditSrv.scala:27)
  while locating org.thp.thehive.services.AuditSrv
    for the 3rd parameter of org.thp.thehive.services.notification.NotificationActor.<init>(NotificationActor.scala:76)
  while locating org.thp.thehive.services.notification.NotificationActor

1 error
akka.actor.ActorInitializationException: akka://application/user/notification-actor: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:196)
	at akka.actor.ActorCell.create(ActorCell.scala:659)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:511)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:533)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CQLStoreManager
  at org.thp.scalligraph.janus.JanusDatabase.<init>(JanusDatabase.scala:71)
  at org.thp.scalligraph.janus.JanusDatabase.class(JanusDatabase.scala:56)
  while locating org.thp.scalligraph.janus.JanusDatabase
  while locating org.thp.scalligraph.models.Database
    for the 1st parameter of org.thp.thehive.models.DatabaseProvider.<init>(SchemaUpdaterActor.scala:20)
  at org.thp.thehive.models.DatabaseProvider.class(SchemaUpdaterActor.scala:19)
  while locating org.thp.thehive.models.DatabaseProvider
  while locating org.thp.scalligraph.models.Database annotated with @com.google.inject.name.Named(value=with-thehive-schema)
    for the 4th parameter of org.thp.thehive.services.AuditSrv.<init>(AuditSrv.scala:28)
  at org.thp.thehive.services.AuditSrv.class(AuditSrv.scala:27)
  while locating org.thp.thehive.services.AuditSrv
    for the 3rd parameter of org.thp.thehive.services.notification.NotificationActor.<init>(NotificationActor.scala:76)
  while locating org.thp.thehive.services.notification.NotificationActor

1 error
	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1097)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131)
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:436)
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:431)
	at play.api.inject.ContextClassLoaderInjector.$anonfun$instanceOf$2(Injector.scala:119)
	at play.api.inject.ContextClassLoaderInjector.withContext(Injector.scala:128)
	at play.api.inject.ContextClassLoaderInjector.instanceOf(Injector.scala:119)
	at play.api.libs.concurrent.ActorRefProvider.$anonfun$get$1(Akka.scala:268)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:91)
	at akka.actor.Props.newActor(Props.scala:226)
	at akka.actor.ActorCell.newActor(ActorCell.scala:611)
	at akka.actor.ActorCell.create(ActorCell.scala:637)
	... 9 common frames omitted
Caused by: java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CQLStoreManager
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:64)
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:440)
	at org.janusgraph.diskstorage.Backend.getStorageManager(Backend.java:411)
	at org.janusgraph.graphdb.configuration.builder.GraphDatabaseConfigurationBuilder.build(GraphDatabaseConfigurationBuilder.java:50)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:161)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:132)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:112)
	at org.thp.scalligraph.janus.JanusDatabase$.openDatabase(JanusDatabase.scala:51)
	at org.thp.scalligraph.janus.JanusDatabase.<init>(JanusDatabase.scala:72)
	at org.thp.scalligraph.janus.JanusDatabase$$FastClassByGuice$$113881e3.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:60)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094)
	... 20 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:58)
	... 60 common frames omitted
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1:9042] Cannot connect))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:268)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:107)
	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1813)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1726)
	at com.datastax.driver.core.Cluster.init(Cluster.java:214)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:387)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:366)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:311)
	at org.janusgraph.diskstorage.cql.CQLStoreManager.initializeSession(CQLStoreManager.java:320)
	at org.janusgraph.diskstorage.cql.CQLStoreManager.<init>(CQLStoreManager.java:182)
	... 65 common frames omitted
2020-08-05 10:46:37,949 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,426 [INFO] from org.reflections.Reflections in main [|] Reflections took 425 ms to scan 1 urls, producing 142 keys and 2211 values 
2020-08-05 10:46:38,440 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,468 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,493 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,541 [INFO] from org.thp.thehive.ClusterSetup in main [|] Initialising cluster
2020-08-05 10:46:38,545 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,588 [INFO] from akka.cluster.Cluster in application-akka.actor.default-dispatcher-11 [|] Cluster Node [akka://application@127.0.0.1:38803] - Node [akka://application@127.0.0.1:38803] is JOINING itself (with roles [dc-default]) and forming new cluster
2020-08-05 10:46:38,588 [INFO] from akka.cluster.Cluster in application-akka.actor.default-dispatcher-11 [|] Cluster Node [akka://application@127.0.0.1:38803] - is the new leader among reachable nodes (more leaders may exist)
2020-08-05 10:46:38,605 [INFO] from akka.cluster.Cluster in application-akka.actor.default-dispatcher-11 [|] Cluster Node [akka://application@127.0.0.1:38803] - Leader is moving node [akka://application@127.0.0.1:38803] to [Up]
2020-08-05 10:46:38,654 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,673 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,680 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,697 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,822 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,829 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,848 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,856 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,885 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,935 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,950 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,977 [INFO] from akka.cluster.singleton.ClusterSingletonManager in application-akka.actor.default-dispatcher-6 [|] Singleton manager starting singleton actor [akka://application/user/integrityCheckSingletonManager/singleton]
2020-08-05 10:46:38,984 [INFO] from akka.cluster.singleton.ClusterSingletonManager in application-akka.actor.default-dispatcher-10 [|] ClusterSingletonManager state change [Start -> Oldest]
2020-08-05 10:46:38,987 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:38,999 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:39,042 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:39,094 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:39,180 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:39,214 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:39,246 [INFO] from com.datastax.driver.core.ClockFactory in application-akka.actor.default-dispatcher-6 [|] Using native clock to generate timestamps.
2020-08-05 10:46:39,269 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:39,276 [ERROR] from akka.actor.OneForOneStrategy in application-akka.actor.default-dispatcher-6 [|] Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CQLStoreManager
  at org.thp.scalligraph.janus.JanusDatabase.<init>(JanusDatabase.scala:71)
  at org.thp.scalligraph.janus.JanusDatabase.class(JanusDatabase.scala:56)
  while locating org.thp.scalligraph.janus.JanusDatabase
  while locating org.thp.scalligraph.models.Database
    for the 1st parameter of org.thp.thehive.models.DatabaseProvider.<init>(SchemaUpdaterActor.scala:20)
  at org.thp.thehive.models.DatabaseProvider.class(SchemaUpdaterActor.scala:19)
  while locating org.thp.thehive.models.DatabaseProvider
  while locating org.thp.scalligraph.models.Database annotated with @com.google.inject.name.Named(value=with-thehive-schema)
    for the 1st parameter of org.thp.thehive.services.ProfileIntegrityCheckOps.<init>(ProfileSrv.scala:88)
  while locating org.thp.thehive.services.ProfileIntegrityCheckOps
  while locating org.thp.scalligraph.services.GenIntegrityCheckOps annotated with @com.google.inject.internal.Element(setName=,uniqueId=26, type=MULTIBINDER, keyType=)
  while locating java.util.Set<org.thp.scalligraph.services.GenIntegrityCheckOps>

1 error
akka.actor.ActorInitializationException: akka://application/user/integrityCheckSingletonManager/singleton: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:196)
	at akka.actor.ActorCell.create(ActorCell.scala:659)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:511)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:533)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CQLStoreManager
  at org.thp.scalligraph.janus.JanusDatabase.<init>(JanusDatabase.scala:71)
  at org.thp.scalligraph.janus.JanusDatabase.class(JanusDatabase.scala:56)
  while locating org.thp.scalligraph.janus.JanusDatabase
  while locating org.thp.scalligraph.models.Database
    for the 1st parameter of org.thp.thehive.models.DatabaseProvider.<init>(SchemaUpdaterActor.scala:20)
  at org.thp.thehive.models.DatabaseProvider.class(SchemaUpdaterActor.scala:19)
  while locating org.thp.thehive.models.DatabaseProvider
  while locating org.thp.scalligraph.models.Database annotated with @com.google.inject.name.Named(value=with-thehive-schema)
    for the 1st parameter of org.thp.thehive.services.ProfileIntegrityCheckOps.<init>(ProfileSrv.scala:88)
  while locating org.thp.thehive.services.ProfileIntegrityCheckOps
  while locating org.thp.scalligraph.services.GenIntegrityCheckOps annotated with @com.google.inject.internal.Element(setName=,uniqueId=26, type=MULTIBINDER, keyType=)
  while locating java.util.Set<org.thp.scalligraph.services.GenIntegrityCheckOps>

1 error
	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1097)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1126)
	at org.thp.thehive.services.IntegrityCheckActor.integrityCheckOps$lzycompute(IntegrityCheckActor.scala:34)
	at org.thp.thehive.services.IntegrityCheckActor.integrityCheckOps(IntegrityCheckActor.scala:33)
	at org.thp.thehive.services.IntegrityCheckActor.preStart(IntegrityCheckActor.scala:55)
	at akka.actor.Actor.aroundPreStart(Actor.scala:546)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:546)
	at org.thp.thehive.services.IntegrityCheckActor.aroundPreStart(IntegrityCheckActor.scala:25)
	at akka.actor.ActorCell.create(ActorCell.scala:639)
	... 9 common frames omitted
Caused by: java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CQLStoreManager
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:64)
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:440)
	at org.janusgraph.diskstorage.Backend.getStorageManager(Backend.java:411)
	at org.janusgraph.graphdb.configuration.builder.GraphDatabaseConfigurationBuilder.build(GraphDatabaseConfigurationBuilder.java:50)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:161)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:132)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:112)
	at org.thp.scalligraph.janus.JanusDatabase$.openDatabase(JanusDatabase.scala:51)
	at org.thp.scalligraph.janus.JanusDatabase.<init>(JanusDatabase.scala:72)
	at org.thp.scalligraph.janus.JanusDatabase$$FastClassByGuice$$113881e3.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:60)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:198)
	at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:151)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:113)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094)
	... 17 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedConstructorAccessor6.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:58)
	... 54 common frames omitted
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1:9042] Cannot connect))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:268)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:107)
	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1813)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1726)
	at com.datastax.driver.core.Cluster.init(Cluster.java:214)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:387)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:366)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:311)
	at org.janusgraph.diskstorage.cql.CQLStoreManager.initializeSession(CQLStoreManager.java:320)
	at org.janusgraph.diskstorage.cql.CQLStoreManager.<init>(CQLStoreManager.java:182)
	... 58 common frames omitted
2020-08-05 10:46:39,280 [INFO] from akka.cluster.singleton.ClusterSingletonManager in application-akka.actor.default-dispatcher-6 [|] Singleton actor [akka://application/user/integrityCheckSingletonManager/singleton] was terminated
2020-08-05 10:46:39,294 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:39,299 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:39,304 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.
2020-08-05 10:46:39,308 [INFO] from com.datastax.driver.core.ClockFactory in main [|] Using native clock to generate timestamps.

**Comment by jjoseph8008** [comment]
Adding application.conf file
## Include Play secret key
# More information on secret key at https://www.playframework.com/documentation/2.8.x/ApplicationSecret
include "/etc/thehive/secret.conf"

## Database configuration
db {
  provider: janusgraph
  janusgraph {
    storage {
      backend: cql
      hostname: [
        "127.0.0.1"
      ] # seed node ip addresses

      #username: "<cassandra_username>"       # login to connect to database (if configured in Cassandra)
      #password: "<cassandra_passowrd"

      cql {
        cluster-name: thp       # cluster name
        keyspace: thehive           # name of the keyspace
        // local-datacenter: datacenter1   # name of the datacenter where TheHive runs (relevant only on multi datacenter setup)
        # replication-factor: 2 # number of replica
        read-consistency-level: ONE
        write-consistency-level: ONE
      }
    }
  }
}

## Attachment storage configuration
storage {
  ## Local filesystem
  provider: localfs
  localfs.location: /opt/thp_data/files/thehive

  ## Hadoop filesystem (HDFS)
  // provider: hdfs
  // hdfs {
  //   root: "hdfs://localhost:10000" # namenode server hostname
  //   location: "/thehive"           # location inside HDFS
  //   username: thehive              # file owner
  // }
}

**Comment by marcoordonez0703** [comment]
Hi. What was the solution to this problem?

**Comment by jjoseph8008** [comment]
It was the firewalld service blocking the port on redhat 7.
