### ISSUE TITLE
[Bug] Header authentication broken since official release (was working in RC2)

### ISSUE THREAD

**Issue by vletoux** [TheHive-Project/TheHive#1466]
Header authentication broken since official release (was working in RC3)

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian,
| OS version (client)       | 10
| TheHive version / git hash   | 4.0.0
| Package Type              | DEB
| Browser type & version    | Firefox

### Problem Description
With header authentication, the user is facing constantly a blank page when logging.
Authentication with header was configured in TheHive 4.0 RC2 and stop working when the new release was delivered.
Disabling header authentication (manually password authentication) is working.

### Steps to Reproduce
1. Configure the Hive with apache2 as reverse proxy
1. Set the header to configure the authentication: `RequestHeader set THEHIVE_USER foo@bar.com`
1. Configure theHive for header authentication: 
```
auth {
  providers: [
    {name: session}               # required !
{name:local}
    {name: key}
{name: header, userHeader: "THEHIVE_USER"}
]

}
```
1. Restart
1. Open the application
1. When opening the developper tool, we can see that the application call the page /api/v1/user/current and a 500 error happens
1. When looking at the hive look, we find out a problem relating to setting cookies:
```
java.lang.IllegalArgumentException: Cookie value contains an invalid char:
        at play.core.cookie.encoding.CookieEncoder.validateCookie(CookieEncoder.java:46)
        at play.core.cookie.encoding.ServerCookieEncoder.encode(ServerCookieEncoder.java:71)
        at play.api.mvc.CookieHeaderEncoding.$anonfun$encodeSetCookieHeader$1(Cookie.scala:273)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike.map(TraversableLike.scala:273)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
        at scala.collection.immutable.List.map(List.scala:298)
        at play.api.mvc.CookieHeaderEncoding.encodeSetCookieHeader(Cookie.scala:264)
        at play.api.mvc.CookieHeaderEncoding.encodeSetCookieHeader$(Cookie.scala:262)
        at play.api.mvc.DefaultCookieHeaderEncoding.encodeSetCookieHeader(Cookie.scala:374)
        at play.api.mvc.Result.bakeCookies(Results.scala:369)
        at play.core.server.common.ServerResultUtils.prepareCookies(ServerResultUtils.scala:291)
        at play.core.server.AkkaHttpServer.$anonfun$runAction$5(AkkaHttpServer.scala:432)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$2(ContextPropagatingDisptacher.scala:56)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.thp.scalligraph.DiagnosticContext$.$anonfun$withDiagnosticContext$2(ContextPropagatingDisptacher.scala:91)
        at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:106)
        at org.thp.scalligraph.DiagnosticContext$.withDiagnosticContext(ContextPropagatingDisptacher.scala:89)
        at org.thp.scalligraph.DiagnosticContext$$anon$2.withContext(ContextPropagatingDisptacher.scala:74)
        at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$1(ContextPropagatingDisptacher.scala:56)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Possible Solutions
No idea

### Complementary information
I tried to investigate if there was a hidden char or a proxy affecting the variables received by the hive.
By parsing the code, I found out the log was showing the character. In this case, it was a normal space (0x20)
I supposed there may be some problem with the cookie and I reflected it in an output header of Apache.
Here is what I tried:
`Header set MELLON_NAME_ID "expr=%{HTTP_COOKIE}"`
The cookie looked normal.
From the code, I understand that this is the server which is trying to build a cookie.

**Comment by crackytsi** [comment]
Strange, for me it seems to work...
My config is like this:
```
auth {
  providers = [
    {name: session}
    {name: basic, realm: thehive}
    {name: header, userHeader:HEADERUSER}
    {name: key}
    {name: local}
  ]
  defaultUserDomain: "test.local"
}
auth.multifactor.enabled = false

```

**Comment by crackytsi** [comment]
I guess your qutoations are wrong...

**Comment by vletoux** [comment]
the user name contains a @ (it's my professional email address).
Is your user name just a standard username ?

**Comment by vletoux** [comment]
Found out.
Users created in RC2 have a problem.
Users need to be deleted and recreated in order to have header authentication working.
Investigation in progress.

**Comment by trinksie** [comment]
Hi! I experience the exact same thing. Header authentication worked fine in RC3 and is broken with latest final release. I see the same cookie invalid char issue and I have pretty much the same config setup as @vletoux . One thing I noticed in the logs is that the - following Kerberos realm convention - the domain of the user set via RequestHeader in Apache is in upper-case letters, e.g. user@EXAMPLE.COM. At the same time The Hive 4.0 does not allow for upper-case letters, so a newly created user would have the email user@example.com in there. Not sure if that matters. It would be great if this bug could be revisited and GSSAPI authentication via RequestHeader made available again. Thanks!
