### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by AndyWeaverPPT** [TheHive-Project/TheHive#1477]
TheHive cannot find the ElasticSearch cluster upon startup in Docker container

### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS
| OS version (client)       | 10
| TheHive version / git hash   | 3.x / Latest
| Package Type              | Docker
| Browser type & version    | Chrome 84.0.4147.125

### Problem Description
TheHive cannot contact ElasticSearch cluster.  Upon first access to TheHive after startup of docker containers, the webpage shows a popup of "App ElasticSearch cluster is not reachable".  It appears that TheHive continues to get an error 500:

2020-08-12 21:34:31,491 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-4 - GET /api/user/current returned 500
com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: java.net.ConnectException
	at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:63)

Review of TheHive log shows 

### Steps to Reproduce
1.  Startup of TheHive/ElasticSearch/Cortex via docker-compose.yml (below)
2.  Open browser, browse to http://{ip-of-vm}:9000
3.  Initial splash screen of bouncing box is complemented by the error message in the lower left of the screen

## docker-compose.yml:

version: "2"
services:
  elasticsearch:
    image: elasticsearch:6.8.8
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  cortex:
    image: thehiveproject/cortex:latest
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
  thehive:
    image: thehiveproject/thehive:latest
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
    command: --cortex-port 9001

## TheHive application log
2020-08-12 21:32:46,306 [INFO] from org.reflections.Reflections in main - Reflections took 1076 ms to scan 4 urls, producing 119 keys and 1312 values 
2020-08-12 21:32:46,545 [INFO] from module in main - Loading model class org.elastic4play.services.DBListModel
2020-08-12 21:32:46,545 [INFO] from module in main - Loading model class models.DashboardModel
2020-08-12 21:32:46,545 [INFO] from module in main - Loading model class models.ArtifactModel
2020-08-12 21:32:46,546 [INFO] from module in main - Loading model class models.LogModel
2020-08-12 21:32:46,546 [INFO] from module in main - Loading model class models.AlertModel
2020-08-12 21:32:46,546 [INFO] from module in main - Loading model class models.CaseTemplateModel
2020-08-12 21:32:46,546 [INFO] from module in main - Loading model class connectors.cortex.models.ReportTemplateModel
2020-08-12 21:32:46,546 [INFO] from module in main - Loading model class models.AuditModel
2020-08-12 21:32:46,546 [INFO] from module in main - Loading model class models.TaskModel
2020-08-12 21:32:46,546 [INFO] from module in main - Loading model class connectors.cortex.models.ActionModel
2020-08-12 21:32:46,547 [INFO] from module in main - Loading model class models.UserModel
2020-08-12 21:32:46,547 [INFO] from module in main - Loading model class connectors.cortex.models.JobModel
2020-08-12 21:32:46,547 [INFO] from module in main - Loading model class org.elastic4play.services.AttachmentModel
2020-08-12 21:32:46,547 [INFO] from module in main - Loading model class models.CaseModel
2020-08-12 21:32:57,967 [INFO] from akka.event.slf4j.Slf4jLogger in application-akka.actor.default-dispatcher-2 - Slf4jLogger started
2020-08-12 21:32:58,274 [INFO] from akka.remote.Remoting in application-akka.actor.default-dispatcher-4 - Starting remoting
2020-08-12 21:32:59,370 [INFO] from akka.remote.Remoting in application-akka.actor.default-dispatcher-4 - Remoting started; listening on addresses :[akka.tcp://application@172.18.0.4:2552]
2020-08-12 21:32:59,385 [INFO] from akka.remote.Remoting in application-akka.actor.default-dispatcher-4 - Remoting now listens on addresses: [akka.tcp://application@172.18.0.4:2552]
2020-08-12 21:32:59,565 [INFO] from akka.cluster.Cluster(akka://application) in application-akka.actor.default-dispatcher-4 - Cluster Node [akka.tcp://application@172.18.0.4:2552] - Starting up, Akka version [2.5.21] ...
2020-08-12 21:33:00,217 [INFO] from akka.cluster.Cluster(akka://application) in application-akka.actor.default-dispatcher-3 - Cluster Node [akka.tcp://application@172.18.0.4:2552] - Registered cluster JMX MBean [akka:type=Cluster]
2020-08-12 21:33:00,229 [INFO] from akka.cluster.Cluster(akka://application) in application-akka.actor.default-dispatcher-3 - Cluster Node [akka.tcp://application@172.18.0.4:2552] - Started up successfully
2020-08-12 21:33:00,527 [INFO] from akka.cluster.Cluster(akka://application) in application-akka.actor.default-dispatcher-2 - Cluster Node [akka.tcp://application@172.18.0.4:2552] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/cluster-usage.html#joining-to-seed-nodes
2020-08-12 21:33:05,443 [INFO] from com.sksamuel.elastic4s.http.ElasticClient$ in main - Creating HTTP client on http://172.18.0.2:9200
2020-08-12 21:33:09,031 [INFO] from connectors.cortex.services.CortexClient in main - new Cortex(cortex1, http://172.18.0.3:9001) authentication: no
2020-08-12 21:33:09,048 [INFO] from connectors.cortex.services.CortexAnalyzerSrv in main - Search for unfinished job ...
2020-08-12 21:33:11,786 [WARN] from org.elastic4play.database.SearchWithScroll in application-akka.actor.default-dispatcher-16 - Search error
com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: java.net.NoRouteToHostException: No route to host
	at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:63)
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:850)
	at org.elasticsearch.client.RestClient$1.retryIfPossible(RestClient.java:588)
	at org.elasticsearch.client.RestClient$1.failed(RestClient.java:567)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:335)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:378)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalPoolEntryCallback.failed(PoolingNHttpClientConnectionManager.java:504)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
	at org.apache.http.nio.pool.RouteSpecificPool.failed(RouteSpecificPool.java:163)
	at org.apache.http.nio.pool.AbstractNIOConnPool.requestFailed(AbstractNIOConnPool.java:542)
	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.failed(AbstractNIOConnPool.java:817)
	at org.apache.http.impl.nio.reactor.SessionRequestImpl.failed(SessionRequestImpl.java:160)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:173)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171)
	... 5 common frames omitted
2020-08-12 21:33:13,250 [INFO] from play.api.Play in main - Application started (Prod)
2020-08-12 21:33:14,334 [INFO] from play.core.server.AkkaHttpServer in main - Enabling HTTP/2 on Akka HTTP server...
2020-08-12 21:33:14,335 [INFO] from play.core.server.AkkaHttpServer in main - Listening for HTTP on /0.0.0.0:9000
2020-08-12 21:34:20,851 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-18 - GET /api/user/current returned 500
com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: java.net.ConnectException
	at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:63)
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:850)
	at org.elasticsearch.client.RestClient$1.retryIfPossible(RestClient.java:588)
	at org.elasticsearch.client.RestClient$1.failed(RestClient.java:567)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:335)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:378)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalPoolEntryCallback.failed(PoolingNHttpClientConnectionManager.java:504)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
	at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168)
	at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:561)
	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:822)
	at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:183)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:210)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:155)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: null
	... 10 common frames omitted

## ElasticSearch application log
[2020-08-12T22:12:59.439+0000][1][gc,heap] Heap region size: 1M
[2020-08-12T22:12:59.439+0000][1][gc,heap,coops] Heap address: 0x00000000c0000000, size: 1024 MB, Compressed Oops mode: 32-bit
[2020-08-12T22:12:59.639+0000][1][gc           ] Using G1
[2020-08-12T22:12:59.640+0000][1][gc,cds       ] Mark closed archive regions in map: [0x00000000fff00000, 0x00000000fff7eff8]
[2020-08-12T22:12:59.640+0000][1][gc,cds       ] Mark open archive regions in map: [0x00000000ffe00000, 0x00000000ffe52ff8]
[2020-08-12T22:13:00.542+0000][1][gc           ] Periodic GC disabled
[2020-08-12T22:13:01.612+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1961848754 ns, Reaching safepoint: 108900 ns, At safepoint: 3100 ns, Total: 112000 ns
[2020-08-12T22:13:03.670+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 2000470906 ns, Reaching safepoint: 58443227 ns, At safepoint: 5700 ns, Total: 58448927 ns
[2020-08-12T22:13:05.211+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1540243680 ns, Reaching safepoint: 90600 ns, At safepoint: 2400 ns, Total: 93000 ns
[2020-08-12T22:13:06.213+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1002475650 ns, Reaching safepoint: 178700 ns, At safepoint: 4600 ns, Total: 183300 ns
[2020-08-12T22:13:07.214+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1000294953 ns, Reaching safepoint: 87700 ns, At safepoint: 2300 ns, Total: 90000 ns
[2020-08-12T22:13:08.214+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1000250553 ns, Reaching safepoint: 116000 ns, At safepoint: 5100 ns, Total: 121100 ns
[2020-08-12T22:13:09.242+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1027992118 ns, Reaching safepoint: 75200 ns, At safepoint: 2400 ns, Total: 77600 ns
[2020-08-12T22:13:10.248+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1006064646 ns, Reaching safepoint: 78899 ns, At safepoint: 2800 ns, Total: 81699 ns
[2020-08-12T22:13:11.249+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1000253753 ns, Reaching safepoint: 78800 ns, At safepoint: 2800 ns, Total: 81600 ns
[2020-08-12T22:13:12.416+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1167477445 ns, Reaching safepoint: 57700 ns, At safepoint: 2200 ns, Total: 59900 ns
[2020-08-12T22:13:13.430+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1003987348 ns, Reaching safepoint: 9426788 ns, At safepoint: 5100 ns, Total: 9431888 ns
[2020-08-12T22:13:14.538+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1108298219 ns, Reaching safepoint: 53100 ns, At safepoint: 2200 ns, Total: 55300 ns
[2020-08-12T22:13:15.027+0000][1][gc,start     ] GC(0) Pause Young (Normal) (G1 Evacuation Pause)
[2020-08-12T22:13:15.027+0000][1][gc,task      ] GC(0) Using 1 workers of 1 for evacuation
[2020-08-12T22:13:15.027+0000][1][gc,age       ] GC(0) Desired survivor size 3670016 bytes, new threshold 15 (max threshold 15)
[2020-08-12T22:13:15.044+0000][1][gc,age       ] GC(0) Age table with threshold 15 (max threshold 15)
[2020-08-12T22:13:15.044+0000][1][gc,age       ] GC(0) - age   1:    5161376 bytes,    5161376 total
[2020-08-12T22:13:15.046+0000][1][gc,phases    ] GC(0)   Pre Evacuate Collection Set: 0.2ms
[2020-08-12T22:13:15.046+0000][1][gc,phases    ] GC(0)   Merge Heap Roots: 0.1ms
[2020-08-12T22:13:15.046+0000][1][gc,phases    ] GC(0)   Evacuate Collection Set: 16.6ms
[2020-08-12T22:13:15.046+0000][1][gc,phases    ] GC(0)   Post Evacuate Collection Set: 0.5ms
[2020-08-12T22:13:15.046+0000][1][gc,phases    ] GC(0)   Other: 1.7ms
[2020-08-12T22:13:15.046+0000][1][gc,heap      ] GC(0) Eden regions: 51->0(46)
[2020-08-12T22:13:15.046+0000][1][gc,heap      ] GC(0) Survivor regions: 0->5(7)
[2020-08-12T22:13:15.046+0000][1][gc,heap      ] GC(0) Old regions: 0->0
[2020-08-12T22:13:15.046+0000][1][gc,heap      ] GC(0) Archive regions: 2->2
[2020-08-12T22:13:15.046+0000][1][gc,heap      ] GC(0) Humongous regions: 1->1
[2020-08-12T22:13:15.046+0000][1][gc,metaspace ] GC(0) Metaspace: 12235K(12928K)->12235K(12928K) NonClass: 10734K(11264K)->10734K(11264K) Class: 1501K(1664K)->1501K(1664K)
[2020-08-12T22:13:15.046+0000][1][gc           ] GC(0) Pause Young (Normal) (G1 Evacuation Pause) 52M->6M(1024M) 19.274ms
[2020-08-12T22:13:15.046+0000][1][gc,cpu       ] GC(0) User=0.01s Sys=0.00s Real=0.02s
[2020-08-12T22:13:15.046+0000][1][safepoint    ] Safepoint "G1CollectForAllocation", Time since last: 488392691 ns, Reaching safepoint: 69900 ns, At safepoint: 19348675 ns, Total: 19418575 ns
[2020-08-12T22:13:16.130+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1084367249 ns, Reaching safepoint: 123299 ns, At safepoint: 2900 ns, Total: 126199 ns
[2020-08-12T22:13:17.216+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1085640547 ns, Reaching safepoint: 97000 ns, At safepoint: 2400 ns, Total: 99400 ns
[2020-08-12T22:13:17.796+0000][1][gc,start     ] GC(1) Pause Young (Normal) (G1 Evacuation Pause)
[2020-08-12T22:13:17.796+0000][1][gc,task      ] GC(1) Using 1 workers of 1 for evacuation
[2020-08-12T22:13:17.796+0000][1][gc,age       ] GC(1) Desired survivor size 3670016 bytes, new threshold 1 (max threshold 15)
[2020-08-12T22:13:17.810+0000][1][gc,age       ] GC(1) Age table with threshold 1 (max threshold 15)
[2020-08-12T22:13:17.810+0000][1][gc,age       ] GC(1) - age   1:    1577968 bytes,    1577968 total
[2020-08-12T22:13:17.810+0000][1][gc,phases    ] GC(1)   Pre Evacuate Collection Set: 0.2ms
[2020-08-12T22:13:17.810+0000][1][gc,phases    ] GC(1)   Merge Heap Roots: 0.0ms
[2020-08-12T22:13:17.810+0000][1][gc,phases    ] GC(1)   Evacuate Collection Set: 12.9ms
[2020-08-12T22:13:17.810+0000][1][gc,phases    ] GC(1)   Post Evacuate Collection Set: 0.4ms
[2020-08-12T22:13:17.810+0000][1][gc,phases    ] GC(1)   Other: 0.2ms
[2020-08-12T22:13:17.810+0000][1][gc,heap      ] GC(1) Eden regions: 46->0(49)
[2020-08-12T22:13:17.810+0000][1][gc,heap      ] GC(1) Survivor regions: 5->2(7)
[2020-08-12T22:13:17.810+0000][1][gc,heap      ] GC(1) Old regions: 0->5
[2020-08-12T22:13:17.810+0000][1][gc,heap      ] GC(1) Archive regions: 2->2
[2020-08-12T22:13:17.810+0000][1][gc,heap      ] GC(1) Humongous regions: 1->1
[2020-08-12T22:13:17.810+0000][1][gc,metaspace ] GC(1) Metaspace: 14876K(15616K)->14876K(15616K) NonClass: 13042K(13568K)->13042K(13568K) Class: 1833K(2048K)->1833K(2048K)
[2020-08-12T22:13:17.810+0000][1][gc           ] GC(1) Pause Young (Normal) (G1 Evacuation Pause) 52M->7M(1024M) 13.892ms
[2020-08-12T22:13:17.810+0000][1][gc,cpu       ] GC(1) User=0.01s Sys=0.00s Real=0.01s
[2020-08-12T22:13:17.810+0000][1][safepoint    ] Safepoint "G1CollectForAllocation", Time since last: 580033777 ns, Reaching safepoint: 79000 ns, At safepoint: 13960282 ns, Total: 14039282 ns
[2020-08-12T22:13:17.839+0000][1][safepoint    ] Safepoint "BulkRevokeBias", Time since last: 28895764 ns, Reaching safepoint: 163700 ns, At safepoint: 52300 ns, Total: 216000 ns
[2020-08-12T22:13:18.035+0000][1][safepoint    ] Safepoint "BulkRevokeBias", Time since last: 195214956 ns, Reaching safepoint: 43800 ns, At safepoint: 57300 ns, Total: 101100 ns
[2020-08-12T22:13:18.035+0000][1][safepoint    ] Safepoint "BulkRevokeBias", Time since last: 90100 ns, Reaching safepoint: 20800 ns, At safepoint: 34600 ns, Total: 55400 ns
[2020-08-12T22:13:19.048+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1011578039 ns, Reaching safepoint: 1964598 ns, At safepoint: 3000 ns, Total: 1967598 ns
[2020-08-12T22:13:19.050+0000][1][gc,start     ] GC(2) Pause Young (Normal) (G1 Evacuation Pause)
[2020-08-12T22:13:19.050+0000][1][gc,task      ] GC(2) Using 1 workers of 1 for evacuation
[2020-08-12T22:13:19.050+0000][1][gc,age       ] GC(2) Desired survivor size 3670016 bytes, new threshold 15 (max threshold 15)
[2020-08-12T22:13:19.062+0000][1][gc,age       ] GC(2) Age table with threshold 15 (max threshold 15)
[2020-08-12T22:13:19.062+0000][1][gc,age       ] GC(2) - age   1:     316208 bytes,     316208 total
[2020-08-12T22:13:19.062+0000][1][gc,age       ] GC(2) - age   2:    1212936 bytes,    1529144 total
[2020-08-12T22:13:19.062+0000][1][gc,phases    ] GC(2)   Pre Evacuate Collection Set: 0.2ms
[2020-08-12T22:13:19.062+0000][1][gc,phases    ] GC(2)   Merge Heap Roots: 0.0ms
[2020-08-12T22:13:19.062+0000][1][gc,phases    ] GC(2)   Evacuate Collection Set: 12.0ms
[2020-08-12T22:13:19.062+0000][1][gc,phases    ] GC(2)   Post Evacuate Collection Set: 0.3ms
[2020-08-12T22:13:19.062+0000][1][gc,phases    ] GC(2)   Other: 0.2ms
[2020-08-12T22:13:19.062+0000][1][gc,heap      ] GC(2) Eden regions: 49->0(49)
[2020-08-12T22:13:19.062+0000][1][gc,heap      ] GC(2) Survivor regions: 2->2(7)
[2020-08-12T22:13:19.062+0000][1][gc,heap      ] GC(2) Old regions: 5->5
[2020-08-12T22:13:19.062+0000][1][gc,heap      ] GC(2) Archive regions: 2->2
[2020-08-12T22:13:19.062+0000][1][gc,heap      ] GC(2) Humongous regions: 1->1
[2020-08-12T22:13:19.062+0000][1][gc,metaspace ] GC(2) Metaspace: 14988K(15616K)->14988K(15616K) NonClass: 13150K(13568K)->13150K(13568K) Class: 1838K(2048K)->1838K(2048K)
[2020-08-12T22:13:19.062+0000][1][gc           ] GC(2) Pause Young (Normal) (G1 Evacuation Pause) 56M->7M(1024M) 12.779ms
[2020-08-12T22:13:19.062+0000][1][gc,cpu       ] GC(2) User=0.00s Sys=0.00s Real=0.02s
[2020-08-12T22:13:19.062+0000][1][safepoint    ] Safepoint "G1CollectForAllocation", Time since last: 1272598 ns, Reaching safepoint: 24700 ns, At safepoint: 12840284 ns, Total: 12864984 ns
[2020-08-12T22:13:20.066+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1003835648 ns, Reaching safepoint: 86000 ns, At safepoint: 3300 ns, Total: 89300 ns
[2020-08-12T22:13:21.072+0000][1][safepoint    ] Safepoint "Cleanup", Time since last: 1005902846 ns, Reaching safepoint: 83000 ns, At safepoint: 2500 ns, Total: 85500 ns
... clip ...
59783K(62720K)->59783K(62720K) Class: 9340K(11392K)->9340K(11392K)
[2020-08-13T14:48:04.674+0000][1][gc           ] GC(52) Pause Young (Normal) (G1 Evacuation Pause) 677M->64M(1024M) 3.658ms
[2020-08-13T14:48:04.674+0000][1][gc,cpu       ] GC(52) User=0.01s Sys=0.00s Real=0.01s
[2020-08-13T14:48:04.674+0000][1][safepoint    ] Safepoint "G1CollectForAllocation", Time since last: 175448824856 ns, Reaching safepoint: 141100 ns, At safepoint: 3757298 ns, Total: 3898398 ns

**Comment by SergeyDrachuk** [comment]
In the Centos 8 the solution is 
firewall-cmd --permanent --zone=trusted --add-source=172.17.0.0/16
firewall-cmd --reload
