### ISSUE TITLE
[Bug] HTTP chunk size exceeds the configured limit of 1048576 bytes

### ISSUE THREAD

**Issue by Jav3k** [TheHive-Project/TheHive#1484]
### Request Type

Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOs 
| OS version (client)       | 7
| TheHive version / git hash   | 3.4.2 (in web 3.4.2-1)
| Package Type              | RPM

also TheHive 3.4.0 Training VM

### Problem Description
Hello. I'm using TheHive API to create alert -> case -> task -> log.
My log is .pdf file attachment (sending to API as Buffer). But the file size is always different. if the attachment size is more than 1 MB, then I get 500 error (logs bellow)

How to increase http chunk size?

### Possible Solutions
Sorry. I don't know scala and akka library. But i think it can be fixed by increasing `akka.http.server.parsing.max-chunk-size`, `akka.http.client.parsing.max-chunk-size` or `akka.http.host-connection-pool.client.parsing.max-chunk-size` to 10M in akka config for example

### Complementary information
TheHive 3.4.2 logs:
```
2020-08-18 16:00:46,391 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-18 - POST /api/case/task/AXQBOisjmXmv16N3ZheJ/log returned 500
akka.http.scaladsl.model.EntityStreamException: HTTP chunk size exceeds the configured limit of 1048576 bytes
        at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:330)
        at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:328)
        at akka.stream.impl.fusing.Collect$$anon$6.$anonfun$wrappedPf$1(Ops.scala:217)
        at akka.stream.impl.fusing.SupervisedGraphStageLogic.withSupervision(Ops.scala:178)
        at akka.stream.impl.fusing.Collect$$anon$6.onPush(Ops.scala:219)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:515)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:478)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:374)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:474)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:730)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:745)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:655)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
        at akka.actor.ActorCell.invoke(ActorCell.scala:561)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by To-om** [comment]
Have you tried to set `akka.http.server.parsing.max-chunk-size: 10M` in application.conf ?

**Comment by Jav3k** [comment]
> Have you tried to set `akka.http.server.parsing.max-chunk-size: 10M` in application.conf ?

Yes. I set all those commands:
```
akka.http.server.parsing.max-chunk-size = 100M
akka.http.client.parsing.max-chunk-size = 100M
akka.http.host-connection-pool.client.parsing.max-chunk-size = 100M

play.server.akka.http.server.parsing.max-chunk-size = 100M
play.server.akka.http.client.parsing.max-chunk-size = 100M
play.server.akka.http.host-connection-pool.client.parsing.max-chunk-size = 100M

play.server.akka.max-content-length = 102400K
parsers.MultipartFormData.maxLength = 102400K
parsers.formUrlEncoded.maxLength = 102400K
akka.http.server.parsing.max-content-length = 102400K
```

**Comment by Jav3k** [comment]
```
akka.http.parsing.max-chunk-size = 16m
```

I think it solved my problem on TheHive 3 and TheHive 4. 
I will close issue
