### ISSUE TITLE
[Bug] Trying to run TheHive inside Docker But Elasticsearch is failing 

### ISSUE THREAD

**Issue by BrunoMCBraga** [TheHive-Project/TheHive#1485]
Basically i am trying to setup TheHive inside Docker using: https://hub.docker.com/r/thehiveproject/thehive

However, i am getting:

```
thehive_1        | [info] c.c.s.CortexClient - new Cortex(cortex1, http://172.18.0.3:) authentication: no
thehive_1        | [info] c.c.s.CortexAnalyzerSrv - Search for unfinished job ...
cortex_1         | [info] play.api.Play - Application started (Prod)
cortex_1         | [info] p.c.s.AkkaHttpServer - Enabling HTTP/2 on Akka HTTP server...
cortex_1         | [info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:9001
thehive_1        | [warn] o.e.d.SearchWithScroll - Search error
thehive_1        | com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: java.net.ConnectException
thehive_1        | 	at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:63)
thehive_1        | 	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:850)
thehive_1        | 	at org.elasticsearch.client.RestClient$1.retryIfPossible(RestClient.java:588)
thehive_1        | 	at org.elasticsearch.client.RestClient$1.failed(RestClient.java:567)
thehive_1        | 	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
thehive_1        | 	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
thehive_1        | 	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:335)
thehive_1        | 	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62)
thehive_1        | 	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:378)
thehive_1        | 	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
thehive_1        | Caused by: java.net.ConnectException: null
thehive_1        | 	at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168)
thehive_1        | 	at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:561)
thehive_1        | 	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:822)
thehive_1        | 	at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:183)
thehive_1        | 	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:210)
thehive_1        | 	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:155)
thehive_1        | 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
thehive_1        | 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
thehive_1        | 	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
thehive_1        | 	at java.lang.Thread.run(Thread.java:748)
thehive_1        | [info] play.api.Play - Application started (Prod)
thehive_1        | [info] p.c.s.AkkaHttpServer - Enabling HTTP/2 on Akka HTTP server...
thehive_1        | [info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:9000
thehive_1        | [warn] o.e.d.SearchWithScroll - Search error
thehive_1        | com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: java.net.ConnectException
thehive_1        | 	at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:63)
thehive_1        | 	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:850)
thehive_1        | 	at org.elasticsearch.client.RestClient$1.retryIfPossible(RestClient.java:588)
thehive_1        | 	at org.elasticsearch.client.RestClient$1.failed(RestClient.java:567)
thehive_1        | 	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
thehive_1        | 	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
thehive_1        | 	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:335)
thehive_1        | 	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62)
thehive_1        | 	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:378)
thehive_1        | 	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
thehive_1        | Caused by: java.net.ConnectException: null
thehive_1        | 	at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168)
thehive_1        | 	at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:561)
thehive_1        | 	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:822)
thehive_1        | 	at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:183)
thehive_1        | 	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:210)
thehive_1        | 	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:155)
thehive_1        | 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
thehive_1        | 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
thehive_1        | 	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
thehive_1        | 	at java.lang.Thread.run(Thread.java:748)
thehive_1        | [info] o.e.ErrorHandler - GET /api/user/current returned 500
thehive_1        | com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: java.net.ConnectException
thehive_1        | 	at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:63)
thehive_1        | 	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:850)
thehive_1        | 	at org.elasticsearch.client.RestClient$1.retryIfPossible(RestClient.java:588)
thehive_1        | 	at org.elasticsearch.client.RestClient$1.failed(RestClient.java:567)
thehive_1        | 	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
thehive_1        | 	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
thehive_1        | 	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:335)
thehive_1        | 	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62)
thehive_1        | 	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:378)
thehive_1        | 	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
thehive_1        | Caused by: java.net.ConnectException: null
thehive_1        | 	at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168)
thehive_1        | 	at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:561)
thehive_1        | 	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:822)
thehive_1        | 	at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:183)
thehive_1        | 	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:210)
thehive_1        | 	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:155)
thehive_1        | 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
thehive_1        | 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
thehive_1        | 	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
thehive_1        | 	at java.lang.Thread.run(Thread.java:748)
```

When i list docker containers running, ElasticSearch is missing. I am using the following yml:

```
version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=hive
      - script.inline=true
      - thread_pool.index.queue_size=100000
      - thread_pool.search.queue_size=100000
      - thread_pool.bulk.queue_size=100000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      -[SOME_PATH]/es-db:/usr/share/elasticsearch/data
  cortex:
    image: thehiveproject/cortex:latest
    ports:
      - "0.0.0.0:9001:9001"
  thehive:
    image: thehiveproject/thehive:latest
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
```

Any idea how can i troubleshoot this? Thanks

### Problem Description
ES fails to initialize properly when used with cortex and thehive inside Docker. TheHive fails then to find ES.

**Comment by PoesRaven** [comment]
This happened to me as well. If you try to start the container for elasticsearch alone you will see that the vm.max_map_count value set in the OS is actually too low for elastic search. if you enter the following in a terminal:
`
sudo sysctl -w vm.max_map_count=262144
`
you should be good to go!

**Comment by BrunoMCBraga** [comment]
@PoesRaven Thanks for the help. I have OSX. 

If i run the command you provided as it is, i get: sysctl: unknown oid 'vm.max_map_count'. 

I was checking: https://stackoverflow.com/questions/41192680/update-max-map-count-for-elasticsearch-docker-container-mac-host and did the following:
- find ~/Library/Containers/com.docker.docker/Data/ -name 'tty'. Take the result and plug it below.
- On terminal: screen [FIND_RESULT]
- Press enter on blank screen
- sysctl -w vm.max_map_count=262144

I am unable and it seems when i run screen...characters are all messed up and even when i managed to update the variable it failed. Any idea how to sort this out?

**Comment by nadouani** [comment]
Is this still an issue? Or is it solved?

**Comment by desnij** [comment]
FWIW: This is actually a docker macos issue.
NB:   Each time one restarts the docker desktop vm the settings are lost ( apart from the gui @BrunoMCBraga has posted above) .  A cursory search I havent found any way to make this permanent, however I am sure there is a way.

I, personally, think this can be closed, but I could be wrong. ;) 
Merci

**Comment by BrunoMCBraga** [comment]
Sorted guys thank you
