### ISSUE TITLE
[Bug] POST /api/connector/cortex/analyzer/template/_search returned 404

### ISSUE THREAD

**Issue by smclinden** [TheHive-Project/TheHive#1495]
### Request Type

Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | ubuntu 18.04
| OS version (client)       | OS X Catalina
| TheHive version / git hash   | 329a8ae7fbce54768d57b9e4de5d748eae826195
| Package Type              | From source
| Browser type & version    | Chrome

### Problem Description
Attempting to import templates causes a 404 error

### Steps to Reproduce
1. Start TheHive
2. Login
3. Navigate to Template Management and select the template zip file.

### Complementary information
org.thp.scalligraph.NotFoundError: /api/connector/cortex/analyzer/template/_search
	at org.thp.scalligraph.ScalligraphRouter$$anonfun$2.$anonfun$applyOrElse$4(ScalligraphRouter.scala:102)
	at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.$anonfun$invokeBlock$2(SessionAuthSrv.scala:84)
	at scala.Option.fold(Option.scala:251)
	at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.invokeBlock(SessionAuthSrv.scala:82)
	at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.invokeBlock(SessionAuthSrv.scala:79)
	at org.thp.scalligraph.ScalligraphRouter$$anonfun$2.$anonfun$applyOrElse$3(ScalligraphRouter.scala:102)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:441)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:439)
	at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:379)
	at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:167)
	at scala.util.Try$.apply(Try.scala:213)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:167)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:199)
	at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:413)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$2(ContextPropagatingDisptacher.scala:57)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.thp.scalligraph.DiagnosticContext$.$anonfun$withDiagnosticContext$2(ContextPropagatingDisptacher.scala:92)
	at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:107)
	at org.thp.scalligraph.DiagnosticContext$.withDiagnosticContext(ContextPropagatingDisptacher.scala:90)
	at org.thp.scalligraph.DiagnosticContext$$anon$2.withContext(ContextPropagatingDisptacher.scala:75)
	at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$1(ContextPropagatingDisptacher.scala:57)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by smclinden** [comment]
The error appears to be here:

        "undefined" != typeof XMLHttpRequest && XMLHttpRequest.prototype && XMLHttpRequest.prototype.send && (XMLHttpRequest.prototype.send = e(XMLHttpRequest.prototype.send, (o = XMLHttpRequest.prototype.send,
        function(t) {
            var e = this
              , n = s(t);
            return n && e.addEventListener("loadend", function() {
                c({
                    requestID: n,
                    statusCode: e.status
                })
            }),
            o.apply(e, arguments)

**Comment by To-om** [comment]
Have you enabled cortex connector ? (Add `play.modules.enabled += org.thp.thehive.connector.cortex.CortexModule` in application.conf) ?

**Comment by smclinden** [comment]
No. I haven't configured Cortex, yet. I assumed that you could load the templates whether Cortex was enabled or not.

Is this incorrect?

**Comment by To-om** [comment]
Analyzer template has sense only if you have analyzers, and analyzers are related to Cortex. You cannot manage templates without Cortex connector. You can also enable connector but without any Cortex:
```
play.modules.enabled += org.thp.thehive.connector.cortex.CortexModule
cortex {
  servers = []
}
```

**Comment by smclinden** [comment]
I enabled Cortex and now the error is TemplateCtrl: [Attribute name is missing]

**Comment by To-om** [comment]
TemplateCtrl is related to case template. Your zip file contains analyzer template. See this [comment](https://github.com/TheHive-Project/TheHive/issues/1520#issuecomment-690048484)
