### ISSUE TITLE
No configuration setting found for key 'search.uri

### ISSUE THREAD

**Issue by farhadarhad** [TheHive-Project/TheHive#1542]
Reflections took 205 ms to scan 4 urls, producing 119 keys and 1312 values
[^[[37minfo^[[0m] module - Loading model class models.AlertModel
[^[[37minfo^[[0m] module - Loading model class models.CaseModel
[^[[37minfo^[[0m] module - Loading model class org.elastic4play.services.AttachmentModel
[^[[37minfo^[[0m] module - Loading model class models.UserModel
[^[[37minfo^[[0m] module - Loading model class models.ArtifactModel
[^[[37minfo^[[0m] module - Loading model class models.DashboardModel
[^[[37minfo^[[0m] module - Loading model class models.TaskModel
[^[[37minfo^[[0m] module - Loading model class connectors.cortex.models.ActionModel
[^[[37minfo^[[0m] module - Loading model class models.CaseTemplateModel
[^[[37minfo^[[0m] module - Loading model class models.LogModel
[^[[37minfo^[[0m] module - Loading model class org.elastic4play.services.DBListModel
[^[[37minfo^[[0m] module - Loading model class connectors.cortex.models.JobModel
[^[[37minfo^[[0m] module - Loading model class connectors.cortex.models.ReportTemplateModel
[^[[37minfo^[[0m] module - Loading model class models.AuditModel
[^[[37minfo^[[0m] a.e.s.Slf4jLogger - Slf4jLogger started
[^[[37minfo^[[0m] a.r.Remoting - Starting remoting
[^[[37minfo^[[0m] a.r.Remoting - Remoting started; listening on addresses :[akka.tcp://application@10.128.0.14:2552]
[^[[37minfo^[[0m] a.r.Remoting - Remoting now listens on addresses: [akka.tcp://application@10.128.0.14:2552]
[^[[37minfo^[[0m] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@10.128.0.14:2552] - Starting up, Akka version [2.5.21] ...
[^[[37minfo^[[0m] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@10.128.0.14:2552] - Registered cluster JMX MBean [akka:type=Cluster]
[^[[37minfo^[[0m] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@10.128.0.14:2552] - Started up successfully
[^[[37minfo^[[0m] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@10.128.0.14:2552] - No seed-nodes configured, manual cluster join required, see https$
[^[[31merror^[[0m] a.a.OneForOneStrategy - Unable to provision, see the following errors:
1) Error injecting constructor, com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'search.uri'
  at org.elastic4play.database.DBConfiguration.<init>(DBConfiguration.scala:41)
  at org.elastic4play.database.DBConfiguration.class(DBConfiguration.scala:40)
  while locating org.elastic4play.database.DBConfiguration
    for the 1st parameter of org.elastic4play.services.AuxSrv.<init>(AuxSrv.scala:17)
  at org.elastic4play.services.AuxSrv.class(AuxSrv.scala:17)
  while locating org.elastic4play.services.AuxSrv
    for the 2nd parameter of services.LocalStreamActor.<init>(StreamSrv.scala:40)
  while locating services.LocalStreamActor
1 error
akka.actor.ActorInitializationException: akka://application/user/localStreamActor: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:193)
        at akka.actor.ActorCell.create(ActorCell.scala:673)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:527)

    at akka.actor.ActorCell.systemInvoke(ActorCell.scala:549)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'search.uri'
  at org.elastic4play.database.DBConfiguration.<init>(DBConfiguration.scala:41)
  at org.elastic4play.database.DBConfiguration.class(DBConfiguration.scala:40)
  while locating org.elastic4play.database.DBConfiguration
    for the 1st parameter of org.elastic4play.services.AuxSrv.<init>(AuxSrv.scala:17)
  at org.elastic4play.services.AuxSrv.class(AuxSrv.scala:17)
  while locating org.elastic4play.services.AuxSrv
    for the 2nd parameter of services.LocalStreamActor.<init>(StreamSrv.scala:40)
  while locating services.LocalStreamActor

1 error
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:442)
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:437)
        at play.api.inject.ContextClassLoaderInjector.$anonfun$instanceOf$2(Injector.scala:118)
        at play.api.inject.ContextClassLoaderInjector.withContext(Injector.scala:127)
        at play.api.inject.ContextClassLoaderInjector.instanceOf(Injector.scala:118)
        at play.api.libs.concurrent.ActorRefProvider.$anonfun$get$1(Akka.scala:269)
        at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'search.uri'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
        at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
        at play.api.ConfigLoader$.$anonfun$stringLoader$2(Configuration.scala:1056)
        at play.api.ConfigLoader$$anon$3.load(Configuration.scala:1051)
        at play.api.Configuration.get(Configuration.scala:227)

1) Error injecting constructor, com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'search.uri'
  at org.elastic4play.database.DBConfiguration.<init>(DBConfiguration.scala:41)
  at org.elastic4play.database.DBConfiguration.class(DBConfiguration.scala:40)
  while locating org.elastic4play.database.DBConfiguration
    for the 1st parameter of org.elastic4play.database.DBGet.<init>(DBGet.scala:14)
  at org.elastic4play.database.DBGet.class(DBGet.scala:14)
  while locating org.elastic4play.database.DBGet
    for the 1st parameter of org.elastic4play.services.GetSrv.<init>(GetSrv.scala:11)
  at org.elastic4play.services.GetSrv.class(GetSrv.scala:11)
  while locating org.elastic4play.services.GetSrv
    for the 1st parameter of org.elastic4play.services.DBLists.<init>(DBList.scala:65)
  at org.elastic4play.services.DBLists.class(DBList.scala:64)
  while locating org.elastic4play.services.DBLists
    for the 1st parameter of models.AlertModel.<init>(Alert.scala:84)
  at models.AlertModel.class(Alert.scala:84)
  while locating models.AlertModel
  while locating services.AuditedModel annotated with @com.google.inject.internal.Element(setName=,uniqueId=3, type=MULTIBINDER, keyType=)
  while locating java.util.Set<services.AuditedModel>
  at global.TheHive.configure(TheHive.scala:34) (via modules: com.google.inject.util.Modules$OverrideModule -> global.TheHive -> net.codingwell.scalaguice.ScalaMultibinder$Re$
  while locating scala.collection.immutable.Set<services.AuditedModel>
    for the 2nd parameter of models.AuditModel.<init>(Audit.scala:59)
  at models.AuditModel.class(Audit.scala:47)
  while locating models.AuditModel
    for the 1st parameter of services.AuditActor.<init>(AuditSrv.scala:101)
  at services.AuditActor.class(AuditSrv.scala:101)
  while locating services.AuditActor

1 error
akka.actor.ActorInitializationException: akka://application/user/AuditActor: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:193)
        at akka.actor.ActorCell.create(ActorCell.scala:673)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:527)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:549)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)

      at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'search.uri'
  at org.elastic4play.database.DBConfiguration.<init>(DBConfiguration.scala:41)
  at org.elastic4play.database.DBConfiguration.class(DBConfiguration.scala:40)
  while locating org.elastic4play.database.DBConfiguration
    for the 1st parameter of org.elastic4play.database.DBGet.<init>(DBGet.scala:14)
  at org.elastic4play.database.DBGet.class(DBGet.scala:14)
  while locating org.elastic4play.database.DBGet
    for the 1st parameter of org.elastic4play.services.GetSrv.<init>(GetSrv.scala:11)
  at org.elastic4play.services.GetSrv.class(GetSrv.scala:11)
  while locating org.elastic4play.services.GetSrv
    for the 1st parameter of org.elastic4play.services.DBLists.<init>(DBList.scala:65)
  at org.elastic4play.services.DBLists.class(DBList.scala:64)
  while locating org.elastic4play.services.DBLists
    for the 1st parameter of models.AlertModel.<init>(Alert.scala:84)
  at models.AlertModel.class(Alert.scala:84)
  while locating models.AlertModel
  while locating services.AuditedModel annotated with @com.google.inject.internal.Element(setName=,uniqueId=3, type=MULTIBINDER, keyType=)
  while locating java.util.Set<services.AuditedModel>
  at global.TheHive.configure(TheHive.scala:34) (via modules: com.google.inject.util.Modules$OverrideModule -> global.TheHive -> net.codingwell.scalaguice.ScalaMultibinder$Re$
  while locating scala.collection.immutable.Set<services.AuditedModel>
    for the 2nd parameter of models.AuditModel.<init>(Audit.scala:59)
  at models.AuditModel.class(Audit.scala:47)
  while locating models.AuditModel
    for the 1st parameter of services.AuditActor.<init>(AuditSrv.scala:101)
  at services.AuditActor.class(AuditSrv.scala:101)
  while locating services.AuditActor

1 error
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:442)
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:437)
        at play.api.inject.ContextClassLoaderInjector.$anonfun$instanceOf$2(Injector.scala:118)

**Comment by rriclet** [comment]
Hello, please fill the issue template so we can have your work environment, problem description, steps to reproduce...
Thanks.

**Comment by stefancastille** [comment]
any news on how this was resolved? I have the exact same issue on a new cluster install on ubunt 24.04.
