### ISSUE TITLE
[Bug] Fails to start with 'Cannot access element because its enclosing transaction is closed and unbound'

### ISSUE THREAD

**Issue by jakubgs** [TheHive-Project/TheHive#1575]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 20.04
| TheHive version / git hash   | 4.0.0
| Package Type              | Binary

### Problem Description
Service exits with `255` with error:
```
[ERROR] from akka.actor.OneForOneStrategy in application-akka.actor.default-dispatcher-11 [|] Cannot access element because its enclosing transaction is closed and unbound
akka.actor.ActorInitializationException: akka://application/user/integrityCheckSingletonManager/singleton: exception during creation
```

### Steps to Reproduce
My config looks like this:
```
# Include Play secret key
include "/etc/thehive/secret.conf"

# Cassandra Database configuration
db.janusgraph {
  storage {
    backend: cql
    username: "thehive"
    password: "secret-password"
    hostname: [
        "10.2.1.1:9042", # slave-01
        "10.2.1.2:9042", # slave-02
        "10.2.1.3:9042", # slave-03
    ]
    cql {
      cluster-name: "thp"
      keyspace: "thehive"
    }
  }
}

# Attachment storage configuration
storage {
  provider: localfs
  localfs.directory: "/data/thehive/data"
}
```
When I try to run it using the [provided service definion](https://github.com/TheHive-Project/TheHive/blob/4.0.0/package/thehive.service) it fails to start with `255`:
```
[ERROR] from akka.actor.OneForOneStrategy in application-akka.actor.default-dispatcher-11 [|] Cannot access element because its enclosing transaction is closed and unbound
akka.actor.ActorInitializationException: akka://application/user/integrityCheckSingletonManager/singleton: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:196)
	at akka.actor.ActorCell.create(ActorCell.scala:659)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:511)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:533)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.IllegalStateException: Cannot access element because its enclosing transaction is closed and unbound
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.getNextTx(StandardJanusGraphTx.java:305)
	at org.janusgraph.graphdb.vertices.AbstractVertex.it(AbstractVertex.java:53)
	at org.janusgraph.graphdb.vertices.AbstractVertex.it(AbstractVertex.java:37)
	at org.janusgraph.graphdb.internal.AbstractElement.isRemoved(AbstractElement.java:141)
	at org.janusgraph.graphdb.vertices.AbstractVertex.verifyAccess(AbstractVertex.java:89)
	at org.janusgraph.graphdb.vertices.AbstractVertex.query(AbstractVertex.java:137)
	at org.janusgraph.graphdb.vertices.AbstractVertex.query(AbstractVertex.java:37)
	at org.janusgraph.graphdb.util.ElementHelper.getValues(ElementHelper.java:41)
	at org.janusgraph.graphdb.query.condition.PredicateCondition.evaluate(PredicateCondition.java:68)
	at org.janusgraph.graphdb.query.condition.And.evaluate(And.java:55)
	at org.janusgraph.graphdb.query.graph.GraphCentricQuery.matches(GraphCentricQuery.java:153)
	at org.janusgraph.graphdb.query.QueryProcessor.lambda$getFilterIterator$2(QueryProcessor.java:133)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:637)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at org.janusgraph.graphdb.query.ResultSetIterator.nextInternal(ResultSetIterator.java:54)
	at org.janusgraph.graphdb.query.ResultSetIterator.<init>(ResultSetIterator.java:44)
	at org.janusgraph.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:66)
	at com.google.common.collect.Iterables$4.iterator(Iterables.java:559)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStep.executeGraphCentricQuery(JanusGraphStep.java:155)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStep.lambda$null$1(JanusGraphStep.java:94)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStep.lambda$new$2(JanusGraphStep.java:94)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:157)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:197)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:43)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at org.thp.scalligraph.services.IntegrityCheckOps.$anonfun$getDuplicates$4(IntegrityCheckOps.scala:47)
	at org.thp.scalligraph.janus.JanusDatabase.roTransaction(JanusDatabase.scala:133)
	at org.thp.scalligraph.services.IntegrityCheckOps.getDuplicates(IntegrityCheckOps.scala:40)
	at org.thp.scalligraph.services.IntegrityCheckOps.getDuplicates$(IntegrityCheckOps.scala:33)
	at org.thp.thehive.services.ResolutionStatusIntegrityCheckOps.getDuplicates(ResolutionStatusSrv.scala:56)
	at org.thp.scalligraph.services.IntegrityCheckOps.$anonfun$duplicateEntities$2(IntegrityCheckOps.scala:205)
	at scala.Option.fold(Option.scala:251)
	at org.thp.scalligraph.services.IntegrityCheckOps.duplicateEntities(IntegrityCheckOps.scala:205)
	at org.thp.scalligraph.services.IntegrityCheckOps.duplicateEntities$(IntegrityCheckOps.scala:205)
	at org.thp.thehive.services.ResolutionStatusIntegrityCheckOps.duplicateEntities(ResolutionStatusSrv.scala:56)
	at org.thp.scalligraph.services.IntegrityCheckOps.check(IntegrityCheckOps.scala:208)
	at org.thp.scalligraph.services.IntegrityCheckOps.check$(IntegrityCheckOps.scala:207)
	at org.thp.thehive.services.ResolutionStatusIntegrityCheckOps.check(ResolutionStatusSrv.scala:56)
	at org.thp.thehive.services.IntegrityCheckActor.$anonfun$preStart$3(IntegrityCheckActor.scala:61)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:338)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:1111)
	at org.thp.thehive.services.IntegrityCheckActor.preStart(IntegrityCheckActor.scala:60)
	at akka.actor.Actor.aroundPreStart(Actor.scala:546)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:546)
	at org.thp.thehive.services.IntegrityCheckActor.aroundPreStart(IntegrityCheckActor.scala:25)
	at akka.actor.ActorCell.create(ActorCell.scala:639)
	... 10 common frames omitted
```

I have no idea what this error means.

**Comment by jakubgs** [comment]
While the problem persists I have fixed the startup failure. It was caused by this error:
```
Configuration error: Configuration error[/data/thehive/conf/application.conf: 41:
    Expecting a value but got wrong token: 'newline' (JSON does not allow unescaped newline in quoted strings, use a backslash escape) (if you intended 'newline' (JSON does not allow unescaped newline in quoted strings, use a backslash escape) to be part of a key or string value, try enclosing the key or value in double quotes)]
```
Which in turn was due to not matching quotes. But this log never appeared in `application.log`. I had to start the app by hand rather than via systemd service definition to see that error. Werid.

**Comment by To-om** [comment]
The transaction management have been redesigned in the coming release 4.0.1. Your error "Cannot access element because its enclosing transaction is closed and unbound" should not appear any more. If you still have similar message in 4.0.1, please reopen this issue.

Regarding your configuration issue, this is a known issue on Play. If you have a  syntax error on your configuration file, the service start fails before initializing logs. You need to check service output to find the reason.

**Comment by raghu789p** [comment]
HI Team,
Greetings! 
 I am facing this issue i am not getting  logs from MISP to Hive i got only 28 alerts , please help me

The Hive version TheHive4.1.24-1

thehive.connector.misp.services.MispImportSrv in application-akka.actor.default-dispatcher-15 [|] Don't know how to convert attribute Attribute(22879,filename|sha1,Payload delivery,true,103,5,Thu Apr 28 08:04:27 UTC 2016,Some(malware sample),false,None,d6twg|d3422d54a69efe84c91fbc6ad615642ee65da389,None,None,List())
2024-06-17 06:56:13,603 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-15 [|] An error occurs (java.lang.IllegalStateException: Cannot access element because its enclosing transaction is closed and unbound), retrying (1)
2024-06-17 06:56:13,603 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-15 [|] An error occurs (java.lang.IllegalStateException: Cannot access element because its enclosing transaction is closed and unbound), retrying (1)
2024-06-17 06:56:13,603 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-15 [|] An error occurs (java.lang.IllegalStateException: Cannot access element because its enclosing transaction is closed and unbound), retrying (1)
2024-06-17 06:56:13,603 [WARN] from org.thp.thehive.connector.misp.services.MispImportSrv in application-akka.actor.default-dispatcher-15 [|] Don't know how to convert attribute Attribute(22880,filename|sha256,Payload delivery,true,103,5,Thu Apr 28 08:04:28 UTC 2016,Some(malware sample),false,None,d6twg|6f5cf2172d39828cd8b72a14af7f356818abf99bf21df23e9581370f9480b0ef,None,None,List())
