### ISSUE TITLE
[Bug] Issues with AD authentication

### ISSUE THREAD

**Issue by meelich** [TheHive-Project/TheHive#1605]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Win10
| TheHive version / git hash   | 4.0
| Package Type              | DEB
| Browser type & version    | Chrome Version 86.0.4240.111 / Firefox 82.0.2

### Problem Description
Authentication against AD fails with error "Operation not permitted"

### Steps to Reproduce
1. Configure application.conf for AD: 
auth {
  provider: [
    {name: session}               # required !
    {name: basic, realm: thehive}
    {
      name: ad
      winDomain: "COMPANY"
      dnsDomain: "internalcompany.net"
      useSSL:  false
      hosts: ["dc.internalcompany.net"]
    }
 {name: local}
 {name: key}
  ]

defaultUserDomain: "internalcompany.net"
}

2. Create user in TheHive: sAMAccountname@internalcompany.net
3. Logon as sAMAccountname@internalcompany.net
4. Login fails:
2020-10-30 13:51:35,784 [ERROR] from org.thp.thehive.services.TOTPAuthSrv in application-akka.actor.default-dispatcher-10 [00000018|46bc444c] Authentication failure
org.thp.scalligraph.AuthenticationError: Operation not supported
        at org.thp.scalligraph.auth.AuthSrv.authenticate(AuthSrv.scala:55)
        at org.thp.scalligraph.auth.AuthSrv.authenticate$(AuthSrv.scala:52)
        at org.thp.scalligraph.auth.KeyAuthSrv.authenticate(KeyAuthSrv.scala:11)
        at org.thp.scalligraph.auth.MultiAuthSrv.$anonfun$authenticate$1(MultiAuthSrv.scala:71)
        at org.thp.scalligraph.auth.MultiAuthSrv$$anonfun$$nestedInanonfun$forAllAuthProvider$1$1.applyOrElse(MultiAuthSrv.scala:59)
        at org.thp.scalligraph.auth.MultiAuthSrv$$anonfun$$nestedInanonfun$forAllAuthProvider$1$1.applyOrElse(MultiAuthSrv.scala:57)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
        at scala.util.Failure.recoverWith(Try.scala:236)
        at org.thp.scalligraph.auth.MultiAuthSrv.$anonfun$forAllAuthProvider$1(MultiAuthSrv.scala:57)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
        at scala.collection.immutable.List.foldLeft(List.scala:89)
        at org.thp.scalligraph.auth.MultiAuthSrv.forAllAuthProvider(MultiAuthSrv.scala:56)
        at org.thp.scalligraph.auth.MultiAuthSrv.authenticate(MultiAuthSrv.scala:71)
        at org.thp.thehive.services.TOTPAuthSrv.authenticate(TOTPAuthSrv.scala:65)
        at org.thp.thehive.controllers.v0.AuthenticationCtrl.$anonfun$login$3(AuthenticationCtrl.scala:42)
        at org.thp.scalligraph.janus.JanusDatabase.roTransaction(JanusDatabase.scala:133)
        at org.thp.thehive.controllers.v0.AuthenticationCtrl.$anonfun$login$1(AuthenticationCtrl.scala:40)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$apply$2(Entrypoint.scala:147)
        at org.thp.scalligraph.DiagnosticContext$.$anonfun$withRequest$2(ContextPropagatingDisptacher.scala:99)
        at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:106)
        at org.thp.scalligraph.DiagnosticContext$.withRequest(ContextPropagatingDisptacher.scala:97)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$apply$1(Entrypoint.scala:147)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$async$3(Entrypoint.scala:161)
        at org.scalactic.Good.fold(Or.scala:1229)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$async$2(Entrypoint.scala:161)
        at org.thp.scalligraph.DiagnosticContext$.$anonfun$withRequest$2(ContextPropagatingDisptacher.scala:99)
        at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:106)
        at org.thp.scalligraph.DiagnosticContext$.withRequest(ContextPropagatingDisptacher.scala:97)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$async$1(Entrypoint.scala:161)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:441)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:439)
        at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:379)
        at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:168)
        at scala.util.Try$.apply(Try.scala:213)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:168)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:200)
        at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:417)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$2(ContextPropagatingDisptacher.scala:56)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.thp.scalligraph.DiagnosticContext$$anon$2.withContext(ContextPropagatingDisptacher.scala:75)
        at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$1(ContextPropagatingDisptacher.scala:56)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2020-10-30 13:51:35,785 [WARN] from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-10 [00000018|] POST /api/login returned 401: Authentication failure
2020-10-30 13:51:35,786 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-10 [00000018|] 139.3.253.200 POST /api/login took 11ms and returned 401 65 bytes

### Complementary information

I understand that this issue is very similar to https://github.com/TheHive-Project/TheHive/issues/1453, but the suggested workaround was tested and does not work.

More information about our AD setup:
NETBIOS: COMPANY
dnsDomain: internalcompany.net
UPNs: firstname.lastname@externalcompany.com

I've modified the application conf and tried various configurations as our UserPrincipalname differs from the dnsDomain, but none of them works. 
I've set up a network capture to capture any and all traffic going from TheHive to our domain controller, but I don't see any traffic at all.
Firewall on TheHive is active, but allows outgoing and returning traffic to the firewall.

I also tried it with LDAP, but it failed with the same error, and no traffic was recorded in the network capture.

Please advise if you need any additional information, happy to provide any.

**Comment by nadouani** [comment]
Is this similar to #1453 ? If not, please feel free to reopen

**Comment by meelich** [comment]
@nadouani , I tried the workarounds in #1453, they don't work for me. I agree that it is similar, with the major difference that I don't see any network traffic going from TheHive to our Domain Controller at all. If it truly was only an authentication issue, I would still have to see data packets going over the wire. I am happy to continue the discussion under #1453 if that makes more sense.
