### ISSUE TITLE
Migration failed - 

### ISSUE THREAD

**Issue by NauckR** [TheHive-Project/TheHive#1618]
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 20.04
| OS version (client)       | Ubuntu 20.04
| TheHive version / git hash   | 4.0
| Package Type              | Followed the Installation instruction for Debian on the Doc section

### Problem Description
Migration failed:

[error] Migration failed
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Could not find implementation class: org.janusgraph.diskstorage.inmemory.InMemoryStoreManager
  at org.thp.scalligraph.janus.JanusDatabase.<init>(JanusDatabase.scala:71)
  at org.thp.scalligraph.janus.JanusDatabase.class(JanusDatabase.scala:56)
  while locating org.thp.scalligraph.janus.JanusDatabase
  while locating org.thp.scalligraph.models.Database
    for the 2nd parameter of org.thp.scalligraph.services.config.ApplicationConfig.<init>(ApplicationConfig.scala:20)
  at org.thp.scalligraph.services.config.ApplicationConfig.class(ApplicationConfig.scala:19)
  while locating org.thp.scalligraph.services.config.ApplicationConfig
    for the 1st parameter of org.thp.thehive.services.TagSrv.<init>(TagSrv.scala:17)
  at org.thp.thehive.services.TagSrv.class(TagSrv.scala:17)
  while locating org.thp.thehive.services.TagSrv
    for the 1st parameter of org.thp.thehive.services.CaseSrv.<init>(CaseSrv.scala:26)
  at org.thp.thehive.services.CaseSrv.class(CaseSrv.scala:25)
  while locating org.thp.thehive.services.CaseSrv
    for the 3rd parameter of org.thp.thehive.migration.th4.Output.<init>(Output.scala:109)
  at org.thp.thehive.migration.th4.Output.class(Output.scala:108)
  while locating org.thp.thehive.migration.th4.Output

1 error
	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1097)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131)
	at org.thp.thehive.migration.th4.Output$.apply(Output.scala:98)
	at org.thp.thehive.migration.Migrate$.$anonfun$new$2(Migrate.scala:157)
	at org.thp.thehive.migration.Migrate$.$anonfun$new$2$adapted(Migrate.scala:142)
	at scala.Option.foreach(Option.scala:407)
	at org.thp.thehive.migration.Migrate$.delayedEndpoint$org$thp$thehive$migration$Migrate$1(Migrate.scala:142)
	at org.thp.thehive.migration.Migrate$delayedInit$body.apply(Migrate.scala:16)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
Caused by: java.lang.IllegalArgumentException: Could not find implementation class: org.janusgraph.diskstorage.inmemory.InMemoryStoreManager
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:60)
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:440)
	at org.janusgraph.diskstorage.Backend.getStorageManager(Backend.java:411)
	at org.janusgraph.graphdb.configuration.builder.GraphDatabaseConfigurationBuilder.build(GraphDatabaseConfigurationBuilder.java:50)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:161)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:132)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:112)
	at org.thp.scalligraph.janus.JanusDatabase$.openDatabase(JanusDatabase.scala:51)
	at org.thp.scalligraph.janus.JanusDatabase.<init>(JanusDatabase.scala:72)
	at org.thp.scalligraph.janus.JanusDatabase$$FastClassByGuice$$113881e3.newInstance(<generated>)
Caused by: java.lang.ClassNotFoundException: org.janusgraph.diskstorage.inmemory.InMemoryStoreManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:56)
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:440)
	at org.janusgraph.diskstorage.Backend.getStorageManager(Backend.java:411)
	at org.janusgraph.graphdb.configuration.builder.GraphDatabaseConfigurationBuilder.build(GraphDatabaseConfigurationBuilder.java:50)
[info] Stage: initialisation

### Steps to Reproduce
1. Install TheHive 4.0 on Ubuntu 20.04 based on the description for Debian within TheHive Docs.
1. ShutDown the Hive service and start Migration

### Complementary information
I attached the complete output from the terminal after running the migration command

[Migration.txt](https://github.com/TheHive-Project/TheHive/files/5493907/Migration.txt)

**Comment by To-om** [comment]
You need to configure destination database. Fill an `application.conf` as describe in the [documentation](https://github.com/TheHive-Project/TheHiveDocs/blob/master/TheHive4/Installation/Install_deb.md#database) and run the migration tool with the parameter `-o /path/to/application.conf`. For full option, use `--help`.
