### ISSUE TITLE
[Bug] Migration from ES5.6 to TheHive 4.0.1 failes

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1658]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4.0.1
| Package Type              | DEB

### Problem Description
Migration from ElasticSearch 5.6 to TheHive 4.0.1 using migration tool without any filters failes, with the following error messages (below you can find the time output that was wrapping the migration):
```

6 Case/Observable:3895/46450 User:70/70 CustomField:9/9 Case/Task/Log:1400/18951
[info] [Migrate cases and alerts] CaseTemplate/Task:42 Organisation:1/1 Case/Task:1288/11658 Case:916/8575 Job:651/5546 ObservableType:4/18 Alert:9/16 Audit:29557/310256 CaseTemplate:21/21 Alert/Observable:26 Case/Observable:3895/46450 User:70/70 CustomField:9/9 Case/Task/Log:1400/18951
[info] [Migrate cases and alerts] CaseTemplate/Task:42 Organisation:1/1 Case/Task:1288/11658 Case:916/8575 Job:651/5546 ObservableType:4/18 Alert:9/16 Audit:29557/310256 CaseTemplate:21/21 Alert/Observable:26 Case/Observable:3895/46450 User:70/70 CustomField:9/9 Case/Task/Log:1400/18951
[info] [Migrate cases and alerts] CaseTemplate/Task:42 Organisation:1/1 Case/Task:1288/11658 Case:916/8575 Job:651/5546 ObservableType:4/18 Alert:9/16 Audit:29557/310256 CaseTemplate:21/21 Alert/Observable:26 Case/Observable:3895/46450 User:70/70 CustomField:9/9 Case/Task/Log:1400/18951
[error] ElasticSearch request failure: POST:/_search/scroll?
StringEntity({"scroll":"36000000ms","scroll_id":"DnF1ZXJ5VGhlbkZldGNoBQAAAAAAJSvEFi1NWmZ5RGVRVFItTWF4SHZHWl9qaWcAAAAAACUrxxYtTVpmeURlUVRSLU1heEh2R1pfamlnAAAAAAAlK8gWLU1aZnlEZVFUUi1NYXhIdkdaX2ppZwAAAAAAJSvFFi1NWmZ5RGVRVFItTWF4SHZHWl9qaWcAAAAAACUrxhYtTVpmeURlUVRSLU1heEh2R1pfamln"},Some(application/json))
 => ElasticError(search_phase_execution_exception,all shards failed,None,None,None,List(ElasticError(search_context_missing_exception,No search context found for id [2436038],None,None,None,null,None), ElasticError(search_context_missing_exception,No search context found for id [2436037],None,None,None,null,None), ElasticError(search_context_missing_exception,No search context found for id [2436040],None,None,None,null,None), ElasticError(search_context_missing_exception,No search context found for id [2436036],None,None,None,null,None), ElasticError(search_context_missing_exception,No search context found for id [2436039],None,None,None,null,None)),Some(CausedBy(search_context_missing_exception,No search context found for id [2436039],Map())))
[warn] Search error
org.thp.scalligraph.SearchError: all shards failed
        at org.thp.thehive.migration.th3.DBConfiguration.$anonfun$execute$2(DBConfiguration.scala:146)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$2(ContextPropagatingDisptacher.scala:56)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.thp.scalligraph.DiagnosticContext$.$anonfun$withDiagnosticContext$2(ContextPropagatingDisptacher.scala:91)
        at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:106)
        at org.thp.scalligraph.DiagnosticContext$.withDiagnosticContext(ContextPropagatingDisptacher.scala:89)
        at org.thp.scalligraph.DiagnosticContext$$anon$2.withContext(ContextPropagatingDisptacher.scala:74)
[error] Migration failed
org.thp.scalligraph.SearchError: Request terminated early or timed out
        at org.thp.thehive.migration.th3.SearchWithScroll$$anon$1$$anon$2.$anonfun$onPull$1(DBFind.scala:195)
        at org.thp.thehive.migration.th3.SearchWithScroll$$anon$1$$anon$2.$anonfun$onPull$1$adapted(DBFind.scala:175)
        at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:466)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:498)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
[info] Stage: Migrate cases and alerts
Action: 0/0
Alert/Observable: 27/27 avg:18ms
Alert: 10/16 avg:24ms
Audit: 29577/310256 avg:11ms
Case/Observable: 3896/46450 avg:28ms
Case/Task/Log: 1401/18951 avg:27059ms
Case/Task: 1288/11658 avg:13ms
Case: 916/8575 avg:28ms
CaseTemplate/Task: 42/42 avg:11ms
CaseTemplate: 21/21 avg:42ms
CustomField: 9/9 avg:9ms
ImpactStatus: 0/0
Job: 651/5546 avg:7ms
ObservableType: 4/18 (14 exists) avg:201ms
Organisation: 1/1 avg:1105ms
Profile: 0/0
ResolutionStatus: 0/0
User: 70/70 avg:111ms


real    645m45.729s
user    274m9.196s
sys     175m25.208s
```

**Comment by mamoedo** [comment]
Hi @crackytsi, I think ES5.6 may not be supported for migration:

https://github.com/TheHive-Project/TheHiveDocs/blob/master/TheHive4/Administration/Migration.md

**Comment by nadouani** [comment]
Hello @crackytsi the migration relies on ES version an only work if the source thehive version is using an ES6

**Comment by crackytsi** [comment]
Thank you and sorry for generating an issue without having the documentation read (again).
