### ISSUE TITLE
[Bug] Hadoop connection refused for file observable upload

### ISSUE THREAD

**Issue by smclinden** [TheHive-Project/TheHive#1683]
### Request Type
Bug
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Web access
| TheHive version / git hash   | 4.0.0
| Package Type              | Release
| Browser type & version    | Edge/Chrome

### Problem Description
I can add most Observables without problems but when I try to add a File I get a "Connection Refused" error with Hadoop.

### Steps to Reproduce
1. Create a new case.
2. Add an observable of type File.
3. A connection error occurs for Hadoop.

**Comment by nadouani** [comment]
Hello @smclinden we need much more details to be able to help. "Connection Refused" is for sure a connection issue because of you configuration.

**Comment by nadouani** [comment]
Please share logs and configuration

**Comment by smclinden** [comment]
application.conf (hadoop is listening on 0.0.0.0:10000)

```
## Attachment storage configuration
storage {
  ## Local filesystem
  # provider: localfs
  # localfs.directory: /apps/data/thehive

  ## Hadoop filesystem (HDFS)
  provider: hdfs
  hdfs {
    root: "hdfs://localhost:10000" # namenode server hostname
    location: "/thehive"           # location inside HDFS
    username: thehive              # file owner
  }
}
```

Netstat output:

```
tcp        0      0 10.223.128.232:10000    0.0.0.0:*               LISTEN     
tcp        0      0 10.223.128.232:45076    10.223.128.232:10000    ESTABLISHED
tcp        0      0 10.223.128.232:10000    10.223.128.232:45076    ESTABLISHED
tcp        0      0 10.223.128.232:50654    10.223.128.232:10000    TIME_WAIT 
```

And application.log (filtered):

```
2020-11-24 11:19:23,761 [WARN] from org.thp.scalligraph.query.InputFilter in application-akka.actor.default-dispatcher-142821 - Use of filter {"status": "FString(Waiting)"} is deprecated. Please use {"_is":{"status":"FString(Waitin
g)"}}
2020-11-24 11:19:23,766 [WARN] from org.thp.scalligraph.query.InputFilter in application-akka.actor.default-dispatcher-142766 - Use of filter {"owner": "FString(sean.mclinden@host.tld)"} is deprecated. Please use {"_is":{"owner":"F
String(sean.mclinden@host.tld)"}}
2020-11-24 11:20:12,190 [WARN] from org.janusgraph.diskstorage.idmanagement.ConsistentKeyIDAuthority in JanusGraphID(2)(0)[0] - Temporary storage exception while acquiring id block - retrying in PT0.6S: {}
org.janusgraph.diskstorage.TemporaryBackendException: Wrote claim for id block [20001, 30001) in PT0.475S => too slow, threshold is: PT0.3S
	at org.janusgraph.diskstorage.idmanagement.ConsistentKeyIDAuthority.getIDBlock(ConsistentKeyIDAuthority.java:268)
	at org.janusgraph.graphdb.database.idassigner.StandardIDPool$IDBlockGetter.call(StandardIDPool.java:288)
	at org.janusgraph.graphdb.database.idassigner.StandardIDPool$IDBlockGetter.call(StandardIDPool.java:255)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-11-24 11:20:14,291 [WARN] from org.janusgraph.diskstorage.locking.consistentkey.ConsistentKeyLocker in application-akka.actor.default-dispatcher-142766 - Lock write succeeded but took too long: duration PT0.118S exceeded limit
 PT0.1S
2020-11-24 11:20:14,969 [WARN] from org.thp.scalligraph.query.InputFilter in application-akka.actor.default-dispatcher-142745 - Use of filter {"status": "FString(Cancel)"} is deprecated. Please use {"_is":{"status":"FString(Cancel)
"}}
2020-11-24 11:20:14,970 [WARN] from org.thp.scalligraph.query.InputFilter in application-akka.actor.default-dispatcher-142826 - Use of filter {"status": "FString(Ok)"} is deprecated. Please use {"_is":{"status":"FString(Ok)"}}
2020-11-24 11:20:14,973 [WARN] from org.thp.scalligraph.query.InputFilter in application-akka.actor.default-dispatcher-142767 - Use of filter {"case": "FString(81932448)"} is deprecated. Please use {"_is":{"case":"FString(81932448)
"}}
2020-11-24 11:20:14,973 [WARN] from org.thp.scalligraph.query.InputFilter in application-akka.actor.default-dispatcher-142766 - Use of filter {"status": "FString(Deleted)"} is deprecated. Please use {"_is":{"status":"FString(Delete
d)"}}
2020-11-24 11:20:15,255 [WARN] from org.thp.scalligraph.query.InputFilter in application-akka.actor.default-dispatcher-142824 - Use of filter {"status": "FString(Deleted)"} is deprecated. Please use {"_is":{"status":"FString(Delete
d)"}}
2020-11-24 11:20:15,255 [WARN] from org.thp.scalligraph.query.InputFilter in application-akka.actor.default-dispatcher-142824 - Use of filter {"objectType": "FString(case)"} is deprecated. Please use {"_is":{"objectType":"FString(c
ase)"}}
2020-11-24 11:20:15,256 [WARN] from org.thp.scalligraph.query.InputFilter in application-akka.actor.default-dispatcher-142824 - Use of filter {"objectId": "FString(81932448)"} is deprecated. Please use {"_is":{"objectId":"FString(8
1932448)"}}
2020-11-24 11:20:15,265 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-142766 - 172.31.83.29 GET /api/case/81932448/links took 12ms and returned 200 2 bytes
2020-11-24 11:20:15,270 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-142824 - 172.31.83.29 POST /api/connector/cortex/action/_search?range=0-100&sort=-startDate took 17ms and returned
 200 2 bytes
2020-11-24 11:20:15,374 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-142824 - 172.31.83.29 GET /fonts/SourceSansPro-Semibold.otf took 1ms and returned 200 232680 bytes
2020-11-24 11:20:15,383 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-142766 - 172.31.83.29 GET /api/case/81932448?nstats=true took 19ms and returned 200 734 bytes
2020-11-24 11:20:15,918 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-142745 - 172.31.83.29 GET /api/flow?count=10&rootId=81932448 took 576ms and returned 200 1186 bytes
2020-11-24 11:20:16,519 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-142826 - 172.31.83.29 GET /api/stream/nuBuKCvYMyLjOmuv07nE took 60013ms and returned 200 2 bytes
2020-11-24 11:20:18,741 [WARN] from org.thp.scalligraph.query.InputFilter in application-akka.actor.default-dispatcher-142766 - Use of filter {"status": "FString(Ok)"} is deprecated. Please use {"_is":{"status":"FString(Ok)"}}
2020-11-24 11:20:18,758 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-142745 - 172.31.83.29 POST /api/case/artifact/_search?range=all&sort=-startDate&nstats=true took 19ms and returned
 200 2 bytes
2020-11-24 11:20:18,998 [WARN] from org.thp.scalligraph.query.InputFilter in application-akka.actor.default-dispatcher-142766 - Use of filter {"status": "FString(Ok)"} is deprecated. Please use {"_is":{"status":"FString(Ok)"}}
2020-11-24 11:20:19,007 [WARN] from org.thp.scalligraph.query.InputFilter in application-akka.actor.default-dispatcher-142821 - Use of filter {"status": "FString(Ok)"} is deprecated. Please use {"_is":{"status":"FString(Ok)"}}
2020-11-24 11:20:19,009 [WARN] from org.thp.scalligraph.query.InputFilter in application-akka.actor.default-dispatcher-142826 - Use of filter {"status": "FString(Ok)"} is deprecated. Please use {"_is":{"status":"FString(Ok)"}}
2020-11-24 11:21:38,697 [ERROR] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-142744 - uncaught error, not retrying
java.net.ConnectException: Call From host.tld/10.223.128.232 to localhost:10000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/Conn
ectionRefused
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:833)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:757)
	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1549)
	at org.apache.hadoop.ipc.Client.call(Client.java:1491)
	at org.apache.hadoop.ipc.Client.call(Client.java:1388)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:233)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:118)
	at com.sun.proxy.$Proxy38.create(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.create(ClientNamenodeProtocolTranslatorPB.java:369)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy39.create(Unknown Source)
	at org.apache.hadoop.hdfs.DFSOutputStream.newStreamForCreate(DFSOutputStream.java:276)
	at org.apache.hadoop.hdfs.DFSClient.create(DFSClient.java:1217)
	at org.apache.hadoop.hdfs.DFSClient.create(DFSClient.java:1196)
	at org.apache.hadoop.hdfs.DFSClient.create(DFSClient.java:1134)
	at org.apache.hadoop.hdfs.DistributedFileSystem$8.doCall(DistributedFileSystem.java:530)
	at org.apache.hadoop.hdfs.DistributedFileSystem$8.doCall(DistributedFileSystem.java:527)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.create(DistributedFileSystem.java:541)
	at org.apache.hadoop.hdfs.DistributedFileSystem.create(DistributedFileSystem.java:468)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1118)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1098)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:987)
	at org.thp.scalligraph.services.HadoopStorageSrv.$anonfun$saveBinary$3(StorageSrv.scala:102)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at org.thp.scalligraph.services.HadoopStorageSrv.saveBinary(StorageSrv.scala:101)
	at org.thp.thehive.services.AttachmentSrv.create(AttachmentSrv.scala:41)
	at org.thp.thehive.services.ObservableSrv.create(ObservableSrv.scala:49)
	at org.thp.thehive.controllers.v0.ObservableCtrl.$anonfun$create$8(ObservableCtrl.scala:77)
	at scala.Option.map(Option.scala:230)
	at org.thp.thehive.controllers.v0.ObservableCtrl.$anonfun$create$7(ObservableCtrl.scala:77)
	at scala.util.Success.flatMap(Try.scala:251)
	at org.thp.thehive.controllers.v0.ObservableCtrl.$anonfun$create$5(ObservableCtrl.scala:72)
	at scala.util.Success.flatMap(Try.scala:251)
	at org.thp.thehive.controllers.v0.ObservableCtrl.$anonfun$create$4(ObservableCtrl.scala:71)
	at scala.util.Success.flatMap(Try.scala:251)
	at org.thp.thehive.controllers.v0.ObservableCtrl.$anonfun$create$3(ObservableCtrl.scala:67)
	at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$authTransaction$2(Entrypoint.scala:77)
	at org.thp.scalligraph.janus.JanusDatabase.$anonfun$tryTransaction$10(JanusDatabase.scala:136)
	at scala.util.Try$.apply(Try.scala:213)
	at org.thp.scalligraph.janus.JanusDatabase.$anonfun$tryTransaction$8(JanusDatabase.scala:136)
	at scala.util.Try$.apply(Try.scala:213)
	at org.thp.scalligraph.utils.DelayRetry.withTry(Retry.scala:88)
	at org.thp.scalligraph.janus.JanusDatabase.tryTransaction(JanusDatabase.scala:130)
	at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$authTransaction$1(Entrypoint.scala:77)
	at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$auth$1(Entrypoint.scala:86)
	at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$asyncAuth$3(Entrypoint.scala:107)
	at org.scalactic.Good.fold(Or.scala:1229)
	at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$asyncAuth$2(Entrypoint.scala:107)
	at org.thp.scalligraph.DiagnosticContext$.$anonfun$withRequest$2(ContextPropagatingDisptacher.scala:100)
	at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:107)
	at org.thp.scalligraph.DiagnosticContext$.withRequest(ContextPropagatingDisptacher.scala:98)
	at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$asyncAuth$1(Entrypoint.scala:107)
	at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.$anonfun$invokeBlock$2(SessionAuthSrv.scala:84)
	at scala.Option.fold(Option.scala:251)
	at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.invokeBlock(SessionAuthSrv.scala:82)
	at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.invokeBlock(SessionAuthSrv.scala:79)
	at play.api.mvc.ActionBuilder$$anon$10.$anonfun$invokeBlock$2(Action.scala:408)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:441)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:439)
	at play.api.mvc.ActionBuilder$$anon$10.invokeBlock(Action.scala:408)
	at play.api.mvc.ActionBuilder$$anon$10.invokeBlock(Action.scala:404)
	at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:379)
	at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$2(ContextPropagatingDisptacher.scala:57)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.thp.scalligraph.DiagnosticContext$.$anonfun$withDiagnosticContext$2(ContextPropagatingDisptacher.scala:92)
	at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:107)
	at org.thp.scalligraph.DiagnosticContext$.withDiagnosticContext(ContextPropagatingDisptacher.scala:90)
	at org.thp.scalligraph.DiagnosticContext$$anon$2.withContext(ContextPropagatingDisptacher.scala:75)
	at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$1(ContextPropagatingDisptacher.scala:57)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:533)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:700)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:804)
	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:421)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1606)
	at org.apache.hadoop.ipc.Client.call(Client.java:1435)
	... 85 common frames omitted
2020-11-24 11:21:38,698 [ERROR] from org.thp.scalligraph.models.Database in application-akka.actor.default-dispatcher-142744 - Exception raised, rollback (Call From localhost.tld/10.223.128.232 to localhost:10000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused)
```
There are no corresponding entries in the Hadoop logs.

**Comment by smclinden** [comment]
Also, there are no folders in the DFS file system.

**Comment by smclinden** [comment]
core-site.xml
```
<configuration>
  <property>
    <name>fs.defaultFS</name>
    <value>hdfs://0.0.0.0:10000</value>
  </property>
  <property>
    <name>hadoop.tmp.dir</name>
    <value>/apps/data/hdfs/temp</value>
  </property>
  <property>
    <name>dfs.client.block.write.replace-datanode-on-failure.best-effort</name>
    <value>true</value>
  </property>
</configuration>
```

hdfs-site.xml:
```
<configuration>
  <property>
    <name>dfs.replication</name>
    <value>2</value>
  </property>
  <property>
    <name>dfs.permission</name>
    <value>false</value>
  </property>
  <property>
    <name>dfs.namenode.name.dir</name>
    <value>/apps/data/hdfs/namenode/data</value>
  </property>
  <property>
    <name>dfs.datanode.name.dir</name>
    <value>/apps/data/hdfs/datanode/data</value>
  </property>
  <property>
    <name>dfs.namenode.checkpoint.dir</name>
    <value>/apps/data/hdfs/checkpoint</value>
  </property>
  <property>
    <name>dfs.namenode.http-address</name>
    <value>0.0.0.0:9870</value>
  </property>
  <!--
  <property>
    <name>dfs.client.block.write.replace-datanode-on-failure.best-effort</name>
    <value>true</value>
  </property>
-->
  <property>
    <name>dfs.client.block.write.replace-datanode-on-failure.policy</name>
    <value>NEVER</value>
  </property>
</configuration>
```

**Comment by smclinden** [comment]
Running start-all.sh as "hadoop" with debugging I get:
```
WARNING: Attempting to start all Apache Hadoop daemons as hadoop in 10 seconds.
WARNING: This is not a recommended production deployment configuration.
WARNING: Use CTRL-C to abort.
Starting namenodes on [0.0.0.0]
0.0.0.0: Authorized Use Only. Transactions may be monitored.
0.0.0.0: By continuing past this point, you expressly consent to this monitoring.
Starting datanodes
localhost: Authorized Use Only. Transactions may be monitored.
localhost: By continuing past this point, you expressly consent to this monitoring.
Starting secondary namenodes [UBTU-CS-P-3569.dcsg.com]
UBTU-CS-P-3569: Authorized Use Only. Transactions may be monitored.
UBTU-CS-P-3569: By continuing past this point, you expressly consent to this monitoring.
2020-11-25 10:21:29,092 DEBUG util.Shell: setsid exited with exit code 0
2020-11-25 10:21:29,228 DEBUG lib.MutableMetricsFactory: field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.getGroups with annotation @org.apache.hadoop.metrics2.annotation.Metric(sampleName=Ops, always=false, valueName=Time, about=, interval=10, type=DEFAULT, value=[GetGroups])
2020-11-25 10:21:29,233 DEBUG lib.MutableMetricsFactory: field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.loginFailure with annotation @org.apache.hadoop.metrics2.annotation.Metric(sampleName=Ops, always=false, valueName=Time, about=, interval=10, type=DEFAULT, value=[Rate of failed kerberos logins and latency (milliseconds)])
2020-11-25 10:21:29,233 DEBUG lib.MutableMetricsFactory: field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.loginSuccess with annotation @org.apache.hadoop.metrics2.annotation.Metric(sampleName=Ops, always=false, valueName=Time, about=, interval=10, type=DEFAULT, value=[Rate of successful kerberos logins and latency (milliseconds)])
2020-11-25 10:21:29,233 DEBUG lib.MutableMetricsFactory: field private org.apache.hadoop.metrics2.lib.MutableGaugeInt org.apache.hadoop.security.UserGroupInformation$UgiMetrics.renewalFailures with annotation @org.apache.hadoop.metrics2.annotation.Metric(sampleName=Ops, always=false, valueName=Time, about=, interval=10, type=DEFAULT, value=[Renewal failures since last successful login])
2020-11-25 10:21:29,233 DEBUG lib.MutableMetricsFactory: field private org.apache.hadoop.metrics2.lib.MutableGaugeLong org.apache.hadoop.security.UserGroupInformation$UgiMetrics.renewalFailuresTotal with annotation @org.apache.hadoop.metrics2.annotation.Metric(sampleName=Ops, always=false, valueName=Time, about=, interval=10, type=DEFAULT, value=[Renewal failures since startup])
2020-11-25 10:21:29,234 DEBUG impl.MetricsSystemImpl: UgiMetrics, User and group related metrics
2020-11-25 10:21:29,253 DEBUG security.SecurityUtil: Setting hadoop.security.token.service.use_ip to true
2020-11-25 10:21:29,271 DEBUG security.Groups:  Creating new Groups object
2020-11-25 10:21:29,273 DEBUG util.NativeCodeLoader: Trying to load the custom-built native-hadoop library...
2020-11-25 10:21:29,273 DEBUG util.NativeCodeLoader: Loaded the native-hadoop library
2020-11-25 10:21:29,273 DEBUG security.JniBasedUnixGroupsMapping: Using JniBasedUnixGroupsMapping for Group resolution
2020-11-25 10:21:29,274 DEBUG security.JniBasedUnixGroupsMappingWithFallback: Group mapping impl=org.apache.hadoop.security.JniBasedUnixGroupsMapping
2020-11-25 10:21:29,335 DEBUG security.Groups: Group mapping impl=org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback; cacheTimeout=300000; warningDeltaMs=5000
2020-11-25 10:21:29,340 DEBUG security.UserGroupInformation: Hadoop login
2020-11-25 10:21:29,340 DEBUG security.UserGroupInformation: hadoop login commit
2020-11-25 10:21:29,343 DEBUG security.UserGroupInformation: Using local user: UnixPrincipal: hadoop
2020-11-25 10:21:29,343 DEBUG security.UserGroupInformation: Using user: "UnixPrincipal: hadoop" with name: hadoop
2020-11-25 10:21:29,344 DEBUG security.UserGroupInformation: User entry: "hadoop"
2020-11-25 10:21:29,344 DEBUG security.UserGroupInformation: UGI loginUser: hadoop (auth:SIMPLE)
2020-11-25 10:21:29,345 DEBUG security.UserGroupInformation: PrivilegedAction [as: hadoop (auth:SIMPLE)][action: org.apache.hadoop.hdfs.tools.GetConf$1@341b80b2]
java.lang.Exception
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1842)
	at org.apache.hadoop.hdfs.tools.GetConf.run(GetConf.java:344)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
	at org.apache.hadoop.hdfs.tools.GetConf.main(GetConf.java:361)
Starting resourcemanager
Starting nodemanagers
localhost: Authorized Use Only. Transactions may be monitored.
localhost: By continuing past this point, you expressly consent to this monitoring.
```

**Comment by smclinden** [comment]
I figured it out after turning on DEBUG logging in Hadoop. I'm running Hadoop 3.3.0 and in order for TheHive to use hdfs I had to manually create "/thehive" and change the ownership to "thehive". Then I was able to create an observable of type "File".

**Comment by qcmatt** [comment]
I had this same issue.

For clarification on the above, this is what I did to "fix" things:

`su - hadoop
cd /opt/hadoop
bin/hdfs dfs -mkdir /thehive
bin/hdfs dfs -chown thehive /thehive
`

Not sure if this is right, but it's what I did to get stuff working
