### ISSUE TITLE
[Bug]/Unable to get MISP organisation

### ISSUE THREAD

**Issue by ghazi0** [TheHive-Project/TheHive#1758]
Unable to get MISP organisation
 MISP server MISP is inaccessible
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |Ubuntu,
| OS version (client)       | 10,
| TheHive version / git hash   | 4.0.4-1
| Package Type              | Binary, 
| Browser type & version    | chrome

### Problem Description

Good morning all
I have a synchronization problem with a misp instance although the integration is enable and green.
Below is an extract of the error.
I NEED YOUR SUPPORT AND THANKS

![image](https://user-images.githubusercontent.com/32374417/105494831-a877df00-5cbb-11eb-8227-bbc0862c4caf.png)

### Complementary information

2021-01-22 13:02:17,926 [ERROR] from org.thp.thehive.connector.misp.services.MispImportSrv in application-akka.actor.default-dispatcher-16 [|] Unable to get MISP organisation
org.thp.scalligraph.InternalError: MISP server misp is inaccessible
	at org.thp.misp.client.MispClient.currentOrganisationName(MispClient.scala:46)
	at org.thp.thehive.connector.misp.services.MispImportSrv.syncMispEvents(MispImportSrv.scala:382)
	at org.thp.thehive.connector.misp.services.MispActor$$anonfun$receive$2.$anonfun$applyOrElse$5(MispActor.scala:37)
	at org.thp.thehive.connector.misp.services.MispActor$$anonfun$receive$2.$anonfun$applyOrElse$5$adapted(MispActor.scala:36)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at org.thp.thehive.connector.misp.services.MispActor$$anonfun$receive$2.applyOrElse(MispActor.scala:36)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at org.thp.thehive.connector.misp.services.MispActor.aroundReceive(MispActor.scala:13)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((/description,List(JsonValidationError(List(error.expected.jsstring),WrappedArray())))))
	at play.api.libs.json.JsReadable.$anonfun$as$2(JsReadable.scala:25)
	at play.api.libs.json.JsError.fold(JsResult.scala:66)
	at play.api.libs.json.JsReadable.as(JsReadable.scala:24)
	at play.api.libs.json.JsReadable.as$(JsReadable.scala:23)
	at play.api.libs.json.JsDefined.as(JsLookup.scala:188)
	at org.thp.misp.client.MispClient.$anonfun$getOrganisation$2(MispClient.scala:144)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	... 4 common frames omitted

**Comment by To-om** [comment]
It seems that the field "description" is not mandatory in MISP organisation. I fix that in TheHive
