### ISSUE TITLE
[Bug] HEAD / returned 404  org.thp.scalligraph.NotFoundError: /

### ISSUE THREAD

**Issue by okidor** [TheHive-Project/TheHive#1780]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RHEL 7
| OS version (client)       | N.A.
| TheHive version / git hash   | 4.0.4-1
| Package Type              | Binary
| Browser type & version    | N.A.

### Problem Description
After startup, thehive spam logs with the following error every 5 seconds:

from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-17 - HEAD / returned 404
org.thp.scalligraph.NotFoundError: /
        at org.thp.scalligraph.ScalligraphRouter$$anon$3.invokeBlock(ScalligraphRouter.scala:89)
        at org.thp.scalligraph.ScalligraphRouter$$anon$3.invokeBlock(ScalligraphRouter.scala:87)
        at org.thp.scalligraph.auth.AuthSrvWithActionFunction$$anon$1.$anonfun$invokeBlock$1(AuthSrv.scala:90)
        at scala.Option.fold(Option.scala:251)
        at org.thp.scalligraph.auth.AuthSrvWithActionFunction$$anon$1.invokeBlock(AuthSrv.scala:90)
        at org.thp.scalligraph.auth.AuthSrvWithActionFunction$$anon$1.invokeBlock(AuthSrv.scala:87)
        at org.thp.scalligraph.auth.BasicAuthSrv$$anon$1.$anonfun$invokeBlock$1(BasicAuthSrv.scala:54)
        at scala.Option.fold(Option.scala:251)
        at org.thp.scalligraph.auth.BasicAuthSrv$$anon$1.invokeBlock(BasicAuthSrv.scala:54)
        at org.thp.scalligraph.auth.BasicAuthSrv$$anon$1.invokeBlock(BasicAuthSrv.scala:52)
        at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.$anonfun$invokeBlock$1(SessionAuthSrv.scala:95)
        at scala.Option.fold(Option.scala:251)
        at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.invokeBlock(SessionAuthSrv.scala:95)
        at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.invokeBlock(SessionAuthSrv.scala:92)
        at org.thp.scalligraph.ScalligraphRouter$$anonfun$2.$anonfun$applyOrElse$2(ScalligraphRouter.scala:100)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:441)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:439)
        at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:379)
        at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:168)
        at scala.util.Try$.apply(Try.scala:213)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:168)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:199)
        at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:417)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$2(ContextPropagatingDisptacher.scala:56)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.thp.scalligraph.DiagnosticContext$$anon$2.withContext(ContextPropagatingDisptacher.scala:75)
        at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$1(ContextPropagatingDisptacher.scala:56)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPollAndExec(ForkJoinPool.java:977)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1605)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

### Steps to Reproduce
1. start thehive

### Possible Solutions
It's probably a misconfiguration, but as the error is not clear i can't find what's wrong.

### Complementary information
Port is listening, api calls work, i can curl the index.html page

**Comment by okidor** [comment]
So, I found out that this error is caused by a VIP that is configured to check that the service is running.
To do so, it does a HTTP HEAD request on /

This wasn't causing an issue on thehive 3 though.

**Comment by nadouani** [comment]
The issues doesn't seem to come from the binaries then. The HTTP HEAD on / is not allowed.

**Comment by nadouani** [comment]
check `GET /api/status` or `GET /api/health`

**Comment by okidor** [comment]
Hello and thank you for your answer.

I understand that the url is not correct and the correct endpoint should be used. But is it normal that the error is not catched ? (stacktrace is printed)
