### ISSUE TITLE
[Bug] TheHive can't execute Analyser on multi-organization Cortex

### ISSUE THREAD

**Issue by EulogyMondata** [TheHive-Project/TheHive#1795]
#[Bug] TheHive can't execute Analyser on multi-organization Cortex

When we have multi organizations connected to Cortex from TheHive. Only the first organization connection will be able to execute the Analyser to Cortex.

## Expected behavior

We need to connect Thehive to multi-organization Cortex for differents Analyser environnements variables for the same Analyser.   The Analyser needed may be differents between organization too.

##Complementary information

### TheHive cortex config

```bash
## CORTEX configuration
# More information at https://github.com/TheHive-Project/TheHiveDocs/TheHive4/Administration/Connectors.md
# Enable Cortex connector
play.modules.enabled += org.thp.thehive.connector.cortex.CortexModule
cortex {
 servers: [
#   {
#     name: "local"                # Cortex name
#     url: "http://localhost:9001" # URL of Cortex instance
#     auth {
#       type: "bearer"
#       key: "keyorgmmm"                 # Cortex API key
#     }
     # wsConfig {}                  # HTTP client configuration (SSL and proxy)
#   }
   {
     name: "organizationTest"                # Cortex name
     url: "http://localhost:9001" # URL of Cortex instance
     auth {
       type: "bearer"
       key: "keyorgnanizationtestxxx"                 # Cortex API key
     }
     includedTheHiveOrganisations = ["organizationTest"]
     # wsConfig {}                  # HTTP client configuration (SSL and proxy)
    },
    {
     name: "Mondata"                # Cortex name
     url: "http://localhost:9001" # URL of Cortex instance
     auth {
       type: "bearer"
       key: "keymondataxxx"                 # Cortex API key
     }
     includedTheHiveOrganisations = ["Mondata"]
     # wsConfig {}                  # HTTP client configuration (SSL and proxy)
   }
 ]
}
```

![Capture d’écran 2021-02-09 092827](https://user-images.githubusercontent.com/69516294/107380382-d2067800-6abb-11eb-8dae-d376735bf6d1.png)
![Capture d’écran 2021-02-09 093627](https://user-images.githubusercontent.com/69516294/107380392-d468d200-6abb-11eb-80ca-a2c419b1b984.png)
![Capture d’écran 2021-02-09 094213](https://user-images.githubusercontent.com/69516294/107380396-d6329580-6abb-11eb-8050-11da3bcdace3.png)

### Work environment
- Server OS: Ubuntu 20.04
 - Browse type and version: Edge Chrominiom And Chrome
- Cortex version: 3.1.0-1
- TheHive version: 4.0.2-1

 - Cortex Analyzer/Responder name: [All]
- Cortex Analyzer/Responder version: [All]

### Additional context

If we switch the Cortex Connexion, then Mondata can initiate Analyser, but not the organizationTest. 

P.S. I post this issue to Cortex repo also, but no respond til then. I need answers or a clue to solve my problem. I don't know if it's a Cortex or a TheHive issue.

**Comment by EulogyMondata** [comment]
Hello everyone!

Can I have a clue about that problem. Because we still stock with this, and we can't use Analyzers & Responders for what we need.

So :

1 - It's a bug, and that may be fix really quick.
2 - It's a bug, but we don't aspect to fix it really soon.
3 - That feature is not supported but will be soon.
4 - That feature is not supported and will not  or not soon.
5 - That just a miss configuration and I need to change something in my setup. 

Can you please help me!

Thank you!

**Comment by nadouani** [comment]
@EulogyMondata please share any logs related to the error. We don't know what happens exactly without any log or error description

**Comment by EulogyMondata** [comment]
This is the log while we doing requests

- first organization with succesfull request

```bash
2021-02-22 15:05:11,009 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217765 [0000cd46|] 10.200.75.241 POST /api/v1/query?name=observables.count took 10ms and returned 200 1 bytes
2021-02-22 15:05:11,022 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217767 [0000cd47|] 10.200.75.241 GET /api/connector/cortex/analyzer?range=all took 23ms and returned 200 834 bytes
2021-02-22 15:05:12,095 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217759 [0000cd40|] 10.200.75.241 GET /api/case/~286724160/links took 3947ms and returned 200 24747 bytes
2021-02-22 15:05:25,785 [INFO] from org.thp.thehive.connector.cortex.services.CortexActor in application-akka.actor.default-dispatcher-217747 [|] CortexActor received job or action (~332968040, FehGyncB-7T8o_bfEL5X, organizationTest) to check, added to List()
2021-02-22 15:05:25,786 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217747 [0000cd48|] 10.200.75.241 POST /api/connector/cortex/job took 518ms and returned 201 331 bytes
2021-02-22 15:05:25,936 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217759 [0000cd33|] 10.200.75.241 GET /api/stream/42aRR3GTxPXSoM2liRCF took 26628ms and returned 200 1162 bytes
2021-02-22 15:05:31,089 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217768 [0000cd4a|] 10.200.75.241 GET /index.html took 0ms and returned 200 1191 bytes
2021-02-22 15:05:31,342 [INFO] from org.thp.thehive.connector.cortex.services.CortexActor in application-akka.actor.default-dispatcher-217759 [|] Job FehGyncB-7T8o_bfEL5X in cortex organizationTest has finished with status Success, updating job ~332968040
2021-02-22 15:05:31,553 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217759 [0000cd49|] 10.200.75.241 GET /api/stream/42aRR3GTxPXSoM2liRCF took 5555ms and returned 200 871 bytes
2021-02-22 15:05:31,631 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217747 [0000cd4b|] 10.200.75.241 POST /api/v1/query?name=observables took 14ms and returned 200
```

- second organization with failed request
```bash
2021-02-22 15:08:00,081 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217747 [0000cd63|] 10.200.75.241 POST /api/v1/query?name=cases took 19ms and returned 200
2021-02-22 15:08:00,094 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217759 [0000cd61|] 10.200.75.241 POST /api/v1/query?name=case-status-stats took 36ms and returned 200 20 bytes
2021-02-22 15:08:00,096 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217775 [0000cd64|] 10.200.75.241 POST /api/v1/query?name=cases.count took 33ms and returned 200 1 bytes
2021-02-22 15:08:00,098 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217767 [0000cd5b|] 10.200.75.241 POST /api/v1/query took 127ms and returned 200 1455 bytes
2021-02-22 15:08:00,158 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217757 [0000cd5e|] 10.200.75.241 POST /api/v1/query?name=my-tasks.stats took 162ms and returned 200 1 bytes
2021-02-22 15:08:00,168 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217772 [0000cd5d|] 10.200.75.241 POST /api/v0/query took 177ms and returned 200 11529 bytes
2021-02-22 15:08:00,283 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217768 [0000cd65|] 10.200.75.241 GET /api/flow?count=10&rootId=any took 206ms and returned 200 8935 bytes
2021-02-22 15:08:00,337 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217765 [0000cd5f|] 10.200.75.241 POST /api/v1/query?name=waiting-tasks.stats took 339ms and returned 200 2 bytes
2021-02-22 15:08:01,198 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217768 [0000cd66|] 10.200.75.241 GET /index.html took 0ms and returned 200 1191 bytes
2021-02-22 15:08:12,051 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217757 [0000cd67|] 10.200.75.241 POST /api/v1/query?name=get-case-~81993960 took 8ms and returned 200
2021-02-22 15:08:12,185 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217747 [0000cd69|] 10.200.75.241 POST /api/v1/query?name=observable-stats-~81993960 took 10ms and returned 200 1 bytes
2021-02-22 15:08:12,188 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217775 [0000cd6a|] 10.200.75.241 POST /api/v1/query?name=case-attachments took 13ms and returned 200
2021-02-22 15:08:12,205 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217768 [0000cd6b|] 10.200.75.241 POST /api/v1/query?name=alert-stats-~81993960 took 30ms and returned 200 1 bytes
2021-02-22 15:08:12,213 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217767 [0000cd6d|] 10.200.75.241 GET /api/case/~81993960/links took 24ms and returned 200 2 bytes
2021-02-22 15:08:12,261 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217772 [0000cd68|] 10.200.75.241 POST /api/v1/query?name=task-stats-~81993960 took 93ms and returned 200 2 bytes
2021-02-22 15:08:12,268 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217759 [0000cd6c|] 10.200.75.241 POST /api/v1/query?name=case-attachments.count took 93ms and returned 200 1 bytes
2021-02-22 15:08:12,391 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217772 [0000cd6f|] 10.200.75.241 GET /api/flow?count=10&rootId=~81993960 took 103ms and returned 200 8935 bytes
2021-02-22 15:08:12,437 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217772 [0000cd6e|] 10.200.75.241 POST /api/v1/query?name=case-actions took 247ms and returned 200 482366 bytes
2021-02-22 15:08:14,059 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217772 [0000cd70|] 10.200.75.241 POST /api/v1/query?name=case-tasks took 6ms and returned 200
2021-02-22 15:08:14,152 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217767 [0000cd71|] 10.200.75.241 POST /api/v1/query?name=case-tasks.count took 100ms and returned 200 2 bytes
2021-02-22 15:08:15,095 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217767 [0000cd72|] 10.200.75.241 POST /api/v1/query?name=observables took 6ms and returned 200
2021-02-22 15:08:15,098 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217757 [0000cd73|] 10.200.75.241 POST /api/v1/query?name=observables.count took 10ms and returned 200 1 bytes
2021-02-22 15:08:20,736 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217747 [0000cd74|] 10.200.75.241 GET /api/case/artifact/~213450880 took 10ms and returned 200 489 bytes
2021-02-22 15:08:20,826 [WARN] from org.thp.scalligraph.query.InputFilter in application-akka.actor.default-dispatcher-217775 [0000cd78|] Use of filter {"_parent": "FObject(Map(_type -> FString(case_artifact), _query -> FObject(Map(_id -> FString(~213450880)))))"} is deprecated. Please use {"_field": "_parent", "_value": "FObject(Map(_type -> FString(case_artifact), _query -> FObject(Map(_id -> FString(~213450880)))))"}
2021-02-22 15:08:20,832 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217759 [0000cd75|] 10.200.75.241 GET /api/case/artifact/~213450880/similar?range=all&sort=-startDate took 31ms and returned 200 2 bytes
2021-02-22 15:08:20,834 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217765 [0000cd76|] 10.200.75.241 POST /api/v1/query?name=case-observable-actions took 31ms and returned 200 2 bytes
2021-02-22 15:08:20,834 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217772 [0000cd77|] 10.200.75.241 GET /api/case/~81993960/observable/~213450880/shares took 12ms and returned 200 2 bytes
2021-02-22 15:08:20,909 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217775 [0000cd78|] 10.200.75.241 POST /api/connector/cortex/job/_search?range=0-200&sort=-startDate took 87ms and returned 200
2021-02-22 15:08:31,230 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217747 [0000cd79|] 10.200.75.241 GET /index.html took 0ms and returned 200 1191 bytes
2021-02-22 15:08:31,800 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217768 [0000cd54|] 10.200.75.241 GET /api/stream/42aRR3GTxPXSoM2liRCF took 60019ms and returned 200 2 bytes
2021-02-22 15:08:33,693 [WARN] from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-217759 [|] POST /api/connector/cortex/job returned 404
org.thp.scalligraph.NotFoundError: Cortex organizationTest not found
        at org.thp.thehive.connector.cortex.services.JobSrv.$anonfun$submit$2(JobSrv.scala:77)
        at scala.Option.fold(Option.scala:251)
        at org.thp.thehive.connector.cortex.services.JobSrv.submit(JobSrv.scala:77)
        at org.thp.thehive.connector.cortex.controllers.v0.JobCtrl.$anonfun$create$6(JobCtrl.scala:66)
        at scala.util.Success.fold(Try.scala:271)
        at org.thp.thehive.connector.cortex.controllers.v0.JobCtrl.$anonfun$create$1(JobCtrl.scala:63)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$asyncAuth$3(Entrypoint.scala:107)
        at org.scalactic.Good.fold(Or.scala:1229)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$asyncAuth$2(Entrypoint.scala:107)
        at org.thp.scalligraph.DiagnosticContext$.$anonfun$withRequest$2(ContextPropagatingDisptacher.scala:99)
        at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:106)
        at org.thp.scalligraph.DiagnosticContext$.withRequest(ContextPropagatingDisptacher.scala:97)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$asyncAuth$1(Entrypoint.scala:107)
        at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.$anonfun$invokeBlock$2(SessionAuthSrv.scala:97)
        at scala.Option.fold(Option.scala:251)
        at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.invokeBlock(SessionAuthSrv.scala:95)
        at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.invokeBlock(SessionAuthSrv.scala:92)
        at play.api.mvc.ActionBuilder$$anon$10.$anonfun$invokeBlock$2(Action.scala:408)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:441)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:439)
        at play.api.mvc.ActionBuilder$$anon$10.invokeBlock(Action.scala:408)
        at play.api.mvc.ActionBuilder$$anon$10.invokeBlock(Action.scala:404)
        at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:379)
        at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:168)
        at scala.util.Try$.apply(Try.scala:213)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:168)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:200)
        at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:418)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$2(ContextPropagatingDisptacher.scala:56)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.thp.scalligraph.DiagnosticContext$.$anonfun$withDiagnosticContext$2(ContextPropagatingDisptacher.scala:91)
        at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:106)
        at org.thp.scalligraph.DiagnosticContext$.withDiagnosticContext(ContextPropagatingDisptacher.scala:89)
        at org.thp.scalligraph.DiagnosticContext$$anon$2.withContext(ContextPropagatingDisptacher.scala:74)
        at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$1(ContextPropagatingDisptacher.scala:56)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-02-22 15:08:59,138 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217747 [0000cd7c|] 10.200.75.241 GET /api/status took 0ms and returned 200 452 bytes
2021-02-22 15:09:00,006 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217747 [0000cd7d|] 10.200.75.241 GET /api/status took 1ms and returned 200 452 bytes
2021-02-22 15:09:01,257 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217759 [0000cd7e|] 10.200.75.241 GET /index.html took 1ms and returned 200 1191 bytes
2021-02-22 15:09:31,285 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217747 [0000cd7f|] 10.200.75.241 GET /index.html took 1ms and returned 200 1191 bytes
2021-02-22 15:09:31,870 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-217765 [0000cd7a|] 10.200.75.241 GET /api/stream/l1bK1fHCzl9virs9jf0z took 60018ms and returned 200 2 bytes
```
While request on Mondata (the second organization), we've got "Cortex organizationTest not found"

```bash
2021-02-22 15:08:33,693 [WARN] from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-217759 [|] POST /api/connector/cortex/job returned 404
org.thp.scalligraph.NotFoundError: Cortex organizationTest not found
        at org.thp.thehive.connector.cortex.services.JobSrv.$anonfun$submit$2(JobSrv.scala:77)
        at scala.Option.fold(Option.scala:251)
```

And like I said if we switch the configuration, the Working organization switch too. 

Is it enough or you need more info?

Thanks for your help!
