### ISSUE TITLE
[Bug] Unable to create alert from MISP event 

### ISSUE THREAD

**Issue by Tyrell20** [TheHive-Project/TheHive#1811]
## Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat 7.9
| TheHive version / git hash   | Version: 4.0.5-1
| Package Type              | RPM

### Problem Description
I have problem with MISP and TheHive. When I published event on MISP, TheHive get nothing.

### Configuration
 play.modules.enabled += org.thp.thehive.connector.misp.MispModule
 misp {
  interval: 1 hour
  servers: [
    {
      name = "MISP-SERVER"            # MISP name
      url = "https://hostname/" # URL or MISP
      auth {
        type = key
        key = "auth_key"             # MISP API key
      }
  # tags that must be automatically added to the case corresponding to the imported event
    tags = ["misp","from-misp-event","test"]
    # case template
    caseTemplate = "MISP-EVENT"

#      wsConfig {}               # HTTP client configuration (SSL and proxy)
    # filters:
#    max-attributes = 1000
#    max-size = 1 MiB
    max-age = 7 days
    exclusion {
    organisation = ["org1_example", "org2_example", "org3_example", "org4_example", "org5_example"]
#    tags = ["tag1", "tag2"]
    }
#    whitelist.tags = ["whitelist-tag1", "whitelist-tag2"]

   }
  ]
 # Check remote TheHive status time interval
  statusCheckInterval = 1 minute
}

### Complementary information
application.log:
2021-03-02 17:26:25,466 [WARN] from org.thp.thehive.connector.misp.services.MispImportSrv in application-akka.actor.default-dispatcher-12 [|030236fc] Unable$
akka.stream.IOOperationIncompleteException: IO operation was stopped unexpectedly after 0 bytes because of java.util.concurrent.TimeoutException: Request ti$
        at akka.stream.impl.io.FileOutputStage$$anon$1.onUpstreamFailure(FileOutputStage.scala:73)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:524)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
        at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:56)
        at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:52)
        at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnError.execute(ActorGraphInterpreter.scala:77)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Request timeout to **MISP_HOSTNAME/**MISP_IP**:443 after 120000 ms
        at play.shaded.ahc.org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
        at play.shaded.ahc.org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
        at play.shaded.ahc.io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680)
        at play.shaded.ahc.io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755)
        at play.shaded.ahc.io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483)
        at play.shaded.ahc.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 common frames omitted

2021-03-02 17:26:25,478 [ERROR] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-12 [|030236fc] uncaught error, not retrying
akka.stream.IOOperationIncompleteException: IO operation was stopped unexpectedly after 0 bytes because of java.util.concurrent.TimeoutException: Request ti$
        at akka.stream.impl.io.FileOutputStage$$anon$1.onUpstreamFailure(FileOutputStage.scala:73)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:524)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
        at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:56)
        at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:52)
        at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnError.execute(ActorGraphInterpreter.scala:77)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Request timeout to **MISP_HOSTNAME/**MISP_IP**:443 after 120000 ms
        at play.shaded.ahc.org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
        at play.shaded.ahc.org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
        at play.shaded.ahc.io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680)
        at play.shaded.ahc.io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755)
        at play.shaded.ahc.io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483)

**Comment by nadouani** [comment]
Hello, this sounds like a troubleshooting issue, please ask the question on https://chat.thehive-project.org

Thanks

**Comment by nadouani** [comment]
```
Caused by: java.util.concurrent.TimeoutException: Request timeout to **MISP_HOSTNAME/**MISP_IP**:443 after 120000 ms
```

Your configuration file is completely broken. Please remove commented code to make sure you have right opening and closing brakets.

**Comment by Tyrell20** [comment]
**MISP_HOSTNAME/**MISP_IP** is 

> ```
> Caused by: java.util.concurrent.TimeoutException: Request timeout to **MISP_HOSTNAME/**MISP_IP**:443 after 120000 ms
> ```
> 
> Your configuration file is completely broken. Please remove commented code to make sure you have right opening and closing brakets.

**MISP_HOSTNAME/**MISP_IP** is only a placeholder substituted to the real values on the log files, I cannot post here the real hostname and IP address of my MISP instance.
Anyway, I will ask on https://chat.thehive-project.org.
Thank you
