### ISSUE TITLE
[Bug] Delete case with 2.9k observables 

### ISSUE THREAD

**Issue by mihdim777** [TheHive-Project/TheHive#1886]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4.1.1-1
| Package Type              | DEB

### Problem Description
Deleting a case with 2.9k observables, fail.

### Steps to Reproduce
1. Import an alert from MISP
2. Create case and observables
3. Try to delete the case

2021-03-24 12:03:51,195 [ERROR] from org.thp.scalligraph.models.Database in application-akka.actor.default-dispatcher-14 [0000017a|38a49b33] Exception raised, rollback (Could not commit transaction due to exception during persistence)
2021-03-24 12:03:51,199 [ERROR] from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-14 [0000017a|] Internal error
com.sleepycat.je.LockTimeoutException: (JE 18.3.12) Lock expired. Locker 109995787 42908_application-akka.actor.default-dispatcher-13_Txn: waited for lock on database=graphindex LockAddr:1817772313 LSN=0xf/0x38124b type=WRITE grant=WAIT_NEW timeoutMillis=500 startTime=1616587430677 endTime=1616587431177
Owners: [LockInfo locker="21528270 41736_application-akka.actor.default-dispatcher-10_Txn" type="READ"]
Waiters: [LockInfo locker="109995787 42908_application-akka.actor.default-dispatcher-13_Txn" type="WRITE"]

        at com.sleepycat.je.txn.LockManager.makeTimeoutException(LockManager.java:1154)
        at com.sleepycat.je.txn.LockManager.waitForLock(LockManager.java:621)
        at com.sleepycat.je.txn.LockManager.lock(LockManager.java:353)
        at com.sleepycat.je.txn.Txn.lockInternal(Txn.java:545)
        at com.sleepycat.je.txn.Locker.lock(Locker.java:496)
        at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:3674)
        at com.sleepycat.je.dbi.CursorImpl.deleteCurrentRecord(CursorImpl.java:917)
        at com.sleepycat.je.Cursor.deleteNoNotify(Cursor.java:2370)
        at com.sleepycat.je.Cursor.deleteNotify(Cursor.java:2311)
        at com.sleepycat.je.Cursor.deleteInternal(Cursor.java:2220)
        at com.sleepycat.je.Database.deleteInternal(Database.java:1229)
        at com.sleepycat.je.Database.delete(Database.java:1185)
        at com.sleepycat.je.Database.delete(Database.java:1291)
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore.delete(BerkeleyJEKeyValueStore.java:248)
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.mutateMany(BerkeleyJEStoreManager.java:217)
        at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreManagerAdapter.mutateMany(OrderedKeyValueStoreManagerAdapter.java:128)
        at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:94)
        at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:91)
        at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:68)
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:54)
        at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.persist(CacheTransaction.java:91)
        at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.flushInternal(CacheTransaction.java:139)
        at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.commit(CacheTransaction.java:196)
        at org.janusgraph.diskstorage.BackendTransaction.commitStorage(BackendTransaction.java:133)
        at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:747)
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1438)
        at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsTransaction$1.doCommit(JanusGraphBlueprintsTransaction.java:185)
        at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:104)
        at org.thp.scalligraph.janus.JanusDatabase.$anonfun$tryTransaction$5(JanusDatabase.scala:234)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at org.thp.scalligraph.janus.JanusDatabase.$anonfun$tryTransaction$8(JanusDatabase.scala:262)
        at org.thp.scalligraph.utils.DelayRetry$$anonfun$withTry$1.$anonfun$applyOrElse$8(Retry.scala:93)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$2(ContextPropagatingDisptacher.scala:56)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.thp.scalligraph.DiagnosticContext$.$anonfun$withDiagnosticContext$2(ContextPropagatingDisptacher.scala:91)
        at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:106)
        at org.thp.scalligraph.DiagnosticContext$.withDiagnosticContext(ContextPropagatingDisptacher.scala:89)
        at org.thp.scalligraph.DiagnosticContext$$anon$2.withContext(ContextPropagatingDisptacher.scala:74)
        at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$1(ContextPropagatingDisptacher.scala:56)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2021-03-24 12:03:51,200 [WARN] from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-14 [0000017a|] DELETE /api/case/~172613768/force returned 500
org.janusgraph.core.JanusGraphException: Could not commit transaction due to exception during persistence
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1449)
        at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsTransaction$1.doCommit(JanusGraphBlueprintsTransaction.java:185)
        at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:104)
        at org.thp.scalligraph.janus.JanusDatabase.$anonfun$tryTransaction$5(JanusDatabase.scala:234)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at org.thp.scalligraph.janus.JanusDatabase.$anonfun$tryTransaction$8(JanusDatabase.scala:262)
        at org.thp.scalligraph.utils.DelayRetry$$anonfun$withTry$1.$anonfun$applyOrElse$8(Retry.scala:93)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$2(ContextPropagatingDisptacher.scala:56)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.thp.scalligraph.DiagnosticContext$.$anonfun$withDiagnosticContext$2(ContextPropagatingDisptacher.scala:91)
        at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:106)
        at org.thp.scalligraph.DiagnosticContext$.withDiagnosticContext(ContextPropagatingDisptacher.scala:89)
        at org.thp.scalligraph.DiagnosticContext$$anon$2.withContext(ContextPropagatingDisptacher.scala:74)
        at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$1(ContextPropagatingDisptacher.scala:56)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:56)
        at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.persist(CacheTransaction.java:91)
        at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.flushInternal(CacheTransaction.java:139)
        at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.commit(CacheTransaction.java:196)
        at org.janusgraph.diskstorage.BackendTransaction.commitStorage(BackendTransaction.java:133)
        at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:747)
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1438)
        ... 28 common frames omitted
Caused by: org.janusgraph.diskstorage.PermanentBackendException: Permanent failure in storage backend
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore.delete(BerkeleyJEKeyValueStore.java:253)
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.mutateMany(BerkeleyJEStoreManager.java:217)
        at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreManagerAdapter.mutateMany(OrderedKeyValueStoreManagerAdapter.java:128)
        at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:94)
        at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:91)
        at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:68)
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:54)
        ... 34 common frames omitted
Caused by: com.sleepycat.je.LockTimeoutException: (JE 18.3.12) Lock expired. Locker 109995787 42908_application-akka.actor.default-dispatcher-13_Txn: waited for lock on database=graphindex LockAddr:1817772313 LSN=0xf/0x38124b type=WRITE grant=WAIT_NEW timeoutMillis=500 startTime=1616587430677 endTime=1616587431177
Owners: [LockInfo locker="21528270 41736_application-akka.actor.default-dispatcher-10_Txn" type="READ"]
Waiters: [LockInfo locker="109995787 42908_application-akka.actor.default-dispatcher-13_Txn" type="WRITE"]

        at com.sleepycat.je.txn.LockManager.makeTimeoutException(LockManager.java:1154)
        at com.sleepycat.je.txn.LockManager.waitForLock(LockManager.java:621)
        at com.sleepycat.je.txn.LockManager.lock(LockManager.java:353)
        at com.sleepycat.je.txn.Txn.lockInternal(Txn.java:545)
        at com.sleepycat.je.txn.Locker.lock(Locker.java:496)
        at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:3674)
        at com.sleepycat.je.dbi.CursorImpl.deleteCurrentRecord(CursorImpl.java:917)
        at com.sleepycat.je.Cursor.deleteNoNotify(Cursor.java:2370)
        at com.sleepycat.je.Cursor.deleteNotify(Cursor.java:2311)
        at com.sleepycat.je.Cursor.deleteInternal(Cursor.java:2220)
        at com.sleepycat.je.Database.deleteInternal(Database.java:1229)
        at com.sleepycat.je.Database.delete(Database.java:1185)
        at com.sleepycat.je.Database.delete(Database.java:1291)
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore.delete(BerkeleyJEKeyValueStore.java:248)
        ... 40 common frames omitted
2021-03-24 12:03:51,200 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-14 [0000017a|] 84.117.28.254 DELETE /api/case/~172613768/force took 27812ms and returned 500 555 bytes

**Comment by mihdim777** [comment]
After restarting the application, it worked to delete the case. No deadlocks.
