### ISSUE TITLE
[Question] Minio The specified bucket does not exist

### ISSUE THREAD

**Issue by Canon88** [TheHive-Project/TheHive#1916]
### Request Type

Question

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| TheHive version / git hash   | 4.1.1
| Package Type              | DEB

### Question

I followed the documentation for the deployment of TheHive cluster. I have a problem, I have configured the `Minio` service according to the documentation and everything works fine. But when I submit an attachment through a Case on TheHive. Below is the relevant TheHive log, I hope it can help me to solve this problem. Thank you very much.

**TheHive Logs**
```
2021-03-31 15:10:37,738 [ERROR] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-23 [00000099|32be21a0] uncaught error, not retrying
akka.stream.alpakka.s3.S3Exception: The specified bucket does not exist
	at akka.stream.alpakka.s3.S3Exception$.apply(S3Exception.scala:69)
	at akka.stream.alpakka.s3.impl.S3Stream$.$anonfun$unmarshalError$1(S3Stream.scala:246)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transform(FastFuture.scala:84)
	at scala.concurrent.Future.map(Future.scala:292)
	at scala.concurrent.Future.map$(Future.scala:292)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.map(FastFuture.scala:77)
	at akka.stream.alpakka.s3.impl.S3Stream$.unmarshalError(S3Stream.scala:245)
	at akka.stream.alpakka.s3.impl.S3Stream$.$anonfun$initiateMultipartUpload$2(S3Stream.scala:469)
	at akka.stream.impl.fusing.Map$$anon$1.onPush(Ops.scala:53)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-03-31 15:10:37,738 [ERROR] from org.thp.scalligraph.models.Database in application-akka.actor.default-dispatcher-23 [00000099|32be21a0] Exception raised, rollback (The specified bucket does not exist)
2021-03-31 15:10:37,738 [ERROR] from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-23 [00000099|] Internal error
akka.stream.alpakka.s3.S3Exception: The specified bucket does not exist
	at akka.stream.alpakka.s3.S3Exception$.apply(S3Exception.scala:69)
	at akka.stream.alpakka.s3.impl.S3Stream$.$anonfun$unmarshalError$1(S3Stream.scala:246)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transform(FastFuture.scala:84)
	at scala.concurrent.Future.map(Future.scala:292)
	at scala.concurrent.Future.map$(Future.scala:292)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.map(FastFuture.scala:77)
	at akka.stream.alpakka.s3.impl.S3Stream$.unmarshalError(S3Stream.scala:245)
	at akka.stream.alpakka.s3.impl.S3Stream$.$anonfun$initiateMultipartUpload$2(S3Stream.scala:469)
	at akka.stream.impl.fusing.Map$$anon$1.onPush(Ops.scala:53)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-03-31 15:10:37,738 [WARN] from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-23 [00000099|] POST /api/case/task/~8208/log returned 500
akka.stream.alpakka.s3.S3Exception: The specified bucket does not exist
	at akka.stream.alpakka.s3.S3Exception$.apply(S3Exception.scala:69)
	at akka.stream.alpakka.s3.impl.S3Stream$.$anonfun$unmarshalError$1(S3Stream.scala:246)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transform(FastFuture.scala:84)
	at scala.concurrent.Future.map(Future.scala:292)
	at scala.concurrent.Future.map$(Future.scala:292)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.map(FastFuture.scala:77)
	at akka.stream.alpakka.s3.impl.S3Stream$.unmarshalError(S3Stream.scala:245)
	at akka.stream.alpakka.s3.impl.S3Stream$.$anonfun$initiateMultipartUpload$2(S3Stream.scala:469)
	at akka.stream.impl.fusing.Map$$anon$1.onPush(Ops.scala:53)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-03-31 15:10:37,738 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-26 [00000099|] 192.168.199.4 POST /api/case/task/~8208/log took 78ms and returned 500 93 bytes
```

**TheHive Config**
```
## Attachment storage configuration
storage {
  ## Local filesystem
  # provider: localfs
  # localfs.location: /opt/thp/thehive/files

  ## Hadoop filesystem (HDFS)
  // provider: hdfs
  // hdfs {
  //   root: "hdfs://localhost:10000" # namenode server hostname
  //   location: "/thehive"           # location inside HDFS
  //   username: thehive              # file owner
  // }

  # S3 configuration by Canon 2021.03.28
  provider: s3
  s3 {
    bucket = "thehive"
    readTimeout = 1 minute
    writeTimeout = 1 minute
    chunkSize = 1 MB
    endpoint = "http://minio1:9100"
    accessKey = "admin"
    secretKey = "HappyHunting"
    region = "us-east-1"
  }
}
```

**TheHive Upload screenshot**
![image](https://user-images.githubusercontent.com/19372121/113106069-e867bf00-9234-11eb-9250-9f7cd88aef17.png)

**Minio screenshot**
![image](https://user-images.githubusercontent.com/19372121/113106357-42688480-9235-11eb-98bd-b269c700435d.png)

**Comment by jeromeleonard** [comment]
Hello, 

One page of the documentation was not completed. You need to add the following parameter at the root of the configuration file:  `alpakka.s3.path-style-access = force`

The documentation has been updated accordingly:
- https://docs.thehive-project.org/thehive/installation-and-configuration/configuration/file-storage/
- https://docs.thehive-project.org/thehive/installation-and-configuration/architecture/3_nodes_cluster/#thehive-associated-configuration_1

Please confirm that it works well with the updated configuration.

**Comment by Canon88** [comment]
> Hello,
> 
> One page of the documentation was not completed. You need to add the following parameter at the root of the configuration file: `alpakka.s3.path-style-access = force`
> 
> The documentation has been updated accordingly:
> 
> * https://docs.thehive-project.org/thehive/installation-and-configuration/configuration/file-storage/
> * https://docs.thehive-project.org/thehive/installation-and-configuration/architecture/3_nodes_cluster/#thehive-associated-configuration_1
> 
> Please confirm that it works well with the updated configuration.

Thanks, the problem has been solved after updating the configuration.👍👍👍
