### ISSUE TITLE
[Question] TheHive add observable not work.

### ISSUE THREAD

**Issue by Canon88** [TheHive-Project/TheHive#1928]
### Request Type

Question

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| TheHive version / git hash   | 4.1.2-1
| Package Type              | DEB

### Question

I tried to add observable to Case in TheHive and it does not work properly. The error message is as follows.
![image](https://user-images.githubusercontent.com/19372121/113514599-33b9fe80-95a2-11eb-9472-bf4127346fe7.png)

```
2021-04-05 00:00:15,211 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-10 [00000078|] 192.168.199.162 GET /api/status took 2ms and returned 200 547 bytes
2021-04-05 00:01:15,079 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-26 [0000007a|] 192.168.199.162 GET /api/status took 2ms and returned 200 547 bytes
2021-04-05 00:01:15,111 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-10 [0000007b|] 192.168.199.4 GET /api/status took 2ms and returned 200 547 bytes
2021-04-05 00:01:15,238 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-25 [00000079|] 192.168.199.162 GET /api/stream/y8vhB4fq1O60dkKRoriL took 60019ms and returned 200 2 bytes
2021-04-05 00:01:55,626 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-25 [0000007d|] 192.168.199.162 GET /api/observable/type?range=all took 49ms and returned 200
2021-04-05 00:02:05,093 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-25 [0000007e|] 192.168.199.162 POST /api/v1/query?name=tags-auto-complete took 29ms and returned 200 8 bytes
2021-04-05 00:02:07,017 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-10 [0000007f|0be42d9d] An error occurs (Could not process individual retrieval call ), retrying (1)
2021-04-05 00:02:07,022 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-25 [0000007f|0be42d9d] An error occurs (Could not process individual retrieval call ), retrying (2)
2021-04-05 00:02:07,528 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-6 [|43f1d134] An error occurs (Could not process individual retrieval call ), retrying (3)
2021-04-05 00:02:08,416 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-25 [|43f1d134] An error occurs (Could not process individual retrieval call ), retrying (4)
2021-04-05 00:02:09,636 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-6 [|43f1d134] An error occurs (Could not process individual retrieval call ), retrying (5)
2021-04-05 00:02:10,736 [ERROR] from org.thp.scalligraph.models.Database in application-akka.actor.default-dispatcher-10 [0000007f|0be42d9d] Exception raised, rollback (Could not process individual retrieval call )
2021-04-05 00:02:10,739 [ERROR] from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-10 [0000007f|46d99ad8] Internal error
org.elasticsearch.client.ResponseException: method [POST], host [https://elasticsearch05:9200], URI [/thehive_observable/_search?scroll=60s], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [thehive_observable]","resource.type":"index_or_alias","resource.id":"thehive_observable","index_uuid":"_na_","index":"thehive_observable"}],"type":"index_not_found_exception","reason":"no such index [thehive_observable]","resource.type":"index_or_alias","resource.id":"thehive_observable","index_uuid":"_na_","index":"thehive_observable"},"status":404}
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
	at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.performRequest(RestElasticSearchClient.java:483)
	at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.search(RestElasticSearchClient.java:467)
	at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.search(RestElasticSearchClient.java:437)
	at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.search(RestElasticSearchClient.java:60)
	at org.janusgraph.diskstorage.es.ElasticSearchIndex.query(ElasticSearchIndex.java:1103)
	at org.janusgraph.diskstorage.indexing.IndexTransaction.queryStream(IndexTransaction.java:108)
	at org.janusgraph.diskstorage.BackendTransaction$6.call(BackendTransaction.java:416)
	at org.janusgraph.diskstorage.BackendTransaction$6.call(BackendTransaction.java:413)
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:68)
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:54)
	at org.janusgraph.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:469)
	at org.janusgraph.diskstorage.BackendTransaction.indexQuery(BackendTransaction.java:413)
	at org.janusgraph.graphdb.database.IndexSerializer.query(IndexSerializer.java:533)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx$3.lambda$null$3(StandardJanusGraphTx.java:1345)
	at org.janusgraph.graphdb.query.profile.QueryProfiler.profile(QueryProfiler.java:99)
	at org.janusgraph.graphdb.query.profile.QueryProfiler.profile(QueryProfiler.java:91)
	at org.janusgraph.graphdb.query.profile.QueryProfiler.profile(QueryProfiler.java:83)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx$3.lambda$null$4(StandardJanusGraphTx.java:1345)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx$3.lambda$execute$5(StandardJanusGraphTx.java:1344)
	at org.janusgraph.graphdb.query.QueryUtil.processIntersectingRetrievals(QueryUtil.java:359)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx$3.execute(StandardJanusGraphTx.java:1354)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx$3.execute(StandardJanusGraphTx.java:1246)
	at org.janusgraph.graphdb.query.QueryProcessor$LimitAdjustingIterator.getNewIterator(QueryProcessor.java:201)
	at org.janusgraph.graphdb.query.LimitAdjustingIterator.hasNext(LimitAdjustingIterator.java:69)
	at org.janusgraph.graphdb.query.ResultSetIterator.nextInternal(ResultSetIterator.java:55)
	at org.janusgraph.graphdb.query.ResultSetIterator.<init>(ResultSetIterator.java:45)
	at org.janusgraph.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:67)
	at org.janusgraph.graphdb.query.graph.GraphCentricQueryBuilder$1.iterator(GraphCentricQueryBuilder.java:204)
	at org.janusgraph.graphdb.query.graph.GraphCentricQueryBuilder$1.iterator(GraphCentricQueryBuilder.java:201)
	at org.thp.scalligraph.janus.strategies.JanusGraphStepAcceptNull.executeGraphCentricQuery(JanusGraphStepAcceptNull.java:131)
	at org.thp.scalligraph.janus.strategies.JanusGraphStepAcceptNull.lambda$null$1(JanusGraphStepAcceptNull.java:66)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.thp.scalligraph.janus.strategies.JanusGraphStepAcceptNull.lambda$new$2(JanusGraphStepAcceptNull.java:66)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:157)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:197)
	at org.thp.scalligraph.traversal.TraversalOps$TraversalOpsDefs.exists(TraversalOps.scala:131)
	at org.thp.thehive.services.ObservableSrv.create(ObservableSrv.scala:93)
	at org.thp.thehive.services.CaseSrv.createObservable(CaseSrv.scala:189)
	at org.thp.thehive.controllers.v0.ObservableCtrl.$anonfun$createSimpleObservableInCase$1(ObservableCtrl.scala:102)
	at org.thp.scalligraph.janus.JanusDatabase.$anonfun$tryTransaction$10(JanusDatabase.scala:259)
	at scala.util.Try$.apply(Try.scala:213)
	at org.thp.scalligraph.janus.JanusDatabase.$anonfun$tryTransaction$8(JanusDatabase.scala:259)
	at org.thp.scalligraph.utils.DelayRetry$$anonfun$withTry$1.$anonfun$applyOrElse$8(Retry.scala:93)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$2(ContextPropagatingDisptacher.scala:56)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.thp.scalligraph.DiagnosticContext$$anon$2.withContext(ContextPropagatingDisptacher.scala:75)
	at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$1(ContextPropagatingDisptacher.scala:56)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-04-05 00:02:10,739 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-10 [0000007f|] 192.168.199.162 POST /api/case/~204804288/artifact took 3764ms and returned 207 748 bytes
2021-04-05 00:02:15,117 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-24 [00000080|] 192.168.199.4 GET /api/status took 1ms and returned 200 547 bytes
2021-04-05 00:02:15,268 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-24 [0000007c|] 192.168.199.162 GET /api/stream/y8vhB4fq1O60dkKRoriL took 60014ms and returned 200 2 bytes
2021-04-05 00:02:15,283 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-10 [00000081|] 192.168.199.162 GET /api/status took 1ms and returned 200 547 bytes
```
I tested Cortex is normal, when I add analysis directly on Cortex works fine.

I checked my Elastic cluster and there is no index for thehive_observable.
![image](https://user-images.githubusercontent.com/19372121/113514644-7d0a4e00-95a2-11eb-9efc-3dde300a6db5.png)

**Comment by Canon88** [comment]
TheHive Config
```
db.janusgraph {
  storage {
    ## Cassandra configuration
    # More information at https://docs.janusgraph.org/basics/configuration-reference/#storagecql
    backend: cql
    hostname: ["th01", "th02", "th03"]
    # Cassandra authentication (if configured)
    username: "cassandra"
    password: "HappyHunting"
    cql {
      cluster-name: thp
      keyspace: thehive
    }
  }

  ## Index configuration
  index.search {
    backend: elasticsearch
    hostname: ["elasticsearch01", "elasticsearch02", "elasticsearch03", "elasticsearch04", "elasticsearch05"]
    index-name: thehive
    # auth
    elasticsearch.http.auth.type=basic
    elasticsearch.http.auth.basic.username=elastic
    elasticsearch.http.auth.basic.password=0M8pJVR1k5GDHbRxmZWU
    # ssl
    elasticsearch.ssl.enabled=true
    elasticsearch.ssl.truststore.location=/etc/thehive/truststore.jks
    elasticsearch.ssl.truststore.password=HelloWorld
  }

  ## For test only !
  # Comment the two lines below before enable Cassandra database
  ## storage.backend: berkeleyje
  ## storage.directory: /opt/thp/thehive/database
  // berkeleyje.freeDisk: 200 # disk usage threshold
}


akka {
  cluster.enable = on
  actor {
    provider = cluster
  }
remote.artery {
  canonical {
    hostname = "th01"
    port = 2551
  }
}
# seed node list contains at least one active node
cluster.seed-nodes = [
  "akka://application@th01:2551",
  "akka://application@th02:2551",
  "akka://application@th03:2551"
  ]
}
```

**Comment by nadouani** [comment]
What's the status of the Observable index in your `Administration > Platform Status` page (log in as superadmin)?

**Comment by Canon88** [comment]
> What's the status of the Observable index in your `Administration > Platform Status` page (log in as superadmin)?

![image](https://user-images.githubusercontent.com/19372121/113571180-7504e980-9648-11eb-93c2-9b48e34a5bfd.png)

**Comment by Canon88** [comment]
> What's the status of the Observable index in your `Administration > Platform Status` page (log in as superadmin)?

This problem is solved. I think the problem is caused by an error in the **Cassandra** `username` configuration in my configuration `storage` configuration in TheHive cluster.
