### ISSUE TITLE
[SSL/HTTPS] [How to enable https on TheHive web application?]

### ISSUE THREAD

**Issue by tarekkilani** [TheHive-Project/TheHive#1941]
Hello, 
Please i'm new to TheHive and i want to know if there is any documentation about setting up SSL to TheHive web application.
Thank you in advance for your help.

**Comment by nadouani** [comment]
Hello,

You need a reverse proxy to deal with the SSL part in front of TheHive, (as there is know issue on the underlying framework we use that discourage configuring SSL directly on TheHive)

Here is a doc for TheHive 3 that works also with TheHive 4:
https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#10-https

**Comment by susangz** [comment]
Hello,

I've migrated to TheHive 3.5.0-1 and until now, I was using this configuration to setup access to TheHive web through HTTPS and it was working:

http.port=disabled
https.port: 9443
play.server.https.keyStore {
      path: "/etc/thehive/ssl/keystore.p12"
      type: "pkcs12"
      password: "xxxxxxxx"
}

However, with that configuration I have now these errors:

[error] p.c.s.AkkaHttpServer - Cannot load SSL context
java.lang.ClassCastException: No constructor with (appProvider:play.core.ApplicationProvider) or no-args constructor defined!
        at play.core.server.ssl.ServerSSLEngine$.createScalaSSLEngineProvider(ServerSSLEngine.scala:123)
        at play.core.server.ssl.ServerSSLEngine$.createSSLEngineProvider(ServerSSLEngine.scala:39)
        at play.core.server.AkkaHttpServer.sslContext$lzycompute(AkkaHttpServer.scala:245)
        at play.core.server.AkkaHttpServer.sslContext(AkkaHttpServer.scala:244)
        at play.core.server.AkkaHttpServer.$anonfun$httpsServerBinding$1(AkkaHttpServer.scala:260)
        at play.core.server.AkkaHttpServer.$anonfun$httpsServerBinding$1$adapted(AkkaHttpServer.scala:255)
        at scala.Option.map(Option.scala:230)
        at play.core.server.AkkaHttpServer.<init>(AkkaHttpServer.scala:255)
        at play.core.server.AkkaHttpServerProvider.createServer(AkkaHttpServer.scala:665)
        at play.core.server.AkkaHttpServerProvider.createServer(AkkaHttpServer.scala:663)

Is not more supported that configuration or something has changed?  I have also an nginx, but since I'm integrating TheHive web in my own GUI through an iFrame, I had issues using the reverse proxy and with TheHive in https it worked perfectly.

Thanks!

**Comment by billmurrin** [comment]
Hey @susangz 

I had to troubleshoot this for a bit, change http.port and https.port to
```
play.server.http.port: disabled
play.server.https.port: 9443
```

I was able to get past that error by setting it this way. I based that on this on the Play website
https://www.playframework.com/documentation/2.8.x/SettingsAkkaHttp
