### ISSUE TITLE
[Bug] TheHive Analyzer causes Cortex log 404 error

### ISSUE THREAD

**Issue by Canon88** [TheHive-Project/TheHive#1999]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu |
| Virtualized  Env.          | True |
| Dedicated RAM              | 4 GB |
| vCPU                       | 4 |
| TheHive version / git hash | 4.1.4 |
| Package Type               | Binary |
| Database                   | Cassandra Cluster |
| Index type                 | Elasticsearch Cluster |
| Attachments storage        | Minio Cluster |

### Problem Description
Describe the problem/bug as clearly as possible.

### Steps to Reproduce
1. step 1
1. step 2
1. step 3...

### Possible Solutions
When I submit observables through TheHive Analyzer, I see a lot of 404's reported in the Cortex logs. The strange thing is that everything is working fine with TheHive. As I said, this log is strange.

I tried to perform the same analysis directly through Cortex and the Cortex logs did not report errors.

Apparently this problem only occurs when submitting observables through TheHive Analyzer. I have had this issue in 2 environments.

```
2021-04-25 23:46:55,322 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-157597 - GET /api/analyzer/Shodan_Host_1_0 returned 404
org.elastic4play.NotFoundError: worker Shodan_Host_1_0 not found
	at org.thp.cortex.services.WorkerSrv.$anonfun$getForOrganization$2(WorkerSrv.scala:82)
	at scala.Option.getOrElse(Option.scala:189)
	at org.thp.cortex.services.WorkerSrv.$anonfun$getForOrganization$1(WorkerSrv.scala:82)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-04-25 23:46:55,344 [INFO] from org.thp.cortex.services.JobSrv in application-akka.actor.default-dispatcher-157594 - Looking for similar job in the last 10 minutes (worker=835c09995e8e4cbe348dc0dfe5772f42, dataType=ip, data=Left(159.89.48.18), tlp=2, parameters={})
2021-04-25 23:46:57,310 [INFO] from org.thp.cortex.services.AuditActor in application-akka.actor.default-dispatcher-157602 - Job Buq2CXkB3K627e3kVuj5 has be updated (JsDefined("InProgress"))
2021-04-25 23:46:57,310 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in application-akka.actor.default-dispatcher-157600 - Execute /opt/Cortex-Analyzers/analyzers/Shodan/shodan_analyzer.py in /opt/Cortex-Analyzers/analyzers, timeout is 30 minutes
2021-04-25 23:47:00,331 [INFO] from org.thp.cortex.services.AuditActor in application-akka.actor.default-dispatcher-157602 - Job Buq2CXkB3K627e3kVuj5 has be updated (JsDefined("Success"))
2021-04-25 23:47:00,332 [INFO] from org.thp.cortex.services.JobSrv in application-akka.actor.default-dispatcher-157600 - Job Buq2CXkB3K627e3kVuj5 has finished with status Success
```

**Comment by billmurrin** [comment]
Can you try disabling and re-enabling the Analyzer in Cortex and trying again?

**Comment by Canon88** [comment]
> Can you try disabling and re-enabling the Analyzer in Cortex and trying again?

I have tried the following 2 ways.
1. logging into Cortex and disabling and enabling the plugin in the web interface, he error is still there.
2. restarting the Cortex process directly, the error is still there.

```
2021-05-05 01:24:36,794 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-14 - GET /api/analyzer/HIBP_Query_2_0 returned 404
org.elastic4play.NotFoundError: worker HIBP_Query_2_0 not found
	at org.thp.cortex.services.WorkerSrv.$anonfun$getForOrganization$2(WorkerSrv.scala:82)
	at scala.Option.getOrElse(Option.scala:189)
	at org.thp.cortex.services.WorkerSrv.$anonfun$getForOrganization$1(WorkerSrv.scala:82)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-05-05 01:24:36,944 [INFO] from org.thp.cortex.services.JobSrv in application-akka.actor.default-dispatcher-14 - Looking for similar job in the last 10 minutes (worker=b43886ccf2f5c7e9873d0ff66af6fd0d, dataType=mail, data=Left(corneliapony@gmail.com), tlp=2, parameters={})
```

**Comment by Canon88** [comment]
**Update:**
I saw some strange logs when I restarted Cortex. It contains a description of "Permission denied".

```
2021-05-05 01:28:20,731 [INFO] from play.api.internal.libs.concurrent.CoordinatedShutdownSupport in Thread-21 - Starting synchronous coordinated shutdown with ServerStoppedReason reason and 2147508000 milliseconds timeout
2021-05-05 01:28:20,733 [INFO] from play.core.server.AkkaHttpServer in Thread-21 - Stopping Akka HTTP server...
2021-05-05 01:28:20,740 [INFO] from play.core.server.AkkaHttpServer in application-akka.actor.internal-dispatcher-2 - Terminating server binding for /0:0:0:0:0:0:0:0:9001
2021-05-05 01:28:20,796 [INFO] from play.core.server.AkkaHttpServer in application-akka.actor.internal-dispatcher-2 - Running provided shutdown stop hooks
2021-05-05 01:28:22,673 [INFO] from org.reflections.Reflections in main - Reflections took 157 ms to scan 2 urls, producing 99 keys and 968 values
2021-05-05 01:28:22,746 [INFO] from module in main - Loading model class org.thp.cortex.models.OrganizationModel
2021-05-05 01:28:22,749 [INFO] from module in main - Loading model class org.elastic4play.services.DBListModel
2021-05-05 01:28:22,749 [INFO] from module in main - Loading model class org.thp.cortex.models.WorkerConfigModel
2021-05-05 01:28:22,749 [INFO] from module in main - Loading model class org.elastic4play.services.AttachmentModel
2021-05-05 01:28:22,750 [INFO] from module in main - Loading model class org.thp.cortex.models.AuditModel
2021-05-05 01:28:22,750 [INFO] from module in main - Loading model class org.thp.cortex.models.ArtifactModel
2021-05-05 01:28:22,750 [INFO] from module in main - Loading model class org.thp.cortex.models.WorkerModel
2021-05-05 01:28:22,751 [INFO] from module in main - Loading model class org.thp.cortex.models.UserModel
2021-05-05 01:28:22,751 [INFO] from module in main - Loading model class org.thp.cortex.models.JobModel
2021-05-05 01:28:22,752 [INFO] from module in main - Loading model class org.thp.cortex.models.ReportModel
2021-05-05 01:28:22,758 [INFO] from module in main - Loading authentication module class org.elastic4play.services.auth.LdapAuthSrv
2021-05-05 01:28:22,759 [INFO] from module in main - Loading authentication module class org.thp.cortex.services.LocalAuthSrv
2021-05-05 01:28:22,759 [INFO] from module in main - Loading authentication module class org.thp.cortex.services.OAuth2Srv
2021-05-05 01:28:22,759 [INFO] from module in main - Loading authentication module class org.thp.cortex.services.KeyAuthSrv
2021-05-05 01:28:22,760 [INFO] from module in main - Loading authentication module class org.elastic4play.services.auth.ADAuthSrv
2021-05-05 01:28:24,383 [INFO] from akka.event.slf4j.Slf4jLogger in application-akka.actor.default-dispatcher-6 - Slf4jLogger started
2021-05-05 01:28:27,074 [INFO] from org.apache.http.impl.execchain.RetryExec in jersey-client-async-executor-0 - I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
2021-05-05 01:28:27,075 [INFO] from org.apache.http.impl.execchain.RetryExec in jersey-client-async-executor-0 - Retrying request to {}->unix://localhost:80
2021-05-05 01:28:27,076 [INFO] from org.apache.http.impl.execchain.RetryExec in jersey-client-async-executor-0 - I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
2021-05-05 01:28:27,076 [INFO] from org.apache.http.impl.execchain.RetryExec in jersey-client-async-executor-0 - Retrying request to {}->unix://localhost:80
2021-05-05 01:28:27,076 [INFO] from org.apache.http.impl.execchain.RetryExec in jersey-client-async-executor-0 - I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
2021-05-05 01:28:27,077 [INFO] from org.apache.http.impl.execchain.RetryExec in jersey-client-async-executor-0 - Retrying request to {}->unix://localhost:80
2021-05-05 01:28:27,086 [INFO] from org.thp.cortex.services.DockerJobRunnerSrv in main - Docker is not available
com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.io.IOException: Permission denied
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2828)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2692)
	at com.spotify.docker.client.DefaultDockerClient.info(DefaultDockerClient.java:595)
	at org.thp.cortex.services.DockerJobRunnerSrv.$anonfun$isAvailable$2(DockerJobRunnerSrv.scala:55)
	at play.api.LoggerLike.info(Logger.scala:136)
	at play.api.LoggerLike.info$(Logger.scala:133)
	at play.api.Logger.info(Logger.scala:233)
	at org.thp.cortex.services.DockerJobRunnerSrv.$anonfun$isAvailable$1(DockerJobRunnerSrv.scala:55)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at org.thp.cortex.services.DockerJobRunnerSrv.isAvailable$lzycompute(DockerJobRunnerSrv.scala:54)
	at org.thp.cortex.services.DockerJobRunnerSrv.isAvailable(DockerJobRunnerSrv.scala:53)
	at org.thp.cortex.services.JobRunnerSrv$$anonfun$1.applyOrElse(JobRunnerSrv.scala:52)
	at org.thp.cortex.services.JobRunnerSrv$$anonfun$1.applyOrElse(JobRunnerSrv.scala:51)
	at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:145)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.collect(TraversableLike.scala:406)
	at scala.collection.TraversableLike.collect$(TraversableLike.scala:404)
	at scala.collection.AbstractTraversable.collect(Traversable.scala:108)
	at org.thp.cortex.services.JobRunnerSrv.<init>(JobRunnerSrv.scala:51)
	at org.thp.cortex.services.JobRunnerSrv$$FastClassByGuice$$7cb671c9.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:78)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:54)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:30)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.io.IOException: Permission denied
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2690)
	... 44 common frames omitted
Caused by: javax.ws.rs.ProcessingException: java.io.IOException: Permission denied
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:178)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Permission denied
	at jnr.unixsocket.UnixSocketChannel.doConnect(UnixSocketChannel.java:127)
	at jnr.unixsocket.UnixSocketChannel.connect(UnixSocketChannel.java:136)
	at jnr.unixsocket.UnixSocketChannel.connect(UnixSocketChannel.java:223)
	at com.spotify.docker.client.UnixConnectionSocketFactory.connectSocket(UnixConnectionSocketFactory.java:85)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	... 21 common frames omitted
2021-05-05 01:28:27,704 [INFO] from org.thp.cortex.services.JobRunnerSrv in application-akka.actor.default-dispatcher-7 - The package cortexutils for python has valid version: 2.1.0
2021-05-05 01:28:27,713 [WARN] from org.thp.cortex.services.JobRunnerSrv in application-akka.actor.default-dispatcher-7 - The package cortexutils for python2 hasn't been found
2021-05-05 01:28:27,717 [INFO] from org.thp.cortex.services.JobRunnerSrv in main - The package cortexutils for python has valid version: 2.1.0
2021-05-05 01:28:27,728 [WARN] from org.thp.cortex.services.JobRunnerSrv in main - The package cortexutils for python2 hasn't been found
2021-05-05 01:28:28,326 [INFO] from org.thp.cortex.services.JobRunnerSrv in application-akka.actor.default-dispatcher-7 - The package cortexutils for python3 has valid version: 2.1.0
2021-05-05 01:28:28,350 [INFO] from org.thp.cortex.services.JobRunnerSrv in main - The package cortexutils for python3 has valid version: 2.1.0
2021-05-05 01:28:28,527 [INFO] from com.sksamuel.elastic4s.http.JavaClient$ in main - Creating HTTP client on https://elasticsearch01:9200,https://https::9200
2021-05-05 01:28:28,633 [INFO] from org.thp.cortex.services.WorkerSrv in application-akka.actor.default-dispatcher-6 - New worker list:
```

**Comment by To-om** [comment]
Regarding the last error, Cortex uses Docker service: the system user which runs the Cortex service must have permission on Docker service (be in docker group)

**Comment by Canon88** [comment]
Hi:
	My Cortex is using the binary installation, why do I still have this problem?

**Comment by To-om** [comment]
Cortex use docker to run analyzers. It is not mandatory but recommanded. You can disable it by setting `job.runners: [process]` in application.conf. If you do that, you need to install analyzers locally (with dependencies). The default analyzer catalog contains only docker version of analyzers.

**Comment by Canon88** [comment]
> Cortex use docker to run analyzers. It is not mandatory but recommanded. You can disable it by setting `job.runners: [process]` in application.conf. If you do that, you need to install analyzers locally (with dependencies). The default analyzer catalog contains only docker version of analyzers.

Thanks, it has been solved.

But the first question is still open, why I go through TheHive to analyze a metric and there is a 404 error reported in the Cortex log in the backend.

```
GET /api/analyzer/Shodan_Host_1_0 returned 404
org.elastic4play.NotFoundError: worker Shodan_Host_1_0 not found
```

**Comment by To-om** [comment]
The message `worker XXX not found` in cortex is not a real error. TheHive can invoke a Cortex job using analyzer name (`Shodan_Host_1_0` for example) or using its ID (`tf0PhHkBMxgXsAvGvUBX`). But TheHive can't distinguish the two forms. The current frontend of TheHive uses only names.

The solution of this non-problem (everything is working correctly) is to make id recognizable.

**Comment by Canon88** [comment]
> The message `worker XXX not found` in cortex is not a real error. TheHive can invoke a Cortex job using analyzer name (`Shodan_Host_1_0` for example) or using its ID (`tf0PhHkBMxgXsAvGvUBX`). But TheHive can't distinguish the two forms. The current frontend of TheHive uses only names.
> 
> The solution of this non-problem (everything is working correctly) is to make id recognizable.

OK, thank you for your reply.
