### ISSUE TITLE
TheHive4 Migration Issue

### ISSUE THREAD

**Issue by lissymaria** [TheHive-Project/TheHive#2006]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | RedHat  |
| OS version (client)        | 7.9 |
| TheHive version           | 4.1.4-1              |
| Package Type               | RPM |
| Database                   | Cassandra          |

### Problem Description
When I run the migration script, I am getting the following error . Thehive3 index is showing as thehive_10. I ran the script with same index only,but in the error field it is showing that index not found. 

[ERROR] from org.thp.thehive.migration.Migrate in main [|] Migration failed
java.lang.RuntimeException: TheHive 3.x index the_hive not found
        at scala.sys.package$.error(package.scala:30)
        at org.thp.thehive.migration.th3.DBConfiguration.indexName$lzycompute(DBConfiguration.scala:214)
        at org.thp.thehive.migration.th3.DBConfiguration.indexName(DBConfiguration.scala:208)
        at org.thp.thehive.migration.th3.DBFind.apply(DBFind.scala:93)
        at org.thp.thehive.migration.th3.Input.countCases(Input.scala:98)
        at org.thp.thehive.migration.MigrationOps.migrate(MigrationOps.scala:376)
        at org.thp.thehive.migration.MigrationOps.migrate$(MigrationOps.scala:302)
        at org.thp.thehive.migration.Migrate$.migrate(Migrate.scala:15)
        at org.thp.thehive.migration.Migrate$.$anonfun$new$2(Migrate.scala:193)
        at org.thp.thehive.migration.Migrate$.$anonfun$new$2$adapted(Migrate.scala:174)
        at scala.Option.foreach(Option.scala:407)
        at org.thp.thehive.migration.Migrate$.delayedEndpoint$org$thp$thehive$migration$Migrate$1(Migrate.scala:174)
        at org.thp.thehive.migration.Migrate$delayedInit$body.apply(Migrate.scala:15)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1$adapted(App.scala:80)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at scala.App.main(App.scala:80)
        at scala.App.main$(App.scala:78)
        at org.thp.thehive.migration.Migrate$.main(Migrate.scala:15)
        at org.thp.thehive.migration.Migrate.main(Migrate.scala)
2021-04-28 00:08:49,791 [INFO] from org.thp.thehive.ClusterListener in TheHiveMigration-akka.actor.default-dispatcher-17 [|] Member is Removed: akka://TheHiveMigration@127.0.0.1:34988 after Exiting
2021-04-28 00:08:49,837 [INFO] from org.thp.thehive.migration.Migrate in main [|] Stage: Get element count
Organisation: 0/1
Any solution for this?

**Comment by To-om** [comment]
The migration to TheHive 4 works only with TheHive 3.5.0 or higher.

**Comment by lissymaria** [comment]
@To-om : Thank You for the reply . But in theHive4 github article, I noticed the migration tool is supposed to work on Thehive 3.4 version . 
https://github.com/TheHive-Project/TheHiveDocs/blob/master/TheHive4/Administration/Migration.md
I will attempt the migration by updating the version to 3.5 also.
