### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Idriel** [TheHive-Project/TheHive#2027]
### Problem Description
Database upgrade from 3.4-1 to 3.5.1-1
Error
```
[info] o.e.s.MigrationSrv - Initiate database migration from version 15
[info] o.e.s.MigrationSrv - Migrate database from version 15, add operations for version 16
[info] o.e.s.MigrationSrv - Migrate database from version 15, add operations for version 17
[error] o.e.d.DBConfiguration - ElasticSearch request failure: PUT:/the_hive_17?include_type_name=false
StringEntity({"settings":{"index":{"number_of_shards":5,"mapping.single_type":true,"number_of_replicas":1,"mapping.nested_fields.limit":100}},"mappings":{"date_detection":false,"numeric_detection":false,"properties":{"sequenceCounter":{"type":"long"},"updatedAt":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"updatedBy":{"type":"keyword"},"createdAt":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"createdBy":{"type":"keyword"},"reports":{"type":"text","fielddata":true},"status":{"type":"keyword"},"sighted":{"type":"boolean"},"ioc":{"type":"boolean"},"tags":{"type":"keyword"},"tlp":{"type":"long"},"attachment":{"type":"nested","properties":{"name":{"type":"keyword"},"hashes":{"type":"keyword"},"size":{"type":"long"},"contentType":{"type":"keyword"},"id":{"type":"keyword"}}},"startDate":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"message":{"type":"text","fielddata":true},"dataType":{"type":"keyword"},"data":{"type":"keyword"},"operations":{"type":"text","fielddata":true},"cortexJobId":{"type":"keyword"},"cortexId":{"type":"keyword"},"report":{"type":"text","fielddata":true},"endDate":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"objectId":{"type":"keyword"},"objectType":{"type":"keyword"},"responderDefinition":{"type":"keyword"},"responderName":{"type":"keyword"},"responderId":{"type":"keyword"},"dblist":{"type":"keyword"},"value":{"type":"keyword"},"definition":{"type":"text","fielddata":true},"description":{"type":"text","fielddata":true},"title":{"type":"text","fielddata":true},"requestId":{"type":"keyword"},"rootId":{"type":"keyword"},"base":{"type":"boolean"},"otherDetails":{"type":"text","fielddata":true},"details":{"type":"nested","properties":{"mergeFrom":{"type":"keyword"},"name":{"type":"keyword"},"updatedAt":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"tlp":{"type":"long"},"endDate":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"caseTemplate":{"type":"keyword"},"description":{"type":"text","fielddata":true},"_id":{"type":"keyword"},"tags":{"type":"keyword"},"lastSyncDate":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"caseId":{"type":"long"},"customFields":{"type":"nested"},"ioc":{"type":"boolean"},"mergeInto":{"type":"keyword"},"pap":{"type":"long"},"roles":{"type":"keyword"},"order":{"type":"long"},"objectType":{"type":"keyword"},"status":{"type":"keyword"},"resolutionStatus":{"type":"keyword"},"sighted":{"type":"boolean"},"dueDate":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"flag":{"type":"boolean"},"attachment":{"type":"nested","properties":{"name":{"type":"keyword"},"hashes":{"type":"keyword"},"size":{"type":"long"},"contentType":{"type":"keyword"},"id":{"type":"keyword"}}},"message":{"type":"text","fielddata":true},"severity":{"type":"long"},"metrics":{"type":"nested"},"owner":{"type":"keyword"},"title":{"type":"text","fielddata":true},"case":{"type":"keyword"},"updatedBy":{"type":"keyword"},"startDate":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"group":{"type":"keyword"},"summary":{"type":"text","fielddata":true},"impactStatus":{"type":"keyword"},"follow":{"type":"boolean"}}},"operation":{"type":"keyword"},"analyzerId":{"type":"keyword"},"reportType":{"type":"keyword"},"content":{"type":"text","fielddata":true},"artifactId":{"type":"keyword"},"analyzerDefinition":{"type":"keyword"},"analyzerName":{"type":"keyword"},"customFields":{"type":"nested"},"mergeFrom":{"type":"keyword"},"mergeInto":{"type":"keyword"},"summary":{"type":"text","fielddata":true},"impactStatus":{"type":"keyword"},"resolutionStatus":{"type":"keyword"},"metrics":{"type":"nested"},"pap":{"type":"long"},"flag":{"type":"boolean"},"owner":{"type":"keyword"},"severity":{"type":"long"},"caseId":{"type":"long"},"tasks":{"type":"nested","properties":{"group":{"type":"keyword"},"dueDate":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"order":{"type":"long"},"endDate":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"startDate":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"flag":{"type":"boolean"},"status":{"type":"keyword"},"owner":{"type":"keyword"},"description":{"type":"text","fielddata":true},"title":{"type":"text","fielddata":true}}},"titlePrefix":{"type":"text","fielddata":true},"name":{"type":"keyword"},"binary":{"type":"binary"},"follow":{"type":"boolean"},"caseTemplate":{"type":"keyword"},"artifacts":{"type":"nested","properties":{"data":{"type":"keyword"},"dataType":{"type":"keyword"},"message":{"type":"keyword"},"startDate":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"attachment":{"type":"nested","properties":{"name":{"type":"keyword"},"hashes":{"type":"keyword"},"size":{"type":"long"},"contentType":{"type":"keyword"},"id":{"type":"keyword"}}},"remoteAttachment":{"type":"nested","properties":{"reference":{"type":"keyword"},"filename":{"type":"keyword"},"contentType":{"type":"keyword"},"size":{"type":"long"},"hash":{"type":"keyword"},"type":{"type":"keyword"}}},"sighted":{"type":"boolean"},"tlp":{"type":"long"},"tags":{"type":"keyword"},"ioc":{"type":"boolean"}}},"case":{"type":"keyword"},"lastSyncDate":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"date":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"sourceRef":{"type":"keyword"},"source":{"type":"keyword"},"type":{"type":"keyword"},"preferences":{"type":"keyword"},"avatar":{"type":"keyword"},"password":{"type":"keyword"},"roles":{"type":"keyword"},"key":{"type":"keyword"},"login":{"type":"keyword"},"group":{"type":"keyword"},"dueDate":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"order":{"type":"long"},"relations":{"type":"join","relations":{"case_artifact":["case_artifact_job"],"caseTemplate":["dummy-caseTemplate"],"alert":["dummy-alert"],"dashboard":["dummy-dashboard"],"data":["dummy-data"],"sequence":["dummy-sequence"],"reportTemplate":["dummy-reportTemplate"],"audit":["dummy-audit"],"case":["case_artifact","dummy-case","case_task"],"case_task":["case_task_log"],"action":["dummy-action"],"user":["dummy-user"],"dblist":["dummy-dblist"]}}},"dynamic_templates":[{"details_customFields":{"path_match":"details.customFields.*","mapping":{"type":"nested","properties":{"number":{"type":"long"},"string":{"type":"keyword"},"date":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"boolean":{"type":"boolean"},"order":{"type":"long"}}}}},{"details_metrics":{"path_match":"details.metrics.*","mapping":{"type":"long"}}},{"customFields":{"path_match":"customFields.*","mapping":{"type":"nested","properties":{"number":{"type":"long"},"string":{"type":"keyword"},"date":{"type":"date","format":"epoch_millis||basic_date_time_no_millis"},"boolean":{"type":"boolean"},"order":{"type":"long"}}}}},{"metrics":{"path_match":"metrics.*","mapping":{"type":"long"}}}]}},Some(application/json))
 => ElasticError(class_cast_exception,java.lang.Boolean cannot be cast to java.util.Map,None,None,None,List(ElasticError(class_cast_exception,java.lang.Boolean cannot be cast to java.util.Map,None,None,None,null,None,None,None,List())),None,None,None,List())
[error] o.e.s.MigrationSrv - Migration fail
org.elastic4play.InternalError: Unknown error: ElasticError(class_cast_exception,java.lang.Boolean cannot be cast to java.util.Map,None,None,None,List(ElasticError(class_cast_exception,java.lang.Boolean cannot be cast to java.util.Map,None,None,None,null,None,None,None,List())),None,None,None,List())
	at org.elastic4play.database.DBConfiguration.$anonfun$execute$2(DBConfiguration.scala:158)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
[info] o.e.ErrorHandler - POST /api/maintenance/migrate returned 500
org.elastic4play.InternalError: Unknown error: ElasticError(class_cast_exception,java.lang.Boolean cannot be cast to java.util.Map,None,None,None,List(ElasticError(class_cast_exception,java.lang.Boolean cannot be cast to java.util.Map,None,None,None,null,None,None,None,List())),None,None,None,List())
	at org.elastic4play.database.DBConfiguration.$anonfun$execute$2(DBConfiguration.scala:158)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
```

**Comment by Idriel** [comment]
following upgrade procedure to 3.5 and reindex from ES 6.x solved challange.
