### ISSUE TITLE
[Bug]S3 storage Access Denied error

### ISSUE THREAD

**Issue by andreacardaropoli** [TheHive-Project/TheHive#2038]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu  |
| TheHive version / git hash | 4.1             |
| Package Type               | DEB |
| Database                   | Cassandra                |
| Index type                 | Elasticsearch                |
| Attachments storage        | S3                  |

### Problem Description
Task attachments and S3 storage operations fail with Access Denied error to S3 despite having proper credentials.

### Steps to Reproduce
1. Use S3 as storage
```
storage {
  provider: s3
  s3 {
    bucket = ${STORAGE_BUCKET}
    readTimeout = 1 minute
    writeTimeout = 1 minute
    chunkSize = 1 MB
    accessKey = ${STORAGE_ACCESS_KEY}
    secretKey = ${STORAGE_SECRET_KEY}
    endpoint = "http://s3.amazonaws.com"
    region = "us-east-1"
  }
}
```
2. Try to attach a file to a Task in a case
2. Try to set your profile image
3. See log errors:
```
[error] o.t.s.u.Retry - uncaught error, not retrying
akka.stream.alpakka.s3.S3Exception: Access Denied
	at akka.stream.alpakka.s3.S3Exception$.apply(S3Exception.scala:69)
	at akka.stream.alpakka.s3.impl.S3Stream$.$anonfun$unmarshalError$1(S3Stream.scala:246)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transform(FastFuture.scala:84)
	at scala.concurrent.Future.map(Future.scala:292)
	at scala.concurrent.Future.map$(Future.scala:292)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.map(FastFuture.scala:77)
	at akka.stream.alpakka.s3.impl.S3Stream$.unmarshalError(S3Stream.scala:245)
[error] o.t.s.m.Database - Exception raised, rollback (Access Denied)
[error] o.t.s.ErrorHandler - Internal error
akka.stream.alpakka.s3.S3Exception: Access Denied
	at akka.stream.alpakka.s3.S3Exception$.apply(S3Exception.scala:69)
	at akka.stream.alpakka.s3.impl.S3Stream$.$anonfun$unmarshalError$1(S3Stream.scala:246)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transform(FastFuture.scala:84)
	at scala.concurrent.Future.map(Future.scala:292)
	at scala.concurrent.Future.map$(Future.scala:292)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.map(FastFuture.scala:77)
	at akka.stream.alpakka.s3.impl.S3Stream$.unmarshalError(S3Stream.scala:245)
[warn] o.t.s.ErrorHandler - PATCH /api/v1/user/admin@thehive.local returned 500
```

I have migrated from TheHive 3.4 to TheHive 4.0.4 and then upgraded to TheHive 4.1.4. The migration script created files in S3 just fine.

### Possible Solutions
(keep this section if you have suggestions on how to solve the problem. **Otherwise delete it**)

### Complementary information
(add anything that can help identifying the problem such as **log** excerpts, **screenshots**, **configuration dumps** etc.)

**Comment by andreacardaropoli** [comment]
If you have a DNS style bucket name use:

alpakka.s3.path-style-access = force

in your application.conf
