### ISSUE TITLE
[Bug] Ghost alert in alert.count header

### ISSUE THREAD

**Issue by azgaviperr** [TheHive-Project/TheHive#2091]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Docker SWARM   |
| OS version (client)        | Viperr,     |
| Virtualized  Env.          | True |
| Dedicated RAM              | 16 GB                                 |
| vCPU                       |  8                       |
| TheHive version / git hash | 4.x, hash of the commit               |
| Package Type               | RPM, DEB, Docker, Binary, From source |
| Database                   | Cassandra  |
| Index type                 |  Elasticsearch   |
| Attachments storage        | Local (GlusterFS)     |
| Browser type & version     | Firefow and Chrome                     |

### Problem Description
Even if all alert are read or imported the counter show a lasting alert that can't be found 

![image](https://user-images.githubusercontent.com/7451354/122908155-1e0fd600-d354-11eb-9dbe-1093ae214e62.png)

There is no error in logs, and symptom are still here even after reindex and dataintegrity check. Nor sure what could be requested by API to get more info or how to debug in cassandra. I first discover this after a merge of multiple alert into one case, not sure if this is related.

### Steps to Reproduce

No idea how to reproduce this, maybe because of a faulty alert creation by api

### Possible Solutions

**Comment by azgaviperr** [comment]
Got now 6 ghost alert and no way to get them, even using api. 
How can I look for it in Cassandra ? 

Caught this error while refreshing the alert page

`info] o.t.s.AccessLogFilter [0000023f|] 10.0.3.10 POST /thehive/api/v1/query?name=alerts.count took 61ms and returned 200 2 bytes

[error] o.t.s.t.TraversalOps [|] Traversal has generated an error

org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception

	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:56)

	at org.janusgraph.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:469)

	at org.janusgraph.diskstorage.BackendTransaction.totals(BackendTransaction.java:463)

	at org.janusgraph.graphdb.database.IndexSerializer.executeTotals(IndexSerializer.java:671)

	at org.janusgraph.graphdb.query.graph.IndexQueryBuilder.executeTotals(IndexQueryBuilder.java:216)

	at org.janusgraph.graphdb.query.graph.IndexQueryBuilder.vertexTotals(IndexQueryBuilder.java:258)

	at org.thp.scalligraph.janus.JanusDatabase.indexCountQuery(JanusDatabase.scala:267)

	at org.thp.scalligraph.traversal.GraphWrapper.indexCountQuery(Graph.scala:59)

	at org.thp.thehive.services.AlertOps$AlertOpsDefs.$anonfun$richAlertWithCustomRenderer$5(AlertSrv.scala:565)

	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)

Caused by: org.janusgraph.diskstorage.PermanentBackendException: Permanent failure in storage backend

	at org.janusgraph.diskstorage.es.ElasticSearchIndex.runCountQuery(ElasticSearchIndex.java:1186)

	at org.janusgraph.diskstorage.es.ElasticSearchIndex.totals(ElasticSearchIndex.java:1219)

	at org.janusgraph.diskstorage.indexing.IndexTransaction.totals(IndexTransaction.java:124)

	at org.janusgraph.diskstorage.BackendTransaction$TotalsCallable.call(BackendTransaction.java:452)

	at org.janusgraph.diskstorage.BackendTransaction$TotalsCallable.call(BackendTransaction.java:441)

	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:68)

	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:54)

	at org.janusgraph.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:469)

	at org.janusgraph.diskstorage.BackendTransaction.totals(BackendTransaction.java:463)

	at org.janusgraph.graphdb.database.IndexSerializer.executeTotals(IndexSerializer.java:671)

Caused by: java.io.IOException: Connection reset by peer

	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:884)

	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:283)

	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)

	at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.performRequest(RestElasticSearchClient.java:483)

	at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.countTotal(RestElasticSearchClient.java:424)

	at org.janusgraph.diskstorage.es.ElasticSearchIndex.runCountQuery(ElasticSearchIndex.java:1182)

	at org.janusgraph.diskstorage.es.ElasticSearchIndex.totals(ElasticSearchIndex.java:1219)

	at org.janusgraph.diskstorage.indexing.IndexTransaction.totals(IndexTransaction.java:124)

	at org.janusgraph.diskstorage.BackendTransaction$TotalsCallable.call(BackendTransaction.java:452)

	at org.janusgraph.diskstorage.BackendTransaction$TotalsCallable.call(BackendTransaction.java:441)

Caused by: java.io.IOException: Connection reset by peer

	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)

	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)

	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)

	at sun.nio.ch.IOUtil.read(IOUtil.java:197)

	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)

	at org.apache.http.impl.nio.reactor.SessionInputBufferImpl.fill(SessionInputBufferImpl.java:231)

	at org.apache.http.impl.nio.codecs.AbstractMessageParser.fillBuffer(AbstractMessageParser.java:136)

	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:241)

	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)

	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)`

**Comment by azgaviperr** [comment]
![image](https://user-images.githubusercontent.com/7451354/125442577-cc7d8341-bda5-4398-83df-f5fdba8905d9.png)
I had 27 alerts at all in the UI list and using api to query it. A  few were deleted as not relevant .

I was able to solve the issue by deleting the elastic index and reindex all. 

Maybe need some extra tweak on the index control.

![image](https://user-images.githubusercontent.com/7451354/125442812-93109f29-fdd5-425e-92b2-01d6ed8785b3.png)

**Comment by Keroseno101** [comment]
Hi, that looks a Index Problem, somehow is your index broken and therefore you have information but is not show in the application. 

Is that happened after a reboot or patch day? I would bet 100€

Probably you can not see nothing in /var/log/elasticsearch/yourclustername.log but you can rebuild the Index to fix this problem. 

vi /etc/thehive/application.conf and write down there: db.janusgraph.forceDropAndRebuildIndex: true
Change this line in /etc/thehive/logback.xml --> <logger name="org.thp" level="DEBUG"/>
then systemctl restart thehive.service && tail -f /var/log/thehive/application.log 

You will see in real time how the index is created, can take 2 minutes or 10 minutes, just wait if there are not errors, you will see something like this at the end:
![image](https://user-images.githubusercontent.com/103500747/200516134-a1fc85a1-0249-4e7b-ba05-a24d2a188beb.png)


Your data will be not compromised, TheHive use elasticsearch as a index and Cassandra as a Database, therefore you can drop and rebuild the Index as you want without loss information. 

Please answer this Post if you fix it or if you have some error.
