### ISSUE TITLE
[Bug] The Hive crashes when usage is high

### ISSUE THREAD

**Issue by mamoedo** [TheHive-Project/TheHive#2111]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| TheHive version / git hash | 4.1,7             |
| Package Type               | Binary |
| Database                   | Cassandra                |
| Index type                 |  Elasticsearch                |
| Attachments storage        | Local              |

### Problem Description
When using TH with a few users there's sometimes when it starts breaking until it's not responding anymore.

### Steps to Reproduce
Just give TH a moderate usage.

### Possible Solutions
Improve performance so it does not crashes.

When I restart TH4, the CPU usage drops on the host where it's the Cassandra and Elasticsearch.

### Complementary information
I attach the logs just before the crash. We can observe some exceptions and some Cassandra logs which may indicate a performance problem.

Special logs:

```
[error] o.t.t.c.m.s.QueueIterator [|779cfb4e] Stream fails
  java.util.concurrent.TimeoutException: Futures timed out after [1 minute]
at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
at scala.concurrent.Await$.$anonfun$result$1(package.scala:223)
at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:174)
at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3313)
at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:172)
at scala.concurrent.Await$.result(package.scala:146)
at org.thp.thehive.connector.misp.services.QueueIterator.getNextValue(QueueIterator.scala:17)
at org.thp.thehive.connector.misp.services.QueueIterator.hasNext(QueueIterator.scala:28)
at scala.collection.Iterator.foreach(Iterator.scala:943)

[info] o.t.t.c.m.s.MispImportSrv [|779cfb4e] Removing old observables
```
```
[WARN] from com.datastax.driver.core.RequestHandler in thp-nio-worker-2 [|] Query '[4 bound values] SELECT
 column1,value,writetime(value) AS writetime,ttl(value) AS ttl FROM thehive.edgestore WHERE key=:key AND column1>=:sliceStart AND
column1<:sliceEnd LIMIT :maxRows;' generated server side warning(s): Read 1014 live rows and 24149 tombstone cells for query SELEC
T * FROM thehive.edgestore WHERE key = e000000000215e00 AND column1 > 72e1a8515d2128b014037c1815 AND column1 < 72e2 LIMIT 5000 (se
e tombstone_warn_threshold)
```
```
[info] o.t.s.AccessLogFilter [0000abd1|] 123.123.123.123 POST /api/v1/query?name=alert-by-tags-stats took 172351ms and returned 200 233 bytes
```
```
[warn] o.t.s.u.Retry [0000ab53|] An error occurs (org.thp.scalligraph.NotFoundError: Stream CfFQyp1ZZUeYf2vUMoGK doesn't exist), retrying (1)
```

TH logs:

[bug_th.txt](https://github.com/TheHive-Project/TheHive/files/6782609/bug_th.txt)

Cassandra logs:

```
WARN  [ReadStage-4] 2021-06-29 14:48:53,011 ReadCommand.java:569 - Read 5000 live rows and 1555 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 40000000001bd480 AND column1 > 7ba0a4197b6120a5736f6008 AND column1 < 7ba1 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-2] 2021-06-29 14:48:53,281 ReadCommand.java:569 - Read 5000 live rows and 1915 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 40000000001bd480 AND column1 > 7ba0a4642d4100a5710d4008 AND column1 < 7ba1 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-2] 2021-06-29 14:48:53,509 ReadCommand.java:569 - Read 5000 live rows and 1298 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 40000000001bd480 AND column1 > 7ba0a663394128a353023c08 AND column1 < 7ba1 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-1] 2021-06-29 14:48:53,772 ReadCommand.java:569 - Read 5000 live rows and 1517 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 40000000001bd480 AND column1 > 7ba0a87d3a2010a501626408 AND column1 < 7ba1 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-4] 2021-06-29 14:48:54,083 ReadCommand.java:569 - Read 5000 live rows and 1290 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 40000000001bd480 AND column1 > 7ba0ab4e020010a57c446008 AND column1 < 7ba1 LIMIT 5000 (see tombstone_warn_threshold)
INFO  [ScheduledTasks:1] 2021-06-29 14:54:38,970 NoSpamLogger.java:91 - Some operations were slow, details available at debug level (debug.log)
WARN  [ReadStage-4] 2021-06-29 14:59:23,844 ReadCommand.java:569 - Read 5000 live rows and 26673 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = b0000000001e4c00 AND column1 >= 72e1 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-4] 2021-06-29 14:59:23,882 ReadCommand.java:569 - Read 809 live rows and 4767 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = b0000000001e4c00 AND column1 > 72e1ac0a616010b0192e6a6002 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [Native-Transport-Requests-1] 2021-06-29 14:59:26,246 ReadCommand.java:569 - Read 5000 live rows and 2014 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = a000000000429780 AND column1 > 72e1a32c6b6118a737163813 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [Native-Transport-Requests-1] 2021-06-29 14:59:26,276 ReadCommand.java:569 - Read 5000 live rows and 3787 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = a000000000429780 AND column1 > 72e1a45f726160a76205081c AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-2] 2021-06-29 14:59:41,508 ReadCommand.java:569 - Read 3360 live rows and 26266 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 88000000059fc500 AND column1 >= 72e1 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-1] 2021-06-29 15:02:47,476 ReadCommand.java:569 - Read 5000 live rows and 2837 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 30000000001e6e00 AND column1 >= 72e1 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-1] 2021-06-29 15:03:02,034 ReadCommand.java:569 - Read 5000 live rows and 1796 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 80000000005beb80 AND column1 > 72e1a3285a4118a730542013 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-4] 2021-06-29 15:03:02,062 ReadCommand.java:569 - Read 5000 live rows and 2172 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 80000000005beb80 AND column1 > 72e1a44b5d6110a92c521c12 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-7] 2021-06-29 15:03:02,091 ReadCommand.java:569 - Read 5000 live rows and 1846 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 80000000005beb80 AND column1 > 72e1a558774138ad55055817 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [Native-Transport-Requests-3] 2021-06-29 15:03:02,324 ReadCommand.java:569 - Read 5000 live rows and 13958 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = e000000000215e00 AND column1 >= 72e1 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-2] 2021-06-29 15:03:02,393 ReadCommand.java:569 - Read 5000 live rows and 8388 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = e000000000215e00 AND column1 > 72e1a235290120a377042c14 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [Native-Transport-Requests-1] 2021-06-29 15:03:02,578 ReadCommand.java:569 - Read 5000 live rows and 38409 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = e000000000215e00 AND column1 > 72e1a3222d6040a84e4d4808 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-6] 2021-06-29 15:03:02,694 ReadCommand.java:569 - Read 5000 live rows and 21508 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = e000000000215e00 AND column1 > 72e1a765740138b01218163417 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-1] 2021-06-29 15:03:02,733 ReadCommand.java:569 - Read 1923 live rows and 4436 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = e000000000215e00 AND column1 > 72e1ad26614010b01b3e5b6002 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [Native-Transport-Requests-6] 2021-06-29 15:03:07,015 ReadCommand.java:569 - Read 5000 live rows and 51712 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 10000000032ca100 AND column1 >= 72e1 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-2] 2021-06-29 15:03:12,342 ReadCommand.java:569 - Read 3127 live rows and 19751 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 88000000059fb700 AND column1 >= 72e1 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-3] 2021-06-29 15:03:13,908 ReadCommand.java:569 - Read 5000 live rows and 7493 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 20000000084b7780 AND column1 >= 72e1 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-1] 2021-06-29 15:03:14,002 ReadCommand.java:569 - Read 5000 live rows and 15199 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 20000000084b7780 AND column1 > 72e1a2742c6040a77c707808 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-3] 2021-06-29 15:03:14,099 ReadCommand.java:569 - Read 5000 live rows and 16243 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 20000000084b7780 AND column1 > 72e1a473290068a8237d700d AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-2] 2021-06-29 15:03:14,127 ReadCommand.java:569 - Read 2302 live rows and 1747 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 20000000084b7780 AND column1 > 72e1ad117f0010b01b1b653002 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-6] 2021-06-29 15:03:21,222 ReadCommand.java:569 - Read 5000 live rows and 26464 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = e000000000146180 AND column1 >= 72e1 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-5] 2021-06-29 15:03:21,516 ReadCommand.java:569 - Read 5000 live rows and 42469 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = e000000000146180 AND column1 > 72e1a32b240040a85d714008 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
WARN  [ReadStage-6] 2021-06-29 15:03:21,586 ReadCommand.java:569 - Read 2020 live rows and 17155 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = e000000000146180 AND column1 > 72e1aa57046010b01704153c02 AND column1 < 72e2 LIMIT 5000 (see tombstone_warn_threshold)
INFO  [IndexSummaryManager:1] 2021-06-29 15:07:38,079 IndexSummaryRedistribution.java:78 - Redistributing index summaries
WARN  [ReadStage-1] 2021-06-29 15:37:18,841 ReadCommand.java:569 - Read 564 live rows and 11461 tombstone cells for query SELECT * FROM thehive.edgestore WHERE key = 7800000000b57d00 AND column1 >= 7ba0 AND column1 < 7ba1 LIMIT 5000 (see tombstone_warn_threshold)
```

**Comment by mamoedo** [comment]
I found the same crash when promoting an alert to a case:

`[INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-20 [00009af9|] 123.123.123.123 POST /api/alert/~696324120/createCase took 60014ms and returned 500 95 bytes`

Full logs:

```
2021-07-08 11:18:56,106 [ERROR] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-20 [00009af9|5f9207df] uncaught error, not retrying
java.util.concurrent.TimeoutException: Futures timed out after [1 minute]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
        at scala.concurrent.Await$.$anonfun$result$1(package.scala:223)
        at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:174)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3313)
        at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:172)
        at scala.concurrent.Await$.result(package.scala:146)
        at org.thp.thehive.services.CaseSrv.nextCaseNumber(CaseSrv.scala:145)
        at org.thp.thehive.services.CaseSrv.create(CaseSrv.scala:87)
        at org.thp.thehive.services.AlertSrv.$anonfun$createCase$8(AlertSrv.scala:263)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.services.AlertSrv.$anonfun$createCase$2(AlertSrv.scala:243)
        at scala.util.Failure.orElse(Try.scala:224)
        at org.thp.thehive.services.AlertSrv.$anonfun$createCase$1(AlertSrv.scala:243)
        at org.thp.thehive.services.AuditSrv.mergeAudits(AuditSrv.scala:84)
        at org.thp.thehive.services.AlertSrv.createCase(AlertSrv.scala:271)
        at org.thp.thehive.controllers.v0.AlertCtrl.$anonfun$createCase$11(AlertCtrl.scala:278)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.controllers.v0.AlertCtrl.$anonfun$createCase$9(AlertCtrl.scala:277)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.controllers.v0.AlertCtrl.$anonfun$createCase$4(AlertCtrl.scala:275)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.controllers.v0.AlertCtrl.$anonfun$createCase$3(AlertCtrl.scala:269)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.controllers.v0.AlertCtrl.$anonfun$createCase$2(AlertCtrl.scala:268)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$authPermittedTransaction$2(Entrypoint.scala:128)
        at org.thp.scalligraph.janus.JanusDatabase.$anonfun$tryTransaction$7(JanusDatabase.scala:241)
        at scala.util.Try$.apply(Try.scala:213)
        at org.thp.scalligraph.janus.JanusDatabase.$anonfun$tryTransaction$6(JanusDatabase.scala:241)
        at scala.util.Try$.apply(Try.scala:213)
        at org.thp.scalligraph.utils.DelayRetry.withTry(Retry.scala:93)
        at org.thp.scalligraph.janus.JanusDatabase.tryTransaction(JanusDatabase.scala:238)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$authPermittedTransaction$1(Entrypoint.scala:128)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$auth$1(Entrypoint.scala:86)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$asyncAuth$3(Entrypoint.scala:107)
        at org.scalactic.Good.fold(Or.scala:1229)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$asyncAuth$2(Entrypoint.scala:107)
        at org.thp.scalligraph.DiagnosticContext$.$anonfun$withRequest$2(ContextPropagatingDisptacher.scala:102)
        at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:108)
        at org.thp.scalligraph.DiagnosticContext$.withRequest(ContextPropagatingDisptacher.scala:99)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$asyncAuth$1(Entrypoint.scala:107)
        at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.$anonfun$invokeBlock$2(SessionAuthSrv.scala:100)
        at scala.Option.fold(Option.scala:251)
        at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.invokeBlock(SessionAuthSrv.scala:98)
        at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.invokeBlock(SessionAuthSrv.scala:95)
        at play.api.mvc.ActionBuilder$$anon$10.$anonfun$invokeBlock$2(Action.scala:408)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:441)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:439)
        at play.api.mvc.ActionBuilder$$anon$10.invokeBlock(Action.scala:408)
        at play.api.mvc.ActionBuilder$$anon$10.invokeBlock(Action.scala:404)
        at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:379)
        at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:168)
        at scala.util.Try$.apply(Try.scala:213)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:168)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:200)
        at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:418)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at org.thp.scalligraph.ContextPropagatingDispatcher$$anon$1.$anonfun$execute$2(ContextPropagatingDisptacher.scala:57)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.thp.scalligraph.DiagnosticContext$.$anonfun$withDiagnosticContext$2(ContextPropagatingDisptacher.scala:93)
        at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:108)
        at org.thp.scalligraph.DiagnosticContext$.withDiagnosticContext(ContextPropagatingDisptacher.scala:91)
        at org.thp.scalligraph.DiagnosticContext$$anon$2.withContext(ContextPropagatingDisptacher.scala:76)
        at org.thp.scalligraph.ContextPropagatingDispatcher$$anon$1.$anonfun$execute$1(ContextPropagatingDisptacher.scala:57)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-07-08 11:18:56,106 [ERROR] from org.thp.scalligraph.models.Database in application-akka.actor.default-dispatcher-20 [00009af9|5f9207df] Exception raised, rollback (Futures timed out after [1 minute])
2021-07-08 11:18:56,106 [ERROR] from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-20 [00009af9|5f9207df] Internal error
java.util.concurrent.TimeoutException: Futures timed out after [1 minute]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
        at scala.concurrent.Await$.$anonfun$result$1(package.scala:223)
        at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:174)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3313)
        at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:172)
        at scala.concurrent.Await$.result(package.scala:146)
        at org.thp.thehive.services.CaseSrv.nextCaseNumber(CaseSrv.scala:145)
        at org.thp.thehive.services.CaseSrv.create(CaseSrv.scala:87)
        at org.thp.thehive.services.AlertSrv.$anonfun$createCase$8(AlertSrv.scala:263)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.services.AlertSrv.$anonfun$createCase$2(AlertSrv.scala:243)
        at scala.util.Failure.orElse(Try.scala:224)
        at org.thp.thehive.services.AlertSrv.$anonfun$createCase$1(AlertSrv.scala:243)
        at org.thp.thehive.services.AuditSrv.mergeAudits(AuditSrv.scala:84)
        at org.thp.thehive.services.AlertSrv.createCase(AlertSrv.scala:271)
        at org.thp.thehive.controllers.v0.AlertCtrl.$anonfun$createCase$11(AlertCtrl.scala:278)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.controllers.v0.AlertCtrl.$anonfun$createCase$9(AlertCtrl.scala:277)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.controllers.v0.AlertCtrl.$anonfun$createCase$4(AlertCtrl.scala:275)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.controllers.v0.AlertCtrl.$anonfun$createCase$3(AlertCtrl.scala:269)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.controllers.v0.AlertCtrl.$anonfun$createCase$2(AlertCtrl.scala:268)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$authPermittedTransaction$2(Entrypoint.scala:128)
        at org.thp.scalligraph.janus.JanusDatabase.$anonfun$tryTransaction$7(JanusDatabase.scala:241)
        at scala.util.Try$.apply(Try.scala:213)
        at org.thp.scalligraph.janus.JanusDatabase.$anonfun$tryTransaction$6(JanusDatabase.scala:241)
        at scala.util.Try$.apply(Try.scala:213)
        at org.thp.scalligraph.utils.DelayRetry.withTry(Retry.scala:93)
        at org.thp.scalligraph.janus.JanusDatabase.tryTransaction(JanusDatabase.scala:238)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$authPermittedTransaction$1(Entrypoint.scala:128)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$auth$1(Entrypoint.scala:86)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$asyncAuth$3(Entrypoint.scala:107)
        at org.scalactic.Good.fold(Or.scala:1229)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$asyncAuth$2(Entrypoint.scala:107)
        at org.thp.scalligraph.DiagnosticContext$.$anonfun$withRequest$2(ContextPropagatingDisptacher.scala:102)
        at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:108)
        at org.thp.scalligraph.DiagnosticContext$.withRequest(ContextPropagatingDisptacher.scala:99)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$asyncAuth$1(Entrypoint.scala:107)
        at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.$anonfun$invokeBlock$2(SessionAuthSrv.scala:100)
        at scala.Option.fold(Option.scala:251)
        at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.invokeBlock(SessionAuthSrv.scala:98)
        at org.thp.scalligraph.auth.SessionAuthSrv$$anon$1.invokeBlock(SessionAuthSrv.scala:95)
        at play.api.mvc.ActionBuilder$$anon$10.$anonfun$invokeBlock$2(Action.scala:408)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:441)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:439)
        at play.api.mvc.ActionBuilder$$anon$10.invokeBlock(Action.scala:408)
        at play.api.mvc.ActionBuilder$$anon$10.invokeBlock(Action.scala:404)
        at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:379)
        at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:168)
        at scala.util.Try$.apply(Try.scala:213)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:168)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:200)
        at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:418)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at org.thp.scalligraph.ContextPropagatingDispatcher$$anon$1.$anonfun$execute$2(ContextPropagatingDisptacher.scala:57)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.thp.scalligraph.DiagnosticContext$.$anonfun$withDiagnosticContext$2(ContextPropagatingDisptacher.scala:93)
        at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:108)
        at org.thp.scalligraph.DiagnosticContext$.withDiagnosticContext(ContextPropagatingDisptacher.scala:91)
        at org.thp.scalligraph.DiagnosticContext$$anon$2.withContext(ContextPropagatingDisptacher.scala:76)
        at org.thp.scalligraph.ContextPropagatingDispatcher$$anon$1.$anonfun$execute$1(ContextPropagatingDisptacher.scala:57)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-07-08 11:18:56,106 [WARN] from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-20 [00009af9|5f9207df] POST /api/alert/~696324120/createCase returned 500
2021-07-08 11:18:56,110 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-20 [00009af9|] 123.123.123.123 POST /api/alert/~696324120/createCase took 60014ms and returned 500 95 bytes
2021-07-08 11:18:56,110 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-20 [|] An error occurs (org.thp.scalligraph.NotFoundError: Stream kWyC5Gk5BiqPIVP9cEeC doesn't exist), retrying (2)
2021-07-08 11:18:56,111 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-20 [|] An error occurs (org.thp.scalligraph.NotFoundError: Stream W9fqhsI4qWO9RcoKAvGU doesn't exist), retrying (2)
2021-07-08 11:18:56,111 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-20 [|] An error occurs (org.thp.scalligraph.NotFoundError: Stream hmaiubm4eYAEekCZF2Yy doesn't exist), retrying (2)
2021-07-08 11:18:56,111 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-20 [|] An error occurs (org.thp.scalligraph.NotFoundError: Stream YurLI5RAizfNI2Hnw2hG doesn't exist), retrying (2)
2021-07-08 11:18:56,111 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-20 [|] An error occurs (org.thp.scalligraph.NotFoundError: Stream 5ex9mCwVMkWVwD3v9rAk doesn't exist), retrying (2)
2021-07-08 11:18:56,111 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-20 [|] An error occurs (org.thp.scalligraph.NotFoundError: Stream jmDIVt33CopJmbaSn3uW doesn't exist), retrying (2)
2021-07-08 11:18:56,111 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-20 [|] An error occurs (org.thp.scalligraph.NotFoundError: Stream wZoxfUP25kU1Y0FGbqVp doesn't exist), retrying (2)
2021-07-08 11:18:56,111 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-20 [|] An error occurs (org.thp.scalligraph.NotFoundError: Stream PZwju8qSsgBQBoXHsHSW doesn't exist), retrying (2)
2021-07-08 11:18:56,111 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-20 [|] An error occurs (org.thp.scalligraph.NotFoundError: Stream l2anDe0gINKx6o86KK6Z doesn't exist), retrying (2)
2021-07-08 11:18:56,111 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-20 [|] An error occurs (org.thp.scalligraph.NotFoundError: Stream qcU5tIHs1h1jDP4QDVhf doesn't exist), retrying (2)
2021-07-08 11:18:56,111 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-20 [|] An error occurs (org.thp.scalligraph.NotFoundError: Stream EOxJbe8MI9cSTgqCsUQj doesn't exist), retrying (2)
2021-07-08 11:18:56,111 [WARN] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-20 [00009ae9|] An error occurs (org.thp.scalligraph.NotFoundError: Stream 8PEtzAnjegfQzP93cYKT doesn't exist), retrying (1)
```
