### ISSUE TITLE
Possibility to create Alert Data type via REST API?

### ISSUE THREAD

**Issue by astir1978** [TheHive-Project/TheHive#2165]
Alert creation via API fails due to missing Data Type i.e. observable if it is configured to be part of API request (e.g. "dataType": "severity").
Data Type (observable) can be added via GUI from admin panel, but is there way to add it automatically via REST API or CLI?

Or is there way to configure system so that it will accept unknown observables?

This is the error when observable is missing:
```
2021-08-11 09:10:37,180 [ERROR] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-14 [0000010c|73610ab8] uncaught error, not retrying
org.thp.scalligraph.NotFoundError: ObservableType severity not found
        at org.thp.scalligraph.services.VertexSrv.$anonfun$getOrFail$1(VertexSrv.scala:32)
        at scala.Option.fold(Option.scala:251)
        at org.thp.scalligraph.services.VertexSrv.getOrFail(VertexSrv.scala:32)
        at org.thp.thehive.controllers.v0.AlertCtrl.createObservable(AlertCtrl.scala:323)
        at org.thp.thehive.controllers.v0.AlertCtrl.$anonfun$create$10(AlertCtrl.scala:77)
...
```

Thanks!

**Comment by astir1978** [comment]
I think I found answer from source code already.

curl -XPOST -H 'Authorization: Bearer ***API*KEY*** ' -H 'Content-Type: application/json' http://127.0.0.1:9000/api/observable/type/ -d '{
  "name": "test_observable"
}'
