### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by artsec89** [TheHive-Project/TheHive#2194]
### Request Type

Question

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        |Ubuntu Server 18.04  |
| TheHive version              | 4.1.10-1           |
| MISP version                |  MISP 2.4.148            |

### Question

Hi Dears
I install and try to integrate with cortex and MISP for SOAR project. In cortex side everything is OK. In MISP, I config the MISP connector on application.log:

 play.modules.enabled += org.thp.thehive.connector.misp.MispModule
        misp {
        interval: 5 minute
  servers: [
    {
      name = "MISP"            # MISP name
      url = "https://misp.local/" # URL or MISP
      auth {
        type = key
        key = "z2rl5tBdfFC6ncsEgt5jpuG1VCjsqeQucktum8Co"             # MISP API key
      }
      wsConfig {}               # HTTP client configuration (SSL and proxy)
        statusCheckInterval = 1 minute

        }
  ]
}

But when login to thehive have this problem:

![Untitled](https://user-images.githubusercontent.com/45354865/132339631-e4560905-97f3-47e4-bd5d-ef8d4affd25a.jpg)

At first after search in google, i think this problem is about SSL.  I check thehive log file and find this:

2021-09-07 11:28:14,369 [INFO] from org.thp.thehive.connector.misp.services.MispActor in application-akka.actor.default-dispatcher-19 [|790b5093] Synchronising MISP events for MISP
2021-09-07 11:28:14,393 [ERROR] from org.thp.thehive.connector.misp.services.MispImportSrv in application-akka.actor.default-dispatcher-19 [|790b5093] Unable to get MISP organisation
org.thp.scalligraph.InternalError: MISP server MISP is inaccessible
        at org.thp.misp.client.MispClient.currentOrganisationName(MispClient.scala:47)
        at org.thp.thehive.connector.misp.services.MispImportSrv.syncMispEvents(MispImportSrv.scala:424)
        at org.thp.thehive.connector.misp.services.MispActor$$anonfun$receive$2.$anonfun$applyOrElse$5(MispActor.scala:35)
        at org.thp.thehive.connector.misp.services.MispActor$$anonfun$receive$2.$anonfun$applyOrElse$5$adapted(MispActor.scala:34)
        at org.thp.thehive.connector.misp.services.MispActor$$anonfun$receive$2.applyOrElse(MispActor.scala:34)
        at org.thp.thehive.connector.misp.services.MispActor.aroundReceive(MispActor.scala:12)
2021-09-07 11:28:14,394 [INFO] from org.thp.thehive.connector.misp.services.MispActor in application-akka.actor.default-dispatcher-19 [|790b5093] MISP synchronisation is complete

If anyone can help me about this issue?

**Comment by Jay-125** [comment]
@artsec89 I have faced the same issue earlier but successfully resolved it. 
Just add one line in log file where you have configured the misp :- 
wsConfig.ssl.loose.acceptAnyCertificate: true
It will resolve the issue.

**Comment by artsec89** [comment]
Thanks you @Jay-125 
But my problem not resolved.
I change Application.conf file like this:
play.modules.enabled += org.thp.thehive.connector.misp.MispModule
misp {
  interval: 1 hour
  servers: [
    {
      name = "MISP Server"
      url = "https://127.0.0.1"
      auth {
        type = key
        key = "***"
      }
      wsConfig {
        wsConfig.ssl.loose.acceptAnyCertificate: true
      }
      tags = ["tag1", "tag2", "tag3"]
      caseTemplate = "misp"
      includedTheHiveOrganisations = ["ORG1", "ORG2" ]
    }
  ]
}
But not resolved. Is any problem in my config file?

**Comment by Jay-125** [comment]
play.modules.enabled += org.thp.thehive.connector.misp.MispModule
misp {
interval: 1 hour
servers: [
{
name = "MISP Server"
url = "https://127.0.0.1"
auth {
type = key
key = "***"
}

wsConfig {}
wsConfig.ssl.loose.acceptAnyCertificate: true


tags = ["tag1", "tag2", "tag3"]
caseTemplate = "misp"
includedTheHiveOrganisations = ["ORG1", "ORG2" ]
}
]
}

Try doing like this.

**Comment by artsec89** [comment]
Hi @Jay-125 
Thanks for your help but not resolved.

**Comment by Jay-125** [comment]
@artsec89 
Okay . Which auth key you are using ?
I mean you are using admin auth key or you have created a new sync user and using that sync user's auth key ?
Because most of the time sync user's key create issues while syncing. so I recommend, first try with admin auth key, if it is successful, then try with other user's auth key.
 
And if you are still facing the same issue then I would recommend you to watch this video :-

https://www.youtube.com/watch?v=kyH1rkK6ch4
