### ISSUE TITLE
[Bug] Migration from 3.5 to 4.1.10 throws "entity content is too long" error

### ISSUE THREAD

**Issue by Kamforka** [TheHive-Project/TheHive#2207]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu 20.04   |
| OS version (client)        | N/A  |
| Virtualized  Env.          | True                           |
| Dedicated RAM              | 16 GB                                 |
| vCPU                       | 4                       |
| TheHive version / git hash | 4.1.10-1              |
| Package Type               |  Docker |
| Database                   | Cassandra /|
| Index type                 | Lucene |
| Attachments storage        | Local                  |
| Browser type & version     | N/A                         |

### Problem Description
I'm trying to migrate a TheHive 3.5 cluster to 4.x, the migration starts and it does some progress however it usually fails with the following errors:

```
[warn] Search error
com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: org.apache.http.ContentTooLongException: entity content is too long [177358627] for the configured buffer limit [104857600]
        at com.sksamuel.elastic4s.http.JavaClient$$anon$1.onFailure(JavaClient.scala:69)
        at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:644)
        at org.elasticsearch.client.RestClient$1.failed(RestClient.java:399)
        at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionFailed(DefaultClientExchangeHandlerImpl.java:101)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:426)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.exception(HttpAsyncRequestExecutor.java:163)
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:276)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
Caused by: org.apache.http.ContentTooLongException: entity content is too long [177358627] for the configured buffer limit [104857600]
        at org.elasticsearch.client.HeapBufferedAsyncResponseConsumer.onEntityEnclosed(HeapBufferedAsyncResponseConsumer.java:76)
        at org.apache.http.nio.protocol.AbstractAsyncResponseConsumer.responseReceived(AbstractAsyncResponseConsumer.java:137)
        at org.apache.http.impl.nio.client.MainClientExec.responseReceived(MainClientExec.java:315)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseReceived(DefaultClientExchangeHandlerImpl.java:151)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.responseReceived(HttpAsyncRequestExecutor.java:315)
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:255)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
[error] Migration failed
org.thp.scalligraph.SearchError: Request terminated early or timed out
        at org.thp.thehive.migration.th3.SearchWithScroll$$anon$1$$anon$2.$anonfun$onPull$1(DBFind.scala:198)
        at org.thp.thehive.migration.th3.SearchWithScroll$$anon$1$$anon$2.$anonfun$onPull$1$adapted(DBFind.scala:178)
        at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:466)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:498)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
```

### Steps to Reproduce
This is the migration command I'm running:
```bash
/opt/thehive/bin/migrate --output /etc/thehive/application.conf --main-organisation myorg --es-uri http://elasticsearch:9200 --es-index the_hive_17
```

### Possible Solutions
Seems like increasing the elasticsearch request buffer could solve the issue, maybe I can use the ` --es-pagesize <value>` option of the migration tool for that?

**Comment by Kamforka** [comment]
Seems like adding the following line to `elasticsearch.yml` solves the issue:

```yml
http.max_content_length: 200mb  # adjust to your need
```
