### ISSUE TITLE
Launching Responder from API

### ISSUE THREAD

**Issue by AlarisTMC** [TheHive-Project/TheHive#2235]
### Request Type
Bug  -- Maybe?

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu  |
| OS version (client)        | 18.04      |
| Virtualized  Env.          | AWS / Containerized (Docker)                       |
| Dedicated RAM              |                              |
| vCPU                       |                    |
| TheHive version / git hash | 3.4.2-1              |
| Package Type               | Docker  |
| Database                   |  |
| Index type                 |                 |
| Attachments storage        | Local              |
| Browser type & version     |                   |

### Problem Description
Attempting to launch a responder from API and getting error

### Steps to Reproduce
POST http://thehive:9000/api/connector/cortex/action

Body:
{ 
  "responderId": "1115e480d1e79a002b0493f1fde709d7", 
  "cortexId": "cortex1", 
  "objectType": "case", 
  "objectId": "QWJvzXwBBCBMXyfYpuAI" 
  }

Response:
{
    "type": "org.elastic4play.MissingAttributeError",
    "message": "Attribute action.objectType is missing"
} 

### Complementary information
Log entry:

[info] o.e.ErrorHandler - POST /api/connector/cortex/action returned 500
org.elastic4play.MissingAttributeError: Attribute action.objectType is missing
        at connectors.cortex.services.CortexActionSrv.$anonfun$executeAction$17(CortexActionSrv.scala:242)
        at scala.Option.fold(Option.scala:158)
        at connectors.cortex.services.CortexActionSrv.executeAction(CortexActionSrv.scala:242)
        at connectors.cortex.controllers.CortexCtrl.$anonfun$createAction$1(CortexCtrl.scala:240)
        at org.elastic4play.controllers.Authenticated$$anon$1.$anonfun$invokeBlock$1(Authenticated.scala:289)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)

**Comment by AlarisTMC** [comment]
Found the answer.    The POST did not include a content-type header of application/json.
