### ISSUE TITLE
not able to get all the alerts from misp

### ISSUE THREAD

**Issue by Shraddha10rathor** [TheHive-Project/TheHive#2242]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        |Ubuntu,  |
| OS version (client)        |  Ubuntu,         |
| Virtualized  Env.          | True / False                          |
| Dedicated RAM              | 9 GB                                 |
| vCPU                       | 4                       |
| TheHive version / git hash | 4.1.11             |
| Package Type               |  Docker|
| Database                   | Cassandra                 |
| Index type                 |  Elasticsearch                |

### Problem Description
After Integrating TheHive with MISP, not getting all the events as alerts.

### Steps to Reproduce

1. In MISP, there are 230 events.
2. Integrated TheHive with MISP.
3. Restarted TheHive wait for some time.

On UI, I am able to see only 30 alerts, where as in the MISP I have 230 events,

**Comment by Mikiped00** [comment]
I have the same problem as you, I could get an error about that. Hope it is useful:
```
[error] o.t.t.c.m.s.QueueIterator [|] Stream fails
java.util.concurrent.TimeoutException: Request timeout to 192.168.0.80/192.168.0.80:443 after 120000 ms
 	at play.shaded.ahc.org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
	at play.shaded.ahc.org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
	at play.shaded.ahc.io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680)
	at play.shaded.ahc.io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755)
	at play.shaded.ahc.io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483)
 	at play.shaded.ahc.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by MU-03** [comment]
I am facing the same issue with TheHive 4 , how can I resolve this?

**Comment by Pindinga1** [comment]
mismo problema.
