### ISSUE TITLE
[Bug] Cannot create new cases after migration

### ISSUE THREAD

**Issue by blainedw** [TheHive-Project/TheHive#2243]
Recently upgraded and migrated data from theHive 3.4.3 to 4.0.5 to 4.1.9 running on RHEL7.9. Installation is on a standalone server. Database is cassandra/lucene. I can't create a new case (although I can update all current cases). The UI states "CaseCreationCtrl: User not found".

**Comment by blainedw** [comment]
Determined that there is no admin organization

**Comment by blainedw** [comment]
I'm sure this also has impact on why I can't create a new case (although I can update all current cases). Here is the stack trace:

2021-11-12 12:38:44,691 [ERROR] from org.thp.scalligraph.utils.Retry in application-akka.actor.default-dispatcher-14 [0000038f|0d70dbf3] uncaught error, not retrying
org.thp.scalligraph.NotFoundError: User not found
        at org.thp.scalligraph.traversal.TraversalOps$TraversalOpsDefs.getOrFail(TraversalOps.scala:145)
        at org.thp.thehive.services.CaseSrv.$anonfun$createTask$1(CaseSrv.scala:198)
        at scala.Option.map(Option.scala:230)
        at org.thp.thehive.services.CaseSrv.createTask(CaseSrv.scala:198)
        at org.thp.thehive.services.CaseSrv.$anonfun$create$16(CaseSrv.scala:106)
        at org.thp.scalligraph.package$RichSeq.$anonfun$toTry$3(package.scala:17)
        at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
        at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
        at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:49)
        at org.thp.scalligraph.package$RichSeq.toTry(package.scala:16)
        at org.thp.thehive.services.CaseSrv.$anonfun$create$12(CaseSrv.scala:106)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.services.CaseSrv.$anonfun$create$10(CaseSrv.scala:105)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.services.CaseSrv.$anonfun$create$9(CaseSrv.scala:104)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.services.CaseSrv.$anonfun$create$7(CaseSrv.scala:103)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.services.CaseSrv.$anonfun$create$4(CaseSrv.scala:91)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.services.CaseSrv.create(CaseSrv.scala:90)
        at org.thp.thehive.controllers.v0.CaseCtrl.$anonfun$create$11(CaseCtrl.scala:62)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.controllers.v0.CaseCtrl.$anonfun$create$9(CaseCtrl.scala:61)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.controllers.v0.CaseCtrl.$anonfun$create$6(CaseCtrl.scala:60)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.thp.thehive.controllers.v0.CaseCtrl.$anonfun$create$4(CaseCtrl.scala:54)
        at org.thp.scalligraph.controllers.Entrypoint$EntryPointBuilder.$anonfun$authTransaction$2(Entrypoint.scala:77)
        at org.thp.scalligraph.janus.JanusDatabase.$anonfun$tryTransaction$7(JanusDatabase.scala:241)
        at scala.util.Try$.apply(Try.scala:213)

**Comment by blainedw** [comment]
Here is the first part of the mgration (no other errors later)

Migration-akka.actor.default-dispatcher-6 [|] [initialisation]
2021-11-10 15:40:21,760 [INFO] from org.thp.scalligraph.models.Database in main [|] Instantiate JanusDatabase using cql backend
2021-11-10 15:40:27,794 [INFO] from org.thp.thehive.migration.Migrate in TheHiveMigration-akka.actor.default-dispatcher-6 [|] [Prepare database]
2021-11-10 15:40:29,661 [INFO] from org.thp.thehive.migration.th4.Output in main [|] Already migrated:
 4 profiles
 1 organisations
 2 users
 3 impactStatuses
 5 resolutionStatuses
 16 observableTypes
 0 customFields
 0 caseTemplates
 0 caseNumbers
 0 alerts
2021-11-10 15:40:37,799 [INFO] from org.thp.thehive.migration.Migrate in TheHiveMigration-akka.actor.default-dispatcher-12 [|] [Prepare database]
2021-11-10 15:40:47,792 [INFO] from org.thp.thehive.migration.Migrate in TheHiveMigration-akka.actor.default-dispatcher-11 [|] [Prepare database]
2021-11-10 15:40:57,792 [INFO] from org.thp.thehive.migration.Migrate in TheHiveMigration-akka.actor.default-dispatcher-13 [|] [Prepare database]
2021-11-10 15:41:08,061 [INFO] from org.thp.thehive.migration.Migrate in TheHiveMigration-akka.actor.default-dispatcher-14 [|] [Prepare database]
2021-11-10 15:41:17,782 [INFO] from org.thp.thehive.migration.Migrate in TheHiveMigration-akka.actor.default-dispatcher-14 [|] [Prepare database]
2021-11-10 15:41:27,792 [INFO] from org.thp.thehive.migration.Migrate in TheHiveMigration-akka.actor.default-dispatcher-6 [|] [Prepare database]
2021-11-10 15:41:37,792 [INFO] from org.thp.thehive.migration.Migrate in TheHiveMigration-akka.actor.default-dispatcher-16 [|] [Prepare database]
2021-11-10 15:41:47,797 [INFO] from org.thp.thehive.migration.Migrate in TheHiveMigration-akka.actor.default-dispatcher-17 [|] [Prepare database]
2021-11-10 15:41:57,782 [INFO] from org.thp.thehive.migration.Migrate in TheHiveMigration-akka.actor.default-dispatcher-18 [|] [Prepare database]
2021-11-10 15:42:07,793 [INFO] from org.thp.thehive.migration.Migrate in TheHiveMigration-akka.actor.default-dispatcher-20 [|] [Prepare database]
Migration-akka.actor.default-dispatcher-26 [|] [Migrate users] Organisation:1/1(1718ms) User:8/30(832ms)
2021-11-10 15:43:17,807 [INFO] from org.thp.thehive.migration.Migrate in TheHiveMigration-akka.actor.default-dispatcher-25 [|] [Migrate case templates] CaseTemplate/Task:25(123ms) Organisation:1/1 ObservableType:1/15(507ms) CaseTemplate:1/14(535ms) User:30/30(138ms) CustomField:13/13(30ms)
2021-11-10 15:43:27,855 [INFO] from org.thp.thehive.migration.Migrate in TheHiveMigration-akka.actor.default-dispatcher-24 [|] [Migrate case templates] CaseTemplate/Task:184(37ms) Organisation:1/1 ObservableType:1/15 CaseTemplate:14/14(93ms) User:30/30 CustomField:13/13

**Comment by blainedw** [comment]
I found the solution to this problem. Several templates had the template owner changed to an invalid user. I exported them and did a global find/replace to fix this and reimported them.
