### ISSUE TITLE
[Bug] Export case to MISP with attachment

### ISSUE THREAD

**Issue by Linow974** [TheHive-Project/TheHive#2426]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Debian 10  |
| OS version (client)        | Debian 10            |
| Virtualized  Env.          | True                           |
| Dedicated RAM              | 8 GB                                 |
| vCPU                       | 4                      |
| TheHive version / git hash | 4.x               |
| Package Type               | DEB |
| Database                   |  BerlkelyDB                |
| Index type                 | Lucene               |
| Attachments storage        | Local                |

### Problem Description

Export TheHive case to MISP create error "CaseExportCtrl: An unexpected error occurred while exporting case" occurs.

### Steps to Reproduce

1. Create case with an observable containing an attachment (regardless of the extension)
1. Export case to MISP

### Complementary information

I have a TheHive test VM on which the version of TheHive was very old (3.4), but with this version the case export with attachment worked without error... As soon as I did the update, I I did the test again with the same attachment and create this error but the case and the file are exported to MISP.

**Comment by Linow974** [comment]
Sorry, logs from application.log : 

```
2022-10-12 17:01:38,106 [INFO] from org.thp.thehive.connector.misp.services.MispExportSrv in application-akka.actor.default-dispatcher-13 [0000009f|] Exporting case 60 to MISP MISP
2022-10-12 17:01:38,407 [ERROR] from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-14 [|] Internal error
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (StringReader); line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2005)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4684)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4561)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2798)
	at play.api.libs.json.jackson.JacksonJson$.parseJsValue(JacksonJson.scala:285)
	at play.api.libs.json.StaticBinding$.parseJsValue(StaticBinding.scala:17)
	at play.api.libs.json.Json$.parse(Json.scala:173)
	at play.api.libs.ws.JsonBodyReadables.$anonfun$readableAsJson$1(JsonBodyReadables.scala:27)
	at play.api.libs.ws.StandaloneWSResponse.body(StandaloneWSResponse.scala:112)
	at play.api.libs.ws.StandaloneWSResponse.body$(StandaloneWSResponse.scala:110)
	at play.api.libs.ws.ahc.StandaloneAhcWSResponse.body(StandaloneAhcWSResponse.scala:17)
	at play.api.libs.ws.ahc.AhcWSResponse.json(AhcWSResponse.scala:93)
	at org.thp.misp.client.MispClient.$anonfun$post$8(MispClient.scala:104)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.thp.scalligraph.ContextPropagatingDispatcher$$anon$1.$anonfun$execute$2(ContextPropagatingDisptacher.scala:57)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.thp.scalligraph.DiagnosticContext$.$anonfun$withDiagnosticContext$2(ContextPropagatingDisptacher.scala:93)
	at org.thp.scalligraph.DiagnosticContext$.saveDiagnosticContext(ContextPropagatingDisptacher.scala:114)
	at org.thp.scalligraph.DiagnosticContext$.withDiagnosticContext(ContextPropagatingDisptacher.scala:91)
	at org.thp.scalligraph.DiagnosticContext$$anon$2.withContext(ContextPropagatingDisptacher.scala:76)
	at org.thp.scalligraph.ContextPropagatingDispatcher$$anon$1.$anonfun$execute$1(ContextPropagatingDisptacher.scala:57)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

```
