### ISSUE TITLE
Using OpenSearch in TheHive

### ISSUE THREAD

**Issue by ehsankhodayar** [TheHive-Project/TheHive#2440]
Hi,

I couldn't find the relevant section to TheHive 5, so I am asking my question here. Is it possible to use OpenSearch instead of Elasticsearch in TheHive?

**Comment by baonq-me** [comment]
I got this exception

```
java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.es.ElasticSearchIndex
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:64)
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:440)
	at org.janusgraph.diskstorage.Backend.getIndexes(Backend.java:427)
	at org.janusgraph.diskstorage.Backend.<init>(Backend.java:150)
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1359)
	at org.janusgraph.graphdb.database.StandardJanusGraph.<init>(StandardJanusGraph.java:146)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:161)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:132)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:112)
	at org.thp.scalligraph.janus.JanusDatabase$.$anonfun$openDatabase$3(JanusDatabase.scala:62)
	at org.thp.scalligraph.utils.DelayRetry.org$thp$scalligraph$utils$DelayRetry$$runSync(Retry.scala:110)
	at org.thp.scalligraph.utils.DelayRetry.org$thp$scalligraph$utils$DelayRetry$$runSync(Retry.scala:116)
	at org.thp.scalligraph.utils.DelayRetry.org$thp$scalligraph$utils$DelayRetry$$runSync(Retry.scala:116)
	at org.thp.scalligraph.utils.DelayRetry.sync(Retry.scala:83)
	at org.thp.scalligraph.janus.JanusDatabase$.openDatabase(JanusDatabase.scala:62)
	at org.thp.scalligraph.janus.JanusDatabaseProvider.$anonfun$get$3(JanusDatabaseProvider.scala:114)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.thp.scalligraph.ContextPropagatingDispatcher$$anon$1.$anonfun$execute$2(ContextPropagatingDisptacher.scala:57)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.thp.scalligraph.DiagnosticContext$$anon$2.withContext(ContextPropagatingDisptacher.scala:77)
	at org.thp.scalligraph.ContextPropagatingDispatcher$$anon$1.$anonfun$execute$1(ContextPropagatingDisptacher.scala:57)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:58)
	... 32 common frames omitted
Caused by: org.janusgraph.diskstorage.PermanentBackendException: Error executing request: Forbidden
	at org.janusgraph.diskstorage.es.ElasticSearchIndex.setupStoredScriptIfNeeded(ElasticSearchIndex.java:373)
	at org.janusgraph.diskstorage.es.ElasticSearchIndex.setupStoredScripts(ElasticSearchIndex.java:354)
	at org.janusgraph.diskstorage.es.ElasticSearchIndex.<init>(ElasticSearchIndex.java:342)
	... 37 common frames omitted
Caused by: java.io.IOException: Error executing request: Forbidden
	at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.getStoredScript(RestElasticSearchClient.java:235)
	at org.janusgraph.diskstorage.es.ElasticSearchIndex.setupStoredScriptIfNeeded(ElasticSearchIndex.java:365)
	... 39 common frames omitted
^C
```

**Comment by sandervandegeijn** [comment]
We would like this very much as well.
