### ISSUE TITLE
[Question] What is the issue with MISP configuration when I get the following error:Unable to get MISP organisation

### ISSUE THREAD

**Issue by TPower2112** [TheHive-Project/TheHive#2448]
[application.log](https://github.com/TheHive-Project/TheHive/files/10418513/application.log)
### Request Type

Question

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu 20.04   |
| OS version (client)        | Win 11|
| Virtualized  Env.          | True  - VMware|
| Dedicated RAM              | 4 GB                                 |
| vCPU                       | 4                      |
| TheHive version / git hash | 5            |
| Package Type               | DEB, From source |
| Database                   | Cassandra               |
| Index type                 | Lucene                 |
| Attachments storage        | Local                |
| Browser type & version     | Google Chrome Version 109.0.5414.75 (Official Build) (64-bit)                         |

### Question
What is the issue with the MISP configuration?  (see attached application log for more details)
2023-01-14 13:28:10,361 [INFO] from org.thp.thehive.connector.misp.services.MispActor in application-akka.actor.default-dispatcher-16 [|] MISP synchronisation is complete
2023-01-14 13:29:10,374 [INFO] from org.thp.thehive.connector.misp.services.MispActor in application-akka.actor.default-dispatcher-16 [|] Synchronising MISP events for MISP
2023-01-14 13:29:10,559 [ERROR] from org.thp.thehive.connector.misp.services.MispImportSrv in application-akka.actor.default-dispatcher-16 [|] Unable to get MISP organisation
org.thp.scalligraph.InternalError: MISP server MISP is inaccessible
	at org.thp.misp.client.MispClient.currentOrganisationName(MispClient.scala:62)
	at org.thp.thehive.connector.misp.services.MispImportSrv.syncMispEvents(MispImportSrv.scala:505)
	at org.thp.thehive.connector.misp.services.MispActor$$anonfun$receive$2.$anonfun$applyOrElse$8(MispActor.scala:76)
	at kamon.ContextStorage.runWithContext(ContextStorage.scala:67)

My MISP instance is configured with a cert and I can log into the https site from different browsers.
I added the MISP instance IP address to the Hive etc/hosts file since it is a dev environment. 

Any help would be appreciated.

Thanks.
TP

**Comment by blainedw** [comment]
Did you ever get a resolution? I'm having the same problem.

**Comment by blainedw** [comment]
Try this
https://github.com/MISP/MISP/issues/10379
