### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by DigiAngel** [TheHive-Project/TheHive#468]
# Fails to start

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16
| OS version (client)       | 10
| TheHive version / git hash   | 3.0.4-1
| Package Type              | DEB
| Browser type & version    | not applicable

### Problem Description
Fails to start.

### Steps to Reproduce
1. sudo systemctl start thehive

### Complementary information
The entire application.log:
~~~
2018-02-06 16:00:19,659 [INFO] from org.reflections.Reflections in main - Reflections took 159 ms to scan 5 urls, producing 115 keys and 1153 values
2018-02-06 16:00:19,690 [INFO] from module in main - Loading model class models.ArtifactModel
2018-02-06 16:00:19,692 [INFO] from module in main - Loading model class models.TaskModel
2018-02-06 16:00:19,692 [INFO] from module in main - Loading model class models.CaseModel
2018-02-06 16:00:19,692 [INFO] from module in main - Loading model class models.AlertModel
2018-02-06 16:00:19,692 [INFO] from module in main - Loading model class models.UserModel
2018-02-06 16:00:19,694 [INFO] from module in main - Loading model class org.elastic4play.services.DBListModel
2018-02-06 16:00:19,694 [INFO] from module in main - Loading model class models.AuditModel
2018-02-06 16:00:19,694 [INFO] from module in main - Loading model class org.elastic4play.services.AttachmentModel
2018-02-06 16:00:19,694 [INFO] from module in main - Loading model class models.LogModel
2018-02-06 16:00:19,696 [INFO] from module in main - Loading model class models.DashboardModel
2018-02-06 16:00:19,696 [INFO] from module in main - Loading model class models.CaseTemplateModel
2018-02-06 16:00:19,696 [INFO] from module in main - Loading model class connectors.cortex.models.JobModel
2018-02-06 16:00:19,696 [INFO] from module in main - Loading model class connectors.cortex.models.ReportTemplateModel
2018-02-06 16:00:20,760 [INFO] from akka.event.slf4j.Slf4jLogger in application-akka.actor.default-dispatcher-2 - Slf4jLogger started
2018-02-06 16:00:21,336 [INFO] from org.elasticsearch.plugins.PluginsService in main - no modules loaded
2018-02-06 16:00:21,338 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
2018-02-06 16:00:21,338 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
2018-02-06 16:00:21,339 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
2018-02-06 16:00:21,339 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
2018-02-06 16:00:21,339 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
2018-02-06 16:00:21,339 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018-02-06 16:00:22,267 [INFO] from io.netty.util.internal.PlatformDependent in main - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
2018-02-06 16:00:23,335 [INFO] from akka.actor.CoordinatedShutdown in application-akka.actor.default-dispatcher-2 - Starting coordinated shutdown from JVM shutdown hook
~~~

/etc/thehive/application.conf:
~~~
search {
  index = the_hive
  cluster = hive
  host = ["127.0.0.1:9300"]
  keepalive = 1m
  pagesize = 50
}

auth {
        provider = [local]
}
~~~

/etc/elasticsearch/elasticsearch.yml
~~~
cluster.name: hive
~~~

Anything I can do to troubleshoot this?  Thank you.

**Comment by To-om** [comment]
If it really fails to start, you should have more logs. Can you try to start it manually using: `/opt/thehive/bin/thehive -Dconfig.file=/etc/thehive/application.conf -Dlogger.file=/etc/thehive/logback.xml` ?

**Comment by nadouani** [comment]
@DigiAngel any updates?

**Comment by DigiAngel** [comment]
Thanks all....I'll try this out again on Monday and report my findings...sorry for the delay.

**Comment by DigiAngel** [comment]
Ok here we go....application secret?
~~~
[info] o.r.Reflections - Reflections took 150 ms to scan 5 urls, producing 115 keys and 1153 values
[info] module - Loading model class org.elastic4play.services.AttachmentModel
[info] module - Loading model class models.DashboardModel
[info] module - Loading model class connectors.cortex.models.JobModel
[info] module - Loading model class models.LogModel
[info] module - Loading model class models.AuditModel
[info] module - Loading model class models.ArtifactModel
[info] module - Loading model class models.CaseModel
[info] module - Loading model class models.UserModel
[info] module - Loading model class org.elastic4play.services.DBListModel
[info] module - Loading model class models.CaseTemplateModel
[info] module - Loading model class models.AlertModel
[info] module - Loading model class connectors.cortex.models.ReportTemplateModel
[info] module - Loading model class models.TaskModel
[info] a.e.s.Slf4jLogger - Slf4jLogger started
[info] o.e.p.PluginsService - no modules loaded
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
[info] i.n.u.i.PlatformDependent - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
Oops, cannot start the server.
Configuration error: Configuration error[
The application secret has not been set, and we are in prod mode. Your application is not secure.
To set the application secret, please read http://playframework.com/documentation/latest/ApplicationSecret
          ]
        at play.api.Configuration$.configError(Configuration.scala:155)
        at play.api.Configuration.reportError(Configuration.scala:985)
        at play.api.http.HttpConfiguration$.getSecretConfiguration(HttpConfiguration.scala:253)
        at play.api.http.HttpConfiguration$.fromConfiguration(HttpConfiguration.scala:238)
        at play.api.http.HttpConfiguration$HttpConfigurationProvider.get$lzycompute(HttpConfiguration.scala:284)
        at play.api.http.HttpConfiguration$HttpConfigurationProvider.get(HttpConfiguration.scala:284)
        at play.api.http.HttpConfiguration$HttpConfigurationProvider.get(HttpConfiguration.scala:283)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
[info] a.a.CoordinatedShutdown - Starting coordinated shutdown from JVM shutdown hook
~~~

**Comment by DigiAngel** [comment]
Bah..it's only at the start of the file 8-|
# Secret Key
# The secret key is used to secure cryptographic functions.
# WARNING: If you deploy your application on several servers, make sure to use the same key.

**Comment by DigiAngel** [comment]
And running fine now...sorry for the noise all..helps if I...you know...read.
