### ISSUE TITLE
Tasks are stripped when merging cases

### ISSUE THREAD

**Issue by dotwayland** [TheHive-Project/TheHive#489]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 14.04.5 LTS
| OS version (client)       | Windows 10
| TheHive version / git hash   | 3.0.5
| Package Type              | DEB
| Browser type & version    | Chrome 63.0.3239.132 (Official Build) (64-bit)

### Problem Description
Tasks are stripped when merging cases

### Steps to Reproduce
1. Create a case manually or from template, and add some tasks to it 
2. Create a second case manually or from template and add some tasks to it
3. Merge the two cases

### Complementary information
2018-02-12 14:47:12,934 [WARN] from services.CaseMergeSrv in application-akka.actor.default-dispatcher-4488 - Task creation fails
org.elastic4play.AttributeCheckingError: [Unknown attribute case_task._version: {"type":"JsonInputValue","value":1}]
	at org.elastic4play.services.FieldsSrv.$anonfun$parse$7(FieldsSrv.scala:30)
	at org.scalactic.Bad.transform(Or.scala:1386)
	at org.elastic4play.services.FieldsSrv.parse(FieldsSrv.scala:30)
	at org.elastic4play.services.CreateSrv.create(CreateSrv.scala:108)
	at org.elastic4play.services.CreateSrv.$anonfun$apply$7(CreateSrv.scala:95)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at org.elastic4play.services.CreateSrv.apply(CreateSrv.scala:94)
	at services.TaskSrv.create(TaskSrv.scala:43)
	at services.CaseMergeSrv$$anonfun$mergeTasksAndLogs$14.$anonfun$applyOrElse$6(CaseMergeSrv.scala:185)
	at akka.stream.impl.fusing.MapAsyncUnordered$$anon$24.onPush(Ops.scala:1250)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:401)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:728)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:743)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:653)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by saadkadhi** [comment]
Thanks @dotwayland. This is an ugly regression that we'll squash promptly. Stay tuned.
