### ISSUE TITLE
No Route To Host? TheHive Error When Attempting to Connect to MISP

### ISSUE THREAD

**Issue by Theory5** [TheHive-Project/TheHive#492]
Hello,

I've been working to setup The Hive (via Docker-Compose) and connect a docker instance of MISP to it. Unfortunately, while I do now get the symbol that shows the MISP connector functioning, it's red and I only see this on my TheHive instance:

![hivemispunknown](https://user-images.githubusercontent.com/6132967/36322094-1ad84646-131a-11e8-98cd-b5052b042b47.PNG)

I THINK I have a solution, since I used the mostly default settings in docker-compose.yml, and MISP default settings where it uses port 443, that I may need to setup full TLS communications and certs. 

But BEFORE I do this, I need direction as adding full TLS to all webservers always increases the complexity of troubleshooting, and the error messages I get when starting docker-compose.yml do not seem to directly point to TLS issues.

Here is the sanitized log output of "docker-compose up". The formatting is a little weird in this output, adding some weird characters. 

http://termbin.com/k97b

The only changes I made to sanitize it were to take the domain I'm on and change it to placeholder.com 

What I believe highlights part of the issue is the line:

^[[32mthehive_1        |^[[0m Caused by: java.net.NoRouteToHostException: No route to host

and stuff below it.

Can someone please take a look and assist? Have you seen this before? What do you think? 

My The Hive application.conf can be found here:

http://termbin.com/sbuo

If I'm doing something wrong please let me know! Thanks in advance, and let me know what else is needed for assistance!

**Comment by To-om** [comment]
Hi,
The error message "No route to host" means that the docker container on which TheHive run can't contact you MISP server because no route are configured to that destination.
The default behavior of docker service configure a default route for all container. Have you customized network configuration of your docker service ?

Another possible cause is that your MISP server is shutdown or disconnected to network.

**Comment by Theory5** [comment]
The Hive creates a bridge called thehive_default. The output (partial) from the command "docker network inspect thehive_default" is this:

`[
    {
        "Name": "thehive_default",
        "Id": "7cdeef266e87b5cabb4703ada137c814fde66111e19d4ce875de8c2a8d9f891d",
        "Created": "2018-02-15T16:12:23.046476728-05:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "1c901c6c37e51f835e80aa26feaa2d9da9e7dc72b72438209e51a863bf3abc3b": {
                "Name": "romantic_brattain",
                "EndpointID": "a52379fe59d2790bad82b418df1283463817970640cc3d2307ca3f4a0878a436",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            },
            "4ddeb066da87771f7d2ec579f9f30d8c65b95f44b6d519cb3b645786af7bb460": {
                "Name": "thehive_cortex_1",
                "EndpointID": "54c3ec048e6c653c936a8afa5f908e75d847acfe0ffd1ce333e7bef99790762b",
                "MacAddress": "02:42:ac:13:00:04",
                "IPv4Address": "172.19.0.4/16",
                "IPv6Address": ""
            },
            "b8f6b8aa0dbae8e5a7a2f21634304f95e5af2278de4c9c2fefcd3dcb62ab3729": {
                "Name": "thehive_thehive_1",
                "EndpointID": "edf1b8ffb98464b121d491f011ac0ae15e4771446a6b6c58a25c10e7a9e3132e",
                "MacAddress": "02:42:ac:13:00:05",
                "IPv4Address": "172.19.0.5/16",
                "IPv6Address": ""
            },
            "e49186e31a94354462c9e9d2673c42974c4d1d184a86202a24e7a4ac1031f7b0": {
                "Name": "thehive_elasticsearch_1",
                "EndpointID": "071d1d2f464c3765c687a38e46b44b92c26d201b971833aa01fa571007e92726",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "thehive"
        }
    }
]`

Romantic Brattain is the MISP docker container. 

Is there more to this than just adding hte container to that bridge? None of the other networks seem to hold any of TheHive's network connections, just this. 

Thanks!

**Comment by Theory5** [comment]
Hello @To-om , what I posted should (hopefully) prove that what you initially told me to look at is correct, and another issue is at play.

Do you need more information from me? Or are you just busy, in which case please ignore this and I'll be happy when you are able to give me some help!

**Comment by TPower2112** [comment]
I had the same error message:
Caused by: org.thp.misp.client.MispClientException: Error when connecting to misp server 'MISP01' on 'https://misp.local.test'
        at org.thp.misp.client.MispClient.onResponse(MispClient.scala:92)
        at org.thp.misp.client.MispClient.$anonfun$get$2(MispClient.scala:97)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:475)
Caused by: java.net.ConnectException: No route to host: misp.local.test/192.168.38.136:443
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        ... 5 common frames omitted
Caused by: java.net.ConnectException: No route to host: misp.local.test/192.168.38.136:443
        at play.shaded.ahc.org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
        at play.shaded.ahc.org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
        at play.shaded.ahc.org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
        at play.shaded.ahc.org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
        at play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
        at play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
        at play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
        at play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at play.shaded.ahc.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)

Based on the below error message, I enabled, under SSL Settings, "Do not check Cert Authority" and "Disable hostname Verification." 
That resolved the issue with the Hive not connecting to the MISP instance.   

Caused by: java.net.ConnectException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at play.shaded.ahc.org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
        at play.shaded.ahc.org.asynchttpclient.netty.channel.NettyConnectListener$1.onFailure(NettyConnectListener.java:151)
        at play.shaded.ahc.org.asynchttpclient.netty.SimpleFutureListener.operationComplete(SimpleFutureListener.java:26)
