### ISSUE TITLE
MISP Synchronisation error

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#522]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven using Chrome Browser
| TheHive version / git hash   | 3.0.7
| Package Type              | DEB

### Problem Description
MISP updating failes with tons of error messages.
The log messages does not help to identify if this is an error on MISP or on TheHive side.

The Logfile of TheHive grows within short time to arround 10 MB.

```
2018-04-03 11:34:45,397 [INFO] from connectors.misp.MispConnection in main - Add MISP connection misp-malware-sharing-development
  url:              https://misp-test.demo.tld
  proxy:            None
  case template:    <not set>
  artifact tags:    misp
  filters:
    max age:        <not set>
    max attributes: <not set>
    max size:       <not set>
    excluded orgs:
    excluded tags:
2018-04-03 11:35:47,365 [INFO] from connectors.misp.MispSynchro in application-akka.actor.default-dispatcher-6 - Misp synchronization completed
2018-04-03 11:35:47,368 [WARN] from connectors.misp.MispSynchro in application-akka.actor.default-dispatcher-6 - Update MISP error
org.elastic4play.AttributeCheckingError: [Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-...

        at org.elastic4play.services.UpdateSrv.$anonfun$checkAttributes$5(UpdateSrv.scala:46)
        at org.scalactic.Bad.fold(Or.scala:1387)
        at org.elastic4play.services.UpdateSrv.checkAttributes(UpdateSrv.scala:46)
        at org.elastic4play.services.UpdateSrv.$anonfun$doUpdate$1(UpdateSrv.scala:52)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-04-03 11:35:47,485 [WARN] from connectors.misp.MispSynchro in application-akka.actor.default-dispatcher-6 - Update MISP error

org.elastic4play.AttributeCheckingError: [Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataType is read-only][Attribute message is read-only][Attribute tlp is read-only][Attribute tags is read-only][Attribute startDate is read-only][Attribute data is read-only][Attribute dataTy
```

**Comment by axpatito** [comment]
+1 on this bug.

In my case it also broke the connection with Cortex.
