### ISSUE TITLE
A client error occurred on GET /index.html : Resource not found by Assets controller

### ISSUE THREAD

**Issue by Xiobe** [TheHive-Project/TheHive#587]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS 7 x64
| OS version (client)       |  Linux Mint 18.1 Serena
| TheHive version / git hash   | commit bd257eb (Apr 13 2018)
| Package Type              | From source
| Browser type & version   | Firefox 59.0.2 (64-bit)

### Problem Description
I am trying to write a script for another party (they require IPv4) that basically builds them an instance of The Hive on a Centos 7 platform. I found a couple of issues with the documentation I was able to resolve and opened a couple of tickets for them. 

I think I am at the end of the compilation but there seems to be an issue. The compilation was successful, the elasticsearch is running and thehive too. When I make my connection I get

> A client error occurred on GET /index.html : Resource not found by Assets controller

### Steps to Reproduce
This is my script without any of the specifics for the environment (like IPv6 disabled, host configuration, and comments)
>sudo yum -y update
>sudo yum -y install java-1.8.0-openjdk.x86_64
>sudo touch /etc/yum.repos.d/elasticsearch.repo
>echo '[elasticsearch-5.x]' | sudo tee -a /etc/yum.repos.d/elasticsearch.repo
>echo 'name=Elasticsearch repository for 5.x packages' | sudo tee -a /etc/yum.repos.d/elasticsearch.repo
>echo 'baseurl=https://artifacts.elastic.co/packages/5.x/yum' | sudo tee -a /etc/yum.repos.d/elasticsearch.repo
>echo 'gpgcheck=1' | sudo tee -a /etc/yum.repos.d/elasticsearch.repo
echo 'gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch' | sudo tee -a /etc/yum.repos.d/elasticsearch.repo
>echo 'enabled=1' | sudo tee -a /etc/yum.repos.d/elasticsearch.repo
>echo 'autorefresh=1' | sudo tee -a /etc/yum.repos.d/elasticsearch.repo
>echo 'type=rpm-md' | sudo tee -a /etc/yum.repos.d/elasticsearch.repo
>sudo yum -y update
>sudo yum -y install elasticsearch
>echo 'cluster.name: hive' | sudo tee -a  /etc/elasticsearch/elasticsearch.yml
>echo 'node.name: "hive_node1"' | sudo tee -a  /etc/elasticsearch/elasticsearch.yml
>echo 'network.host: 127.0.0.1' | sudo tee -a /etc/elasticsearch/elasticsearch.yml
>echo 'script.inline: on' | sudo tee -a /etc/elasticsearch/elasticsearch.yml
>echo 'thread_pool.index.queue_size: 100000' | sudo tee -a /etc/elasticsearch/elasticsearch.yml
>echo 'thread_pool.search.queue_size: 100000' | sudo tee -a /etc/elasticsearch/elasticsearch.yml
>echo 'thread_pool.bulk.queue_size: 100000' | sudo tee -a /etc/elasticsearch/elasticsearch.yml
>sudo systemctl enable elasticsearch.service
>sudo yum -y install git bzip2 java-1.8.0-openjdk-devel epel-release nodejs
>sudo npm install -g grunt-cli bower semver
>cd /opt
>git clone https://github.com/CERT-BDF/TheHive.git
>/opt/TheHive/bin/activator clean compile stage dist
>sudo cp -r /opt/TheHive/target/universal/stage /opt/thehive
>ln -s /var/log/thehive/ /opt/thehive/logs
>sudo mkdir -p /etc/thehive
>sudo cp /opt/thehive/conf/application.conf /etc/thehive/application.conf
>sudo cp /opt/thehive/conf/logback.xml /etc/thehive/logback.xml
>sudo mkdir /etc/thehive
>(cat << _EOF_
>play.http.secret.key="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)"
>_EOF_
>) | sudo tee -a /etc/thehive/application.conf
>sudo groupadd thehive
>sudo useradd -g thehive --system thehive
>sudo mkdir -p /var/log/thehive/
>sudo touch /var/log/thehive/application.log
>sudo cp /opt/thehive/package/thehive.service /usr/lib/systemd/system
>sudo chown -R thehive:thehive /opt/thehive
>sudo chown -R thehive:thehive /var/log/thehive 
>sudo chown thehive:thehive /etc/thehive/application.conf
>sudo chmod 640 /etc/thehive/application.conf
>sudo systemctl enable thehive
>sudo service elasticsearch start
>sudo service thehive start
>sudo service elasticsearch status
>sudo service thehive status

### Complementary information
Content of /var/log/thehive/application.log 
>2018-05-17 10:09:56,393 [INFO] from org.reflections.Reflections in main - Reflections took 272 ms to scan 5 urls, producing 116 keys and 1170 values 
>2018-05-17 10:09:56,488 [INFO] from module in main - Loading model class models.UserModel
>2018-05-17 10:09:56,489 [INFO] from module in main - Loading model class models.AuditModel
>2018-05-17 10:09:56,489 [INFO] from module in main - Loading model class models.ArtifactModel
>2018-05-17 10:09:56,490 [INFO] from module in main - Loading model class connectors.cortex.models.JobModel
>2018-05-17 10:09:56,490 [INFO] from module in main - Loading model class org.elastic4play.services.AttachmentModel
>2018-05-17 10:09:56,490 [INFO] from module in main - Loading model class models.CaseTemplateModel
>2018-05-17 10:09:56,490 [INFO] from module in main - Loading model class models.TaskModel
>2018-05-17 10:09:56,490 [INFO] from module in main - Loading model class models.AlertModel
>2018-05-17 10:09:56,491 [INFO] from module in main - Loading model class models.LogModel
>2018-05-17 10:09:56,491 [INFO] from module in main - Loading model class connectors.cortex.models.ReportTemplateModel
>2018-05-17 10:09:56,491 [INFO] from module in main - Loading model class org.elastic4play.services.DBListModel
>2018-05-17 10:09:56,491 [INFO] from module in main - Loading model class models.CaseModel
>2018-05-17 10:09:56,491 [INFO] from module in main - Loading model class models.DashboardModel
>2018-05-17 10:09:59,133 [INFO] from akka.event.slf4j.Slf4jLogger in application-akka.actor.default-dispatcher-2 - Slf4jLogger started
>2018-05-17 10:10:00,750 [INFO] from org.elasticsearch.plugins.PluginsService in main - no modules loaded
>2018-05-17 10:10:00,752 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
>2018-05-17 10:10:00,752 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
>2018-05-17 10:10:00,752 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
>2018-05-17 10:10:00,752 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
>2018-05-17 10:10:00,752 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
>2018-05-17 10:10:00,752 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
>2018-05-17 10:10:02,287 [INFO] from io.netty.util.internal.PlatformDependent in main - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
>2018-05-17 10:10:02,939 [WARN] from application in main - /etc/thehive/application.conf: 31: auth.type is deprecated, use auth.provider instead
>2018-05-17 10:10:04,432 [INFO] from play.api.Play in main - Application started (Prod)
>2018-05-17 10:10:05,060 [INFO] from play.core.server.AkkaHttpServer in main - Listening for HTTP on /0.0.0.0:9000

It seems the server does not even get the GET / request.

**Comment by Xiobe** [comment]
Thank you for the feedback. Sorry that it took a couple of days to get back to you.

>node --version
>v6.14.0

>npm --version
>3.10.10

>bower --version
>1.8.4

>grunt --version
>grunt-cli v1.2.0

**Comment by To-om** [comment]
ok, seems good.
go into `ui` directory, try to build front-end and check output for errors.
```
cd ui
npm install 
bower install
grunt build
```

**Comment by Xiobe** [comment]
In the meanwhile the version of node has changed
>node --version
>v6.14.2

I am running into trouble with ``npm install`` I get a bunch of info on deprecated things
>npm install
>npm WARN deprecated grunt-filerev@2.3.1: Deprecated
>npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
>npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
>npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
>npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
>npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
>npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
>npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
>npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
>npm WARN deprecated bower@1.3.12: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
>npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
>npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
>npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
>npm WARN deprecated tough-cookie@0.12.1: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
>npm WARN deprecated npmconf@2.1.3: this package has been reintegrated into npm and is now out of date with respect to npm
>npm WARN prefer global jshint@2.8.0 should be installed with -g

and a bunch of missing dependencies
>npm WARN grunt-karma@2.0.0 requires a peer of karma@^0.13.0 || >= 0.14.0-rc.0 but none was installed.
>npm WARN karma-jasmine@1.1.2 requires a peer of jasmine-core@* but none was installed.
>npm WARN karma-jasmine@1.1.2 requires a peer of karma@* but none was installed.
>npm WARN karma-phantomjs-launcher@1.0.4 requires a peer of karma@>=0.9 but none was installed.

I tried installing karma with ``npm install -g karma`` but ran into missing dependencies, outdated and deprecated dependencies.

Can you advise me on how to handle this?

**Comment by nadouani** [comment]
Well we cannot yet get rid of bower because this requires revamping all the dependency management, and thus, might introduce an uncontrolled number of regression issues.

We have made this for Cortex that has been completely rewritten using just NPM and WebPack as build ad dependency management tools.

Doing the same to TheHive might take a lot of time, we currently don't have.

If you feel comfortable to do it, we would be happy to discuss and accept your PRs

**Comment by nadouani** [comment]
BTW, the bower warnings should not block you

**Comment by Eaglaxoon** [comment]
Hi Team,

I encounter the same problem: A client error occurred on GET /index.html : Resource not found by Assets controller

root@localhost thehive]# service thehive status
Redirecting to /bin/systemctl status thehive.service
● thehive.service - TheHive
   Loaded: loaded (/usr/lib/systemd/system/thehive.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2018-08-02 12:27:16 WEST; 2min 10s ago
     Docs: https://thehive-project.org
  Process: 20165 ExecStart=/opt/thehive/bin/thehive -Dconfig.file=/etc/thehive/application.conf -Dlogger.file=/etc/thehive/logback.xml -Dpidfile.path=/dev/null (code=exited, status=217/USER)
 Main PID: 20165 (code=exited, status=217/USER)

Aug 02 12:27:16 localhost.localdomain systemd[1]: Started TheHive.
Aug 02 12:27:16 localhost.localdomain systemd[1]: Starting TheHive...
Aug 02 12:27:16 localhost.localdomain systemd[1]: thehive.service: main process exited, code=exited, ...SER
Aug 02 12:27:16 localhost.localdomain systemd[1]: Unit thehive.service entered failed state.
Aug 02 12:27:16 localhost.localdomain systemd[1]: thehive.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

----
[root@localhost thehive]# bin/thehive -Dconfig.file=/etc/thehive/application.conf
[info] o.r.Reflections - Reflections took 1112 ms to scan 5 urls, producing 121 keys and 1285 values 
[info] module - Loading model class connectors.cortex.models.JobModel
[info] module - Loading model class models.LogModel
[info] module - Loading model class models.AlertModel
[info] module - Loading model class connectors.cortex.models.ActionModel
[info] module - Loading model class org.elastic4play.services.DBListModel
[info] module - Loading model class models.AuditModel
[info] module - Loading model class models.DashboardModel
[info] module - Loading model class connectors.cortex.models.ReportTemplateModel
[info] module - Loading model class models.UserModel
[info] module - Loading model class org.elastic4play.services.AttachmentModel
[info] module - Loading model class models.CaseModel
[info] module - Loading model class models.ArtifactModel
[info] module - Loading model class models.TaskModel
[info] module - Loading model class models.CaseTemplateModel
[info] a.e.s.Slf4jLogger - Slf4jLogger started
[info] a.r.Remoting - Starting remoting
[info] a.r.Remoting - Remoting started; listening on addresses :[akka.tcp://application@127.0.0.1:2552]
[info] a.r.Remoting - Remoting now listens on addresses: [akka.tcp://application@127.0.0.1:2552]
[info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@127.0.0.1:2552] - Starting up...
[info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@127.0.0.1:2552] - Registered cluster JMX MBean [akka:type=Cluster]
[info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@127.0.0.1:2552] - Started up successfully
[info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@127.0.0.1:2552] - No seed-nodes configured, manual cluster join required
[info] o.e.p.PluginsService - no modules loaded
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
[info] i.n.u.i.PlatformDependent - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
[info] play.api.Play - Application started (Prod)
[info] p.c.s.AkkaHttpServer - Enabling HTTP/2 on Akka HTTP server...
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
^C[info] p.c.s.AkkaHttpServer - Stopping server...
[info] a.r.RemoteActorRefProvider$RemotingTerminator - Shutting down remote daemon.
[info] a.r.RemoteActorRefProvider$RemotingTerminator - Remote daemon shut down; proceeding with flushing remote transports.
[info] a.r.Remoting - Remoting shut down
[info] a.r.RemoteActorRefProvider$RemotingTerminator - Remoting shut down.
[root@localhost thehive]# bin/thehive -Dconfig.file=/etc/thehive/application.conf
Oops, cannot start the server.
Configuration error: Configuration error[/etc/thehive/application.conf: 1: Expecting a value but got wrong token: 'newline' (JSON does not allow unescaped newline in quoted strings, use a backslash escape) (if you intended 'newline' (JSON does not allow unescaped newline in quoted strings, use a backslash escape) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)]
	at play.api.Configuration$.configError(Configuration.scala:156)
	at play.api.Configuration$.load(Configuration.scala:102)
	at play.core.server.ProdServerStart$.readServerConfigSettings(ProdServerStart.scala:86)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:40)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: com.typesafe.config.ConfigException$Parse: /etc/thehive/application.conf: 1: Expecting a value but got wrong token: 'newline' (JSON does not allow unescaped newline in quoted strings, use a backslash escape) (if you intended 'newline' (JSON does not allow unescaped newline in quoted strings, use a backslash escape) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:251)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:473)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:646)
	at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:152)
	at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:172)
	at com.typesafe.config.impl.ConfigImpl.parseFileAnySyntax(ConfigImpl.java:137)
	at com.typesafe.config.ConfigFactory.parseFileAnySyntax(ConfigFactory.java:741)
	at com.typesafe.config.ConfigFactory.parseFileAnySyntax(ConfigFactory.java:753)
	at play.api.Configuration$.$anonfun$load$4(Configuration.scala:69)
	at scala.Option.map(Option.scala:146)
	at play.api.Configuration$.$anonfun$load$3(Configuration.scala:69)
	at scala.Option.orElse(Option.scala:289)
	at play.api.Configuration$.load(Configuration.scala:69)
	... 4 more
[root@localhost thehive]# bin/thehive -Dconfig.file=/etc/thehive/application.conf
[info] o.r.Reflections - Reflections took 549 ms to scan 5 urls, producing 121 keys and 1285 values 
[info] module - Loading model class connectors.cortex.models.JobModel
[info] module - Loading model class models.LogModel
[info] module - Loading model class models.AlertModel
[info] module - Loading model class connectors.cortex.models.ActionModel
[info] module - Loading model class org.elastic4play.services.DBListModel
[info] module - Loading model class models.AuditModel
[info] module - Loading model class models.DashboardModel
[info] module - Loading model class connectors.cortex.models.ReportTemplateModel
[info] module - Loading model class models.UserModel
[info] module - Loading model class org.elastic4play.services.AttachmentModel
[info] module - Loading model class models.CaseModel
[info] module - Loading model class models.ArtifactModel
[info] module - Loading model class models.TaskModel
[info] module - Loading model class models.CaseTemplateModel
[info] a.e.s.Slf4jLogger - Slf4jLogger started
[info] a.r.Remoting - Starting remoting
[info] a.r.Remoting - Remoting started; listening on addresses :[akka.tcp://application@127.0.0.1:2552]
[info] a.r.Remoting - Remoting now listens on addresses: [akka.tcp://application@127.0.0.1:2552]
[info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@127.0.0.1:2552] - Starting up...
[info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@127.0.0.1:2552] - Registered cluster JMX MBean [akka:type=Cluster]
[info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@127.0.0.1:2552] - Started up successfully
[info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@127.0.0.1:2552] - No seed-nodes configured, manual cluster join required
[info] o.e.p.PluginsService - no modules loaded
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
[info] i.n.u.i.PlatformDependent - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
[info] play.api.Play - Application started (Prod)
[info] p.c.s.AkkaHttpServer - Enabling HTTP/2 on Akka HTTP server...
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

-------

can you advice me on how correct this ?

**Comment by 3c7** [comment]
Hey @Eaglaxoon,

these lines
```
Oops, cannot start the server.
Configuration error: Configuration error[/etc/thehive/application.conf: 1: Expecting a value but got wrong token: 'newline' (JSON does not allow unescaped newline in quoted strings, use a backslash escape) (if you intended 'newline' (JSON does not allow unescaped newline in quoted strings, use a backslash escape) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)]
```
indicate that your configuration file is somehow malformed. Have you checked it?

**Comment by crackytsi** [comment]
@Xiobe I'm quite sure you tried to build thehive as root which won't work without modifications as bower requires to be non-root.
I had the same issues when I tried to get into the build process

**Comment by crackytsi** [comment]
Same for @Eaglaxoon  ;)
