### ISSUE TITLE
TheHive - Cortex connection issue: Unknown server

### ISSUE THREAD

**Issue by norgalades** [TheHive-Project/TheHive#661]
### Request Type
Help needed

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | Windows 10
| TheHive version / git hash   | 3.0.9
| Cortex version / git hash   | 2.0.4
| Package Type              | Binary

### Problem Description
After having enabled cortex connection, TheHive is not recognizing the server. Standalone Cortex is working fine, but submitting the analyses from TheHive is not possibile due to Unknown version error. 
![image](https://user-images.githubusercontent.com/30833739/43513999-7f792cea-957f-11e8-8a70-2dc09c670d25.png)

![image](https://user-images.githubusercontent.com/30833739/43514055-9b453d7e-957f-11e8-8de2-e6fb7f3034a6.png)

### Complementary information
**Cortex logs:** 

2018-08-01 11:27:23,198 [INFO] from play.core.server.AkkaHttpServer in Thread-6 - Stopping server...
2018-08-01 11:27:29,243 [INFO] from org.reflections.Reflections in main - Reflections took 397 ms to scan 2 urls, producing 95 keys and 871 values
2018-08-01 11:27:29,346 [INFO] from module in main - Loading model class org.thp.cortex.models.ReportModel
2018-08-01 11:27:29,350 [INFO] from module in main - Loading model class org.thp.cortex.models.UserModel
2018-08-01 11:27:29,355 [INFO] from module in main - Loading model class org.elastic4play.services.DBListModel
2018-08-01 11:27:29,357 [INFO] from module in main - Loading model class org.thp.cortex.models.OrganizationModel
2018-08-01 11:27:29,359 [INFO] from module in main - Loading model class org.thp.cortex.models.AuditModel
2018-08-01 11:27:29,362 [INFO] from module in main - Loading model class org.thp.cortex.models.AnalyzerConfigModel
2018-08-01 11:27:29,363 [INFO] from module in main - Loading model class org.thp.cortex.models.ArtifactModel
2018-08-01 11:27:29,365 [INFO] from module in main - Loading model class org.elastic4play.services.AttachmentModel
2018-08-01 11:27:29,367 [INFO] from module in main - Loading model class org.thp.cortex.models.JobModel
2018-08-01 11:27:29,369 [INFO] from module in main - Loading model class org.thp.cortex.models.AnalyzerModel
2018-08-01 11:27:32,559 [INFO] from akka.event.slf4j.Slf4jLogger in application-akka.actor.default-dispatcher-4 - Slf4jLogger started
2018-08-01 11:27:41,573 [INFO] from org.thp.cortex.services.AnalyzerSrv in main - New analyzer list:
 
...

2018-08-01 11:27:44,013 [INFO] from play.api.Play in main - Application started (Prod)
2018-08-01 11:27:45,882 [INFO] from play.core.server.AkkaHttpServer in main - Listening for HTTP on /0.0.0.0:9001  

**TheHive logs:**

2018-08-01 11:27:42,204 [INFO] from akka.actor.CoordinatedShutdown in application-akka.actor.default-dispatcher-20 - Starting coordinated shutdown from JVM shutdown hook
2018-08-01 11:27:42,539 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-20 - GET /api/stream/4dvO7VMeiT returned 500
akka.pattern.AskTimeoutException: Ask timed out on [ActorSelection[Anchor(akka://application/), Path(/user/stream-4dvO7VMeiT)]] after [62000 ms]. Sender[null] sent message of type "services.StreamActor$GetOperations$".
        at akka.pattern.PromiseActorRef$.$anonfun$apply$1(AskSupport.scala:601)
        at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:140)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.run(LightArrayRevolverScheduler.scala:337)
        at akka.actor.LightArrayRevolverScheduler.$anonfun$close$1(LightArrayRevolverScheduler.scala:141)
        at akka.actor.LightArrayRevolverScheduler.$anonfun$close$1$adapted(LightArrayRevolverScheduler.scala:140)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at akka.actor.LightArrayRevolverScheduler.close(LightArrayRevolverScheduler.scala:140)
        at akka.actor.ActorSystemImpl.stopScheduler(ActorSystem.scala:855)
        at akka.actor.ActorSystemImpl.$anonfun$_start$1(ActorSystem.scala:794)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at akka.actor.ActorSystemImpl$$anon$3.run(ActorSystem.scala:810)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:987)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:987)
        at scala.concurrent.Future.$anonfun$andThen$1(Future.scala:533)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-08-01 11:27:48,931 [INFO] from org.reflections.Reflections in main - Reflections took 410 ms to scan 5 urls, producing 116 keys and 1170 values
2018-08-01 11:27:49,027 [INFO] from module in main - Loading model class connectors.cortex.models.JobModel
2018-08-01 11:27:49,030 [INFO] from module in main - Loading model class connectors.cortex.models.ReportTemplateModel
2018-08-01 11:27:49,032 [INFO] from module in main - Loading model class models.UserModel
2018-08-01 11:27:49,033 [INFO] from module in main - Loading model class org.elastic4play.services.AttachmentModel
2018-08-01 11:27:49,035 [INFO] from module in main - Loading model class org.elastic4play.services.DBListModel
2018-08-01 11:27:49,038 [INFO] from module in main - Loading model class models.CaseModel
2018-08-01 11:27:49,040 [INFO] from module in main - Loading model class models.LogModel
2018-08-01 11:27:49,041 [INFO] from module in main - Loading model class models.ArtifactModel
2018-08-01 11:27:49,043 [INFO] from module in main - Loading model class models.DashboardModel
2018-08-01 11:27:49,044 [INFO] from module in main - Loading model class models.AlertModel
2018-08-01 11:27:49,047 [INFO] from module in main - Loading model class models.AuditModel
2018-08-01 11:27:49,049 [INFO] from module in main - Loading model class models.TaskModel
2018-08-01 11:27:49,050 [INFO] from module in main - Loading model class models.CaseTemplateModel
2018-08-01 11:27:52,682 [INFO] from akka.event.slf4j.Slf4jLogger in application-akka.actor.default-dispatcher-4 - Slf4jLogger started
2018-08-01 11:27:53,747 [INFO] from org.elasticsearch.plugins.PluginsService in main - no modules loaded
2018-08-01 11:27:53,761 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
2018-08-01 11:27:53,762 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
2018-08-01 11:27:53,763 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
2018-08-01 11:27:53,765 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
2018-08-01 11:27:53,766 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
2018-08-01 11:27:53,767 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018-08-01 11:27:56,873 [INFO] from io.netty.util.internal.PlatformDependent in main - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
2018-08-01 11:28:02,281 [INFO] from connectors.cortex.services.CortexClient in main - new Cortex(CortexAgent, http://localhost:9001) authentication: connectors.cortex.services.CortexAuthentication$Key
2018-08-01 11:28:02,834 [INFO] from connectors.cortex.services.CortexSrv in main - Search for unfinished job ...
2018-08-01 11:28:03,163 [INFO] from connectors.cortex.services.CortexSrv in application-akka.actor.default-dispatcher-3 - 0 jobs found
2018-08-01 11:28:04,767 [INFO] from play.api.Play in main - Application started (Prod)
2018-08-01 11:28:06,493 [INFO] from play.core.server.AkkaHttpServer in main - Listening for HTTPS on /0.0.0.0:9443

**TheHive Conf:**

play.modules.enabled += connectors.cortex.CortexConnector

cortex {
  "CortexAgent" {
    # URL of the Cortex server.
    url = "http://localhost:9001"
    key = "****************************"
  }
}

**Comment by norgalades** [comment]
I managed to get a Cortex Server ok by changing localohost with the actual IP in thehive conf as follow:

cortex {
"CortexAgent" {
# URL of the Cortex server.
url = "http://IP_OF_SERVER:9001"
key = "****************************"
}
}

Now: 

![image](https://user-images.githubusercontent.com/30833739/43515333-8546ea92-9582-11e8-99d0-10a00963a383.png)

![image](https://user-images.githubusercontent.com/30833739/43515424-c3baecb0-9582-11e8-9757-8f0ed019cca1.png)

But still there is no analyzer available 

![image](https://user-images.githubusercontent.com/30833739/43515465-de067d82-9582-11e8-8dcd-f60d2f66acd6.png)

And it seems that the server is still not recognized

![image](https://user-images.githubusercontent.com/30833739/43515518-ff13f766-9582-11e8-9cda-c238f33327b4.png)

Any idea why this could happen? 

Thank you

**Comment by norgalades** [comment]
Problem found.

The observables I was trying to submit were all hashes (but I have custom fields to specify which kind of hash it is, md5, sha1, sha256) so TheHive doesn't know how to submit them :( 

Is there a way I can tell thehive that those are just hashes? Or the only way is to remove the hashes specification? 

Thanks for your time and help.

**Comment by To-om** [comment]
You can put the hash type in tag.

**Comment by niomictomi** [comment]
> I managed to get a Cortex Server ok by changing localohost with the actual IP in thehive conf as follow:
> 
> cortex {
> "CortexAgent" {
> url = "http://IP_OF_SERVER:9001"
> key = "****************************"
> }
> }
> 
> And renewing the API key for thehive user in Cortex.
> Now:
> 
> ![image](https://user-images.githubusercontent.com/30833739/43515333-8546ea92-9582-11e8-99d0-10a00963a383.png)
> 
> ![image](https://user-images.githubusercontent.com/30833739/43515424-c3baecb0-9582-11e8-9757-8f0ed019cca1.png)
> 
> But still there is no analyzer available
> 
> ![image](https://user-images.githubusercontent.com/30833739/43515465-de067d82-9582-11e8-8dcd-f60d2f66acd6.png)
> 
> And it seems that the server is still not recognized
> 
> ![image](https://user-images.githubusercontent.com/30833739/43515518-ff13f766-9582-11e8-9cda-c238f33327b4.png)
> 
> Any idea why this could happen?
> 
> Thank you

Any solutions ??

**Comment by svenseeberg** [comment]
> Any solutions ??

I'm having the same issues. Cortex is running, TheHive says that it is available (green icon in the lower right corner, and also OK in the "About" dialog).

Also, the API seems to be available:
```
curl http://localhost:9001/api/status

{"versions":{"Cortex":"3.1.1-1","Elastic4Play":"1.13.1","Play":"2.8.3","Elastic4s":"7.9.1","ElasticSearch client":"7.9.1"},"config":{"protectDownloadsWith":"malware","authType":["key","local"],"capabilities":["authByKey","changePassword","setPassword"],"ssoAutoLogin":false}}% 
```

But when trying to run analyzers for observables, I also have no Cortex server available - like in the screenshot in the previous post.

Used versions:
* Cortex 3.1.1-1
* TheHive 4.1.10-1

**Comment by To-om** [comment]
You need to check which analyzers are enabled on Cortex and on which data types they are applicable.

**Comment by svenseeberg** [comment]
> You need to check which analyzers are enabled on Cortex and on which data types they are applicable.

Good point. I have the default URLs (https://download.thehive-project.org/responders.json, https://download.thehive-project.org/analyzers.json) in the Cortex `application.conf`:

```
analyzer {
  urls = [
    "https://download.thehive-project.org/analyzers.json"
  ]
  fork-join-executor {
    parallelism-min = 2
    parallelism-factor = 2.0
    parallelism-max = 4
  }
}
```

I think I'm closer to the problem now:

```
curl -H 'Authorization: Bearer SECRET_TOKEN' 'http://127.0.0.1:9001/api/analyzer'
[]
```
The Cortex log file does not show any errors. Can anyone provide a hint where to look for the problem? Is there a Cortex debug log level available? I cannot find such a setting in the example config file.

**Comment by svenseeberg** [comment]
Okay, found the issue: create Cortex org admin user and enable analyzers. Sorry.
