### ISSUE TITLE
SSL with XPACK does not work

### ISSUE THREAD

**Issue by EricPE69** [TheHive-Project/TheHive#701]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | SLES 12
| OS version (client)       | Windows 7
| TheHive version / git hash   | 3.0.9
| Package Type              | Binary
| Browser type & version    | Chrome 68

### Problem Description
Hello,
I activate xpack for elastic and configure SSL for elastic transport.
When I try to connect to thehive I have the message "Elasticsearch unavailable" and in the log :+1: 
```
[info] o.e.ErrorHandler - GET /api/user/current returned 500
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{Ujp2a8HTSPCXc2D2AruT-A}{10.200.204.40}{10.200.204.40:9300}, {#transport#-2}{IboT4FvrSsyvBs87xz5tAQ}{10.200.204.41}{10.200.204.41:9300}, {#transport#-3}{ggxyEsAZQZSAe65YbPTdVw}{10.200.204.42}{10.200.204.42:9300}]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
        at com.sksamuel.elastic4s.search.SearchImplicits$SearchDefinitionExecutable$.$anonfun$apply$1(SearchImplicits.scala:27)
        at com.sksamuel.elastic4s.search.SearchImplicits$SearchDefinitionExecutable$.$anonfun$apply$1$adapted(SearchImplicits.scala:27)
        at com.sksamuel.elastic4s.Executable.injectFutureAndMap(Executable.scala:21)
        at com.sksamuel.elastic4s.Executable.injectFutureAndMap$(Executable.scala:19)
```

In the elastic log I have the following error:
```
_[2018-09-03T00:00:01,214][WARN ][o.e.x.s.t.n.SecurityNetty4Transport] [SOC-sl00z2] exception caught on transport layer [[id: 0x29494870, L:0.0.0.0/0.0.0.0:9300 ! R:/10.200.204.42:33652]], closing connection
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 45530000005800000000000fb07808004c4ba3010d417574686f72697a6174696f6e224261736963205a57786863335270597a706c6247467a64476c6a58314e50517a45340016696e7465726e616c3a7463702f68616e647368616b6500
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-codec-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.13.Final.jar:4.1.13.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 45530000005800000000000fb07808004c4ba3010d417574686f72697a6174696f6e224261736963205a57786863335270597a706c6247467a64476c6a58314e50517a45340016696e7465726e616c3a7463702f68616e647368616b6500
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1103) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[?:?]
        ... 15 more_
```

### Steps to Reproduce
Here is the hive configuration:
```
search {
  # Index name.
  index = thehive
  # ElasticSearch cluster name.
  cluster = SOC-IQR
  #cluster = SOC-TEST
  # ElasticSearch instance address.
  host = ["99.300.204.40:9300,99.300.204.41:9300,99.300.204.42:9300"]
  # Scroll keepalive.
  keepalive = 1m
  # Scroll page size.
  pagesize = 50
  username = elastic
  password = elastic_SOC18
  # Enable SSL to connect to ElasticSearch
  ssl.enabled = true
  # Path to certificate authority file
  ssl.ca = /applis/xagcla/pur/xagcla02/par/AC2016PoleEmploiQualificationApplications.crt
  # Path to certificate file
  #ssl.certificate = /applis/xagcla/pur/xagcla02/par/QVR-sl00z2.sii24.pole-emploi.intra.pem
  # Path to key file
  #ssl.key = /applis/xagcla/pur/xagcla02/par/QVR-sl00z2.sii24.pole-emploi.intra.key
}
```

### Complementary information
If I deactivate SSL for elasticsearch transport ( xpack.security.transport.ssl.enabled: false in elastic config) I have no more the problem.

Best Regards
Eric

**Comment by kara-1234** [comment]
+1

I believe I am having the same issue.

I'm on thehive-3.1.0-1.noarch on CentOS 7.latest and connecting to ElasticSearch 6.2 over xpack.

**Comment by lliknart** [comment]
Please, tell me this is a joke... (cf step to reproduce)

**Comment by 1earch** [comment]
@EricPE69 You have an error in your configuration of TheHive: the `search.host` field isn't in the wanted format. You should set it as following:
```
search {
  ...
  # ElasticSearch instance address.
  host = ["xx.xx.xx.xx:9300", "xx.xx.xx.xx:9300"]
  ...
}
```
where `xx.xx.xx.xx` are the IP addresses of your ElasticSearch nodes.

In addition, for security needs, I would recommend you to:
1. Edit your issue to hide sensitive informations (they won't be discarded as GitHub saves all comment versions, but it will be hidden in an history that near nobody will try to see).
2. Change at least your XPACK password and username

**Comment by BrijJhala** [comment]
Playframework did not support TLS 1.1 or 1.2 ??? I am getting below exception when I tried to connect from other microservice. Cortex playframework only support TLS 1.0 hence its an issue. That's what I am guessing.

Error: write EPROTO 140299170170752:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:ssl/statem/statem_lib.c:1919:\\n' +\n  '\\n'

**Comment by EricPE69** [comment]
Hello,

I do not use anymore The Hive.
