### ISSUE TITLE
Cortex Connector

### ISSUE THREAD

**Issue by XiQshoner** [TheHive-Project/TheHive#721]
Running Ubunutu 18.0.4
Cortex 2.0.4 and TheHive 3.0.10

I am having the exact same issue. For clarification sake, does it matter if I have the Cortex config in the /opt/thehive/conf/application.conf file? Does it have to be located in /etc/thehive/application.conf?
I have modified the config to use http://127.0.0.1:9001, http://localhost:9001, and my server IP.

I ran the API `curl -H 'Authorization: Bearer **API_KEY**' 'http://CORTEX_APP_URL:9001/api/analyzer'`
/w my API key and URL successfully 

My  /opt/thehive/conf/application.conf file looks like this for the Cortex portion:

`play.modules.enabled += connectors.cortex.CortexConnector

cortex {
  "1" {
     url = "http://localhost:9001"
     key= "qT3/9oLTylVq5AE9O38TG1KDi9MV5L76"
  }
}`

The output of my var/log/thehive/application.log is as follows for the relevant day:
2018-09-10 18:04:59,572 [WARN] from org.elastic4play.services.AuxSrv in application-akka.actor.default-dispatcher-40 - Entity case AWWv8vX2w3BspvBlqL_R not found
2018-09-10 18:04:59,591 [WARN] from org.elastic4play.services.AuxSrv in application-akka.actor.default-dispatcher-47 - Entity case AWWvosrSw3BspvBlqL_E not found
2018-09-10 18:05:42,949 [WARN] from org.elastic4play.services.AuxSrv in application-akka.actor.default-dispatcher-41 - Entity case AWWv8vX2w3BspvBlqL_R not found
2018-09-10 18:05:42,995 [WARN] from org.elastic4play.services.AuxSrv in application-akka.actor.default-dispatcher-46 - Entity case AWWvosrSw3BspvBlqL_E not found
2018-09-10 18:07:17,958 [INFO] from play.core.server.AkkaHttpServer in Thread-9 - Stopping server...
2018-09-10 18:07:17,961 [INFO] from akka.actor.CoordinatedShutdown in application-akka.actor.default-dispatcher-52 - Starting coordinated shutdown from JVM shutdown hook
2018-09-10 18:07:18,025 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-43 - GET /api/stream/l8iJJTflIo returned 500
akka.pattern.AskTimeoutException: Ask timed out on [ActorSelection[Anchor(akka://application/), Path(/user/stream-l8iJJTflIo)]] after [62000 ms]. Sender[null] sent message of type "services.StreamActor$GetOperations$".
        at akka.pattern.PromiseActorRef$.$anonfun$apply$1(AskSupport.scala:601)
        at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:140)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.run(LightArrayRevolverScheduler.scala:337)
        at akka.actor.LightArrayRevolverScheduler.$anonfun$close$1(LightArrayRevolverScheduler.scala:141)
        at akka.actor.LightArrayRevolverScheduler.$anonfun$close$1$adapted(LightArrayRevolverScheduler.scala:140)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at akka.actor.LightArrayRevolverScheduler.close(LightArrayRevolverScheduler.scala:140)
        at akka.actor.ActorSystemImpl.stopScheduler(ActorSystem.scala:855)
        at akka.actor.ActorSystemImpl.$anonfun$_start$1(ActorSystem.scala:794)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at akka.actor.ActorSystemImpl$$anon$3.run(ActorSystem.scala:810)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:987)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:987)
        at scala.concurrent.Future.$anonfun$andThen$1(Future.scala:533)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-09-10 18:07:23,995 [INFO] from org.reflections.Reflections in main - Reflections took 199 ms to scan 5 urls, producing 116 keys and 1174 values 
2018-09-10 18:07:24,030 [INFO] from module in main - Loading model class models.CaseModel
2018-09-10 18:07:24,033 [INFO] from module in main - Loading model class org.elastic4play.services.DBListModel
2018-09-10 18:07:24,033 [INFO] from module in main - Loading model class models.ArtifactModel
2018-09-10 18:07:24,033 [INFO] from module in main - Loading model class models.DashboardModel
2018-09-10 18:07:24,034 [INFO] from module in main - Loading model class models.AlertModel
2018-09-10 18:07:24,034 [INFO] from module in main - Loading model class connectors.cortex.models.JobModel
2018-09-10 18:07:24,034 [INFO] from module in main - Loading model class models.UserModel
2018-09-10 18:07:24,034 [INFO] from module in main - Loading model class org.elastic4play.services.AttachmentModel
2018-09-10 18:07:24,035 [INFO] from module in main - Loading model class models.AuditModel
2018-09-10 18:07:24,035 [INFO] from module in main - Loading model class models.TaskModel
2018-09-10 18:07:24,035 [INFO] from module in main - Loading model class connectors.cortex.models.ReportTemplateModel
2018-09-10 18:07:24,035 [INFO] from module in main - Loading model class models.LogModel
2018-09-10 18:07:24,036 [INFO] from module in main - Loading model class models.CaseTemplateModel
2018-09-10 18:07:25,558 [INFO] from akka.event.slf4j.Slf4jLogger in application-akka.actor.default-dispatcher-2 - Slf4jLogger started
2018-09-10 18:07:26,199 [INFO] from org.elasticsearch.plugins.PluginsService in main - no modules loaded
2018-09-10 18:07:26,203 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
2018-09-10 18:07:26,203 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
2018-09-10 18:07:26,203 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
2018-09-10 18:07:26,203 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
2018-09-10 18:07:26,203 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
2018-09-10 18:07:26,203 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018-09-10 18:07:27,464 [INFO] from io.netty.util.internal.PlatformDependent in main - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
2018-09-10 18:07:29,536 [INFO] from play.api.Play in main - Application started (Prod)
2018-09-10 18:07:30,003 [INFO] from play.core.server.AkkaHttpServer in main - Listening for HTTPS on /0:0:0:0:0:0:0:0:9443
2018-09-10 18:07:56,689 [WARN] from org.elastic4play.services.AuxSrv in application-akka.actor.default-dispatcher-27 - Entity case AWWv8vX2w3BspvBlqL_R not found
2018-09-10 18:07:56,721 [WARN] from org.elastic4play.services.AuxSrv in application-akka.actor.default-dispatcher-8 - Entity case AWWvosrSw3BspvBlqL_E not found
2018-09-10 18:17:15,149 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-51 - POST /api/login returned 401
org.elastic4play.AuthenticationError: Authentication failure
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$3.applyOrElse(MultiAuthSrv.scala:57)
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$3.applyOrElse(MultiAuthSrv.scala:57)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-09-10 18:18:18,251 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-51 - POST /api/login returned 401
org.elastic4play.AuthenticationError: Authentication failure
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$3.applyOrElse(MultiAuthSrv.scala:57)
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$3.applyOrElse(MultiAuthSrv.scala:57)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-09-10 18:18:21,855 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-58 - POST /api/login returned 401
org.elastic4play.AuthenticationError: Authentication failure
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$3.applyOrElse(MultiAuthSrv.scala:57)
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$3.applyOrElse(MultiAuthSrv.scala:57)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-09-10 18:21:13,417 [INFO] from play.core.server.AkkaHttpServer in Thread-9 - Stopping server...
2018-09-10 18:21:13,422 [INFO] from akka.actor.CoordinatedShutdown in application-akka.actor.default-dispatcher-45 - Starting coordinated shutdown from JVM shutdown hook
2018-09-10 18:21:13,504 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-66 - GET /api/stream/Y4842qjqBF returned 500
akka.pattern.AskTimeoutException: Ask timed out on [ActorSelection[Anchor(akka://application/), Path(/user/stream-Y4842qjqBF)]] after [62000 ms]. Sender[null] sent message of type "services.StreamActor$GetOperations$".
        at akka.pattern.PromiseActorRef$.$anonfun$apply$1(AskSupport.scala:601)
        at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:140)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.run(LightArrayRevolverScheduler.scala:337)
        at akka.actor.LightArrayRevolverScheduler.$anonfun$close$1(LightArrayRevolverScheduler.scala:141)
        at akka.actor.LightArrayRevolverScheduler.$anonfun$close$1$adapted(LightArrayRevolverScheduler.scala:140)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at akka.actor.LightArrayRevolverScheduler.close(LightArrayRevolverScheduler.scala:140)
        at akka.actor.ActorSystemImpl.stopScheduler(ActorSystem.scala:855)
        at akka.actor.ActorSystemImpl.$anonfun$_start$1(ActorSystem.scala:794)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at akka.actor.ActorSystemImpl$$anon$3.run(ActorSystem.scala:810)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:987)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:987)
        at scala.concurrent.Future.$anonfun$andThen$1(Future.scala:533)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-09-10 18:21:20,434 [INFO] from org.reflections.Reflections in main - Reflections took 183 ms to scan 5 urls, producing 116 keys and 1174 values 
2018-09-10 18:21:20,468 [INFO] from module in main - Loading model class models.CaseModel
2018-09-10 18:21:20,470 [INFO] from module in main - Loading model class org.elastic4play.services.DBListModel
2018-09-10 18:21:20,470 [INFO] from module in main - Loading model class models.ArtifactModel
2018-09-10 18:21:20,471 [INFO] from module in main - Loading model class models.DashboardModel
2018-09-10 18:21:20,471 [INFO] from module in main - Loading model class models.AlertModel
2018-09-10 18:21:20,471 [INFO] from module in main - Loading model class connectors.cortex.models.JobModel
2018-09-10 18:21:20,471 [INFO] from module in main - Loading model class models.UserModel
2018-09-10 18:21:20,472 [INFO] from module in main - Loading model class org.elastic4play.services.AttachmentModel
2018-09-10 18:21:20,472 [INFO] from module in main - Loading model class models.AuditModel
2018-09-10 18:21:20,472 [INFO] from module in main - Loading model class models.TaskModel
2018-09-10 18:21:20,472 [INFO] from module in main - Loading model class connectors.cortex.models.ReportTemplateModel
2018-09-10 18:21:20,473 [INFO] from module in main - Loading model class models.LogModel
2018-09-10 18:21:20,473 [INFO] from module in main - Loading model class models.CaseTemplateModel
2018-09-10 18:21:22,457 [INFO] from akka.event.slf4j.Slf4jLogger in application-akka.actor.default-dispatcher-3 - Slf4jLogger started
2018-09-10 18:21:23,074 [INFO] from org.elasticsearch.plugins.PluginsService in main - no modules loaded
2018-09-10 18:21:23,078 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
2018-09-10 18:21:23,079 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
2018-09-10 18:21:23,080 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
2018-09-10 18:21:23,080 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
2018-09-10 18:21:23,080 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
2018-09-10 18:21:23,080 [INFO] from org.elasticsearch.plugins.PluginsService in main - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018-09-10 18:21:24,281 [INFO] from io.netty.util.internal.PlatformDependent in main - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
2018-09-10 18:21:26,028 [INFO] from play.api.Play in main - Application started (Prod)
2018-09-10 18:21:26,490 [INFO] from play.core.server.AkkaHttpServer in main - Listening for HTTPS on /0:0:0:0:0:0:0:0:9443

Any help would be greatly appreciated.

**Comment by saadkadhi** [comment]
Discussion ongoing in #154
