### ISSUE TITLE
New elastic4play authentication error since updating Deb installation

### ISSUE THREAD

**Issue by smclinden** [TheHive-Project/TheHive#747]
2018-10-05 06:24:58,439 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispa
tcher-19 - Authentication failure:
        session: AuthenticationError User session has expired
        pki: AuthenticationError Certificate authentication is not configured
        key: AuthenticationError Authentication header not found
        basic: AuthenticationError Authentication header not found
        init: AuthenticationError Use of initial user is forbidden because users exist in database

**Comment by smclinden** [comment]
There was an earlier warning, but this has never been a problem:

 ws.ssl {
   trustManager = {
     stores = [
       { type = "PEM", path = "/path/to/cacert.crt" },
       { type = "JKS", path = "/path/to/truststore.jks" }
     ]
   }
 }
      
The action begins, here:

2018-10-05 06:16:36,366 [INFO] from connectors.misp.MispSynchro in application-akka.actor.default-dispatcher-3 - Misp synchronization completed
2018-10-05 06:16:36,685 [INFO] from play.core.server.AkkaHttpServer in main - Enabling HTTP/2 on Akka HTTP server...
2018-10-05 06:16:36,687 [INFO] from play.core.server.AkkaHttpServer in main - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
2018-10-05 06:24:58,439 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispatcher-19 - Authentication failure:
	session: AuthenticationError User session has expired
	pki: AuthenticationError Certificate authentication is not configured
	key: AuthenticationError Authentication header not found
	basic: AuthenticationError Authentication header not found
	init: AuthenticationError Use of initial user is forbidden because users exist in database
2018-10-05 06:24:58,439 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispatcher-18 - Authentication failure:
	session: AuthenticationError User session has expired
	pki: AuthenticationError Certificate authentication is not configured
	key: AuthenticationError Authentication header not found
	basic: AuthenticationError Authentication header not found
	init: AuthenticationError Use of initial user is forbidden because users exist in database
2018-10-05 06:24:58,441 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispatcher-2 - Authentication failure:
	session: AuthenticationError User session has expired
	pki: AuthenticationError Certificate authentication is not configured
	key: AuthenticationError Authentication header not found
	basic: AuthenticationError Authentication header not found
	init: AuthenticationError Use of initial user is forbidden because users exist in database
2018-10-05 06:24:58,451 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-2 - POST /api/alert/_stats returned 401
org.elastic4play.AuthenticationError: Authentication failure
	at org.elastic4play.controllers.Authenticated.$anonfun$getContext$4(Authenticated.scala:241)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-10-05 06:24:58,451 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-18 - POST /api/alert/_search?range=0-15&sort=-date returned 401
org.elastic4play.AuthenticationError: Authentication failure
	at org.elastic4play.controllers.Authenticated.$anonfun$getContext$4(Authenticated.scala:241)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-10-05 06:24:58,451 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispatcher-15 - Authentication failure:
	session: AuthenticationError User session has expired
	pki: AuthenticationError Certificate authentication is not configured
	key: AuthenticationError Authentication header not found
	basic: AuthenticationError Authentication header not found
	init: AuthenticationError Use of initial user is forbidden because users exist in database
2018-10-05 06:24:58,452 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-15 - POST /api/alert/_stats returned 401

**Comment by nadouani** [comment]
Are you able to login in and then you get these errors? Can you please describe what is not working exactly?

**Comment by smclinden** [comment]
The errors first occur before I login, but I am able to login without any issues. The purpose is ImportandExport so it may be that the issue is logging into MISP. Here are some of the errors that I get later on:


2018-10-07 01:16:36,775 [INFO] from connectors.misp.MispSynchro in application-akka.actor.default-dispatcher-4 - Misp synchronization completed
2018-10-07 01:40:27,019 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-3 - Illegal request, responding with status '400 Bad Request': Illegal HTTP message start
2018-10-07 01:41:04,068 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-19 - Illegal request, responding with status '400 Bad Request': Request is missing required `Host` header: Cannot establish effective URI of request to `/`, request has a relative URI and is missing a `Host` header; consider setting `akka.http.server.default-host-header`
2018-10-07 01:41:19,073 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-16 - Illegal request, responding with status '501 Not Implemented': Unsupported HTTP method:  ￳  ￯j
2018-10-07 01:41:23,948 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-4 - Illegal request, responding with status '400 Bad Request': Unsupported HTTP method: HTTP method too long (started with '0. publicﾡ!'). Increase `akka.http.server.parsing.max-method-length` to support HTTP methods with more characters.
2018-10-07 01:41:23,951 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-19 - Illegal request, responding with status '400 Bad Request': Unsupported HTTP method: HTTP method too long (started with ' ￳  ￯￾ﾇ~D'). Increase `akka.http.server.parsing.max-method-length` to support HTTP methods with more characters.
2018-10-07 01:41:39,536 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-16 - Illegal request, responding with status '501 Not Implemented': Unsupported HTTP method: t3
2018-10-07 01:41:44,566 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-17 - Illegal request, responding with status '400 Bad Request': Unsupported HTTP method: HTTP method too long (started with '  ￼￿P￾￞S'). Increase `akka.http.server.parsing.max-method-length` to support HTTP methods with more characters.
2018-10-07 01:41:55,213 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-15 - Illegal request, responding with status '501 Not Implemented': Unsupported HTTP method: Secure
2018-10-07 01:41:55,609 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-19 - Illegal request, responding with status '501 Not Implemented': Unsupported HTTP method: EQCPKJ
2018-10-07 01:42:09,431 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-3 - Illegal request, responding with status '400 Bad Request': Illegal request-target: Invalid input '<', expected segment, '/', '?' or 'EOI' (line 1, column 2): /<script>foo</script>
 ^
2018-10-07 01:42:10,186 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-19 - Illegal request, responding with status '501 Not Implemented': Unsupported HTTP method: NESSUS
2018-10-07 01:42:11,065 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-15 - Illegal request, responding with status '400 Bad Request': Request is missing required `Host` header: Cannot establish effective URI of request to `/spipe?Source=nessus`, request has a relative URI and is missing a `Host` header; consider setting `akka.http.server.default-host-header`
2018-10-07 01:42:13,439 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-4 - Illegal request, responding with status '400 Bad Request': Request is missing required `Host` header: Cannot establish effective URI of request to `/logout`, request has a relative URI and is missing a `Host` header; consider setting `akka.http.server.default-host-header`
2018-10-07 01:42:15,004 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-17 - Illegal request, responding with status '400 Bad Request': Illegal HTTP message start
2018-10-07 01:42:15,459 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-13259 - Illegal request, responding with status '400 Bad Request': Unsupported HTTP method: HTTP method too long (started with 'CONNECT
OPTIONS'). Increase `akka.http.server.parsing.max-method-length` to support HTTP methods with more characters.
2018-10-07 01:42:19,023 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-4 - Illegal header: Illegal 'content-type' header: Invalid input '{', expected tchar, OWS or '/' (line 1, column 2): %{#context['com.opensymphony.xwork2.dispatcher.HttpServletResponse'].addHeader('X-Tenable','heMsbm3v')}.multipart/form-data
 ^
2018-10-07 01:42:19,031 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-4 - Illegal header: Illegal 'content-type' header: Invalid input '{', expected tchar, OWS or '/' (line 1, column 2): %{(#_='multipart/form-data').(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','/c','ipconfig','/all'}:{'bash','-c','id'})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(#ros=(@org.apache.struts2.ServletActionContext@getResponse().getOutputStream())).(@org.apache.commons.io.IOUtils@copy(#process.getInputStream(),#ros)).(#ros.flush())}
 ^
2018-10-07 01:42:50,071 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-19 - Illegal request, responding with status '400 Bad Request': Request is missing required `Host` header
2018-10-07 01:42:55,059 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-19 - Illegal request, responding with status '400 Bad Request': Illegal HTTP message start
2018-10-07 02:16:36,729 [INFO] from connectors.misp.MispSynchro in application-akka.actor.default-dispatcher-16 - Update of MISP events is starting ...

**Comment by smclinden** [comment]
MISP is set up for HTTPS/HTTP2.

**Comment by smclinden** [comment]
I guess that I can close this. Apparently security was running Nessus scans against servers and we weren't alerted.

**Comment by asgharali1** [comment]
@nadouani I am trying to create an admin user. However, I was unable to create a user. I am seeing the following exception below. Please advice 

```
cortex_6/_update/admin?_source=true&refresh=wait_for&routing=admin&retry_on_conflict=5
StringEntity({"script":{"source":"ctx._source[\"password\"]=params.param0;ctx._source[\"updatedBy\"]=params.param1;ctx._source[\"updatedAt\"]=params.param2","params":{"param0":"냠頤垅┑蛟뜙䧙甶࿨䡃,d1020d264a4c9b602bf895a52711df4ae569c978ae5af2c47bde9754d375e3c3","param1":"init","param2":1643826406831}}},Some(application/json))
 => ElasticError(illegal_argument_exception,request [/cortex_6/_update/admin] contains unrecognized parameters: [_source], [retry_on_conflict],None,None,None,List(ElasticError(illegal_argument_exception,request [/cortex_6/_update/admin] contains unrecognized parameters: [_source], [retry_on_conflict],None,None,None,null,None,None,None,List())),None,None,None,List())
2022-02-02 18:26:46,837 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-54 - POST /api/user returned 500
org.elastic4play.InternalError: Unknown error: ElasticError(illegal_argument_exception,request [/cortex_6/_update/admin] contains unrecognized parameters: [_source], [retry_on_conflict],None,None,None,List(ElasticError(illegal_argument_exception,request [/cortex_6/_update/admin] contains unrecognized parameters: [_source], [retry_on_conflict],None,None,None,null,None,None,None,List())),None,None,None,List())
	at org.elastic4play.database.DBConfiguration.$anonfun$execute$2(DBConfiguration.scala:158)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2022-02-02 18:26:47,469 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-54 - GET /api/stream/cCfmAyjxv3 returned 401
org.elastic4play.AuthenticationError: Authentication header not found
	at org.elastic4play.controllers.Authenticated.$anonfun$getFromApiKey$1(Authenticated.scala:143)
	at scala.Option.fold(Option.scala:251)
	at org.elastic4play.controllers.Authenticated.getFromApiKey(Authenticated.scala:143)
	at org.thp.cortex.controllers.StreamCtrl$$anonfun$1.applyOrElse(StreamCtrl.scala:101)
	at org.thp.cortex.controllers.StreamCtrl$$anonfun$1.applyOrElse(StreamCtrl.scala:101)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2022-02-02 18:26:48,726 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispatcher-54 - Authentication failure:
	session: AuthenticationError User session not found
	pki: AuthenticationError Certificate authentication is not configured
	key: AuthenticationError Authentication header not found
	init: AuthenticationError Use of initial user is forbidden because users exist in database
2022-02-02 18:26:48,726 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-54 - POST /api/user returned 401
org.elastic4play.AuthenticationError: Authentication failure
	at org.elastic4play.controllers.Authenticated.$anonfun$getContext$4(Authenticated.scala:272)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
