### ISSUE TITLE
TheHive version 3.1.2-2 is crashing with "GC overhead limit exceeded" error.

### ISSUE THREAD

**Issue by R00ST3RDUDE** [TheHive-Project/TheHive#812]
TheHive version 3.1.2-2 is crashing with "GC overhead limit exceeded" error.

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RHEL 7.5 

| TheHive version / git hash   | 3.1.2-2
| Package Type              | RPM

### Problem Description
Describe the problem/bug as clearly as possible.

Randomly TheHive is crashing with the following errors being piped to the console:

[root@hive-pthlaj rrohlf]# Uncaught error from thread [application-akka.actor.default-dispatcher-17]: GC overhead limit exceeded, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.StringBuffer.toString(StringBuffer.java:669)
        at play.api.libs.json.jackson.JacksonJson$.$anonfun$generateFromJsValue$1(JacksonJson.scala:264)
        at play.api.libs.json.jackson.JacksonJson$$$Lambda$2360/1635978877.apply(Unknown Source)
        at play.api.libs.json.jackson.JacksonJson$.withStringWriter(JacksonJson.scala:244)
        at play.api.libs.json.jackson.JacksonJson$.generateFromJsValue(JacksonJson.scala:255)
        at play.api.libs.json.StaticBinding$.generateFromJsValue(StaticBinding.scala:23)
        at play.api.libs.json.Json$.stringify(Json.scala:178)
        at play.api.libs.json.JsValue.toString(JsValue.scala:22)
        at play.api.libs.json.JsValue.toString$(JsValue.scala:22)
        at play.api.libs.json.JsObject.toString(JsValue.scala:124)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at scala.StringContext.standardInterpolator(StringContext.scala:129)
        at scala.StringContext.s(StringContext.scala:97)
        at play.api.libs.json.JsLookup$.$anonfun$$bslash$extension1$2(JsLookup.scala:99)
        at play.api.libs.json.JsLookup$$$Lambda$2359/542457125.apply(Unknown Source)
        at play.api.libs.json.JsUndefined.error(JsLookup.scala:182)
        at play.api.libs.json.JsUndefined.validationError(JsLookup.scala:183)
        at play.api.libs.json.JsLookupResult.validate(JsLookup.scala:155)
        at play.api.libs.json.JsLookupResult.validate$(JsLookup.scala:153)
        at play.api.libs.json.JsUndefined.validate(JsLookup.scala:181)
        at play.api.libs.json.JsReadable.asOpt(JsReadable.scala:18)
        at play.api.libs.json.JsReadable.asOpt$(JsReadable.scala:18)
        at play.api.libs.json.JsUndefined.asOpt(JsLookup.scala:181)
        at org.elastic4play.services.CreateSrv.$anonfun$checkAttributes$1(CreateSrv.scala:37)
        at org.elastic4play.services.CreateSrv$$Lambda$2435/1574470268.apply(Unknown Source)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$Lambda$95/613784740.apply(Unknown Source)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error] a.a.ActorSystemImpl - Uncaught error from thread [application-akka.actor.default-dispatcher-17]: GC overhead limit exceeded, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.StringBuffer.toString(StringBuffer.java:669)
        at play.api.libs.json.jackson.JacksonJson$.$anonfun$generateFromJsValue$1(JacksonJson.scala:264)
        at play.api.libs.json.jackson.JacksonJson$$$Lambda$2360/1635978877.apply(Unknown Source)
        at play.api.libs.json.jackson.JacksonJson$.withStringWriter(JacksonJson.scala:244)
        at play.api.libs.json.jackson.JacksonJson$.generateFromJsValue(JacksonJson.scala:255)
        at play.api.libs.json.StaticBinding$.generateFromJsValue(StaticBinding.scala:23)
        at play.api.libs.json.Json$.stringify(Json.scala:178)
        at play.api.libs.json.JsValue.toString(JsValue.scala:22)
        at play.api.libs.json.JsValue.toString$(JsValue.scala:22)
[ERROR] [12/03/2018 12:23:31.152] [application-akka.actor.default-dispatcher-5] [akka.actor.ActorSystemImpl(application)] Internal server error, sending 500 response (akka.stream.AbruptTerminationException: Processor actor [Actor[akka://application/system/StreamSupervisor-0/flow-268382-1-One2OneBidi#-1393722269]] terminated abruptly)
[ERROR] [12/03/2018 12:23:31.152] [application-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(application)] Internal server error, sending 500 response (akka.stream.AbruptTerminationException: Processor actor [Actor[akka://application/system/StreamSupervisor-0/flow-268385-1-One2OneBidi#690972239]] terminated abruptly)

I noticed the application log stopped logging for some reason about 4 months ago, so unfortunately I do no have that to add to this report.

**Comment by To-om** [comment]
What did TheHive do when the error occurs ? Did you try to create a huge alert ?

**Comment by To-om** [comment]
Have you configured SSL on TheHive ? Out-of-memory error occurs when SSL is managed by java. If so, add a reverse proxy (nginx for example) in front of TheHive (see https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#101-https-using-a-reverse-proxy)

**Comment by R00ST3RDUDE** [comment]
We have implemented the nginx reverse proxy and will continue to monitor. I'll update this and let you know if that was the cause of the problem. Thanks for your timely responses, it is appreciated.

**Comment by To-om** [comment]
I close this issue. Feel free to reopen it if needed.
