### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Idriel** [TheHive-Project/TheHive#813]
Every few days Hive is down and I have following error. java.lang.OutOfMemoryError: Java heap space
```
Uncaught error from thread [application-scheduler-1]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
	at akka.dispatch.AbstractNodeQueue.<init>(AbstractNodeQueue.java:32)
	at akka.actor.LightArrayRevolverScheduler$TaskQueue.<init>(LightArrayRevolverScheduler.scala:304)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:269)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:235)
	at java.base/java.lang.Thread.run(Thread.java:844)
Uncaught error from thread [application-akka.actor.default-dispatcher-25869]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
Uncaught error from thread [application-akka.actor.default-dispatcher-18]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
	at java.base/sun.security.provider.DigestBase.engineDigest(DigestBase.java:185)
	at java.base/java.security.MessageDigest$Delegate.engineDigest(MessageDigest.java:629)
	at java.base/java.security.MessageDigest.digest(MessageDigest.java:385)
	at java.base/java.security.MessageDigest.digest(MessageDigest.java:431)
	at java.base/com.sun.crypto.provider.PKCS12PBECipherCore.derive(PKCS12PBECipherCore.java:118)
	at java.base/com.sun.crypto.provider.PKCS12PBECipherCore.derive(PKCS12PBECipherCore.java:69)
	at java.base/com.sun.crypto.provider.PKCS12PBECipherCore.implInit(PKCS12PBECipherCore.java:346)
	at java.base/com.sun.crypto.provider.PKCS12PBECipherCore.implInit(PKCS12PBECipherCore.java:373)
	at java.base/com.sun.crypto.provider.PKCS12PBECipherCore.implInit(PKCS12PBECipherCore.java:358)
	at java.base/com.sun.crypto.provider.PKCS12PBECipherCore$PBEWithSHA1AndDESede.engineInit(PKCS12PBECipherCore.java:467)
	at java.base/javax.crypto.Cipher.implInit(Cipher.java:836)
	at java.base/javax.crypto.Cipher.chooseProvider(Cipher.java:890)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1565)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1496)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:380)
	at java.base/sun.security.util.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:90)
	at java.base/java.security.KeyStore.getKey(KeyStore.java:1057)
	at java.base/sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:133)
	at java.base/sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70)
	at java.base/javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:271)
	at org.elastic4play.ClientAuthSSLEngineProvider.readKeyManagers(ClientAuthSSLEngineProvider.scala:27)
	at org.elastic4play.ClientAuthSSLEngineProvider.createSSLContext(ClientAuthSSLEngineProvider.scala:56)
	at org.elastic4play.ClientAuthSSLEngineProvider.createSSLEngine(ClientAuthSSLEngineProvider.scala:66)
	at play.core.server.AkkaHttpServer$$anon$5$$anon$6.engineCreateSSLEngine(AkkaHttpServer.scala:445)
	at java.base/javax.net.ssl.SSLContext.createSSLEngine(SSLContext.java:348)
	at akka.http.scaladsl.Http2Ext.createEngine$1(Http2.scala:71)
	at akka.http.scaladsl.Http2Ext.$anonfun$bindAndHandleAsync$3(Http2.scala:76)
	at akka.http.scaladsl.Http2Ext$$Lambda$2282/182000079.apply(Unknown Source)
	at akka.stream.scaladsl.TLS$.$anonfun$apply$5(TLS.scala:176)
	at akka.stream.scaladsl.TLS$$$Lambda$2284/562594408.apply(Unknown Source)
	at akka.stream.impl.io.TLSActor.liftedTree1$1(TLSActor.scala:157)
	at akka.stream.impl.io.TLSActor.<init>(TLSActor.scala:157)
[error] a.a.ActorSystemImpl - exception on LARS’ timer thread
java.lang.OutOfMemoryError: Java heap space
	at akka.dispatch.AbstractNodeQueue.<init>(AbstractNodeQueue.java:32)
	at akka.actor.LightArrayRevolverScheduler$TaskQueue.<init>(LightArrayRevolverScheduler.scala:304)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:269)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:235)
	at java.base/java.lang.Thread.run(Thread.java:844)
[info] a.a.ActorSystemImpl - starting new LARS thread
[error] a.a.ActorSystemImpl - Uncaught error from thread [application-scheduler-1]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
	at akka.dispatch.AbstractNodeQueue.<init>(AbstractNodeQueue.java:32)
	at akka.actor.LightArrayRevolverScheduler$TaskQueue.<init>(LightArrayRevolverScheduler.scala:304)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:269)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:235)
	at java.base/java.lang.Thread.run(Thread.java:844)
[error] a.a.ActorSystemImpl - Uncaught error from thread [application-akka.actor.default-dispatcher-25869]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
[error] a.a.ActorSystemImpl - Uncaught error from thread [application-akka.actor.default-dispatcher-18]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
	at java.base/sun.security.provider.DigestBase.engineDigest(DigestBase.java:185)
	at java.base/java.security.MessageDigest$Delegate.engineDigest(MessageDigest.java:629)
	at java.base/java.security.MessageDigest.digest(MessageDigest.java:385)
	at java.base/java.security.MessageDigest.digest(MessageDigest.java:431)
	at java.base/com.sun.crypto.provider.PKCS12PBECipherCore.derive(PKCS12PBECipherCore.java:118)
	at java.base/com.sun.crypto.provider.PKCS12PBECipherCore.derive(PKCS12PBECipherCore.java:69)
	at java.base/com.sun.crypto.provider.PKCS12PBECipherCore.implInit(PKCS12PBECipherCore.java:346)
	at java.base/com.sun.crypto.provider.PKCS12PBECipherCore.implInit(PKCS12PBECipherCore.java:373)
	at java.base/com.sun.crypto.provider.PKCS12PBECipherCore.implInit(PKCS12PBECipherCore.java:358)
	at java.base/com.sun.crypto.provider.PKCS12PBECipherCore$PBEWithSHA1AndDESede.engineInit(PKCS12PBECipherCore.java:467)
[info] p.c.s.AkkaHttpServer - Stopping server...
[error] a.a.OneForOneStrategy - head of empty list
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:428)
	at scala.collection.immutable.Nil$.head(List.scala:425)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AsyncAppender-Worker-ASYNCSTDOUT"
Uncaught error from thread [application-akka.actor.default-dispatcher-2]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AsyncAppender-Worker-ASYNCFILE"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-3-thread-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-2-thread-1"
Uncaught error from thread [Uncaught error from thread [Uncaught error from thread [application-scheduler-25911]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
Exception in thread "AsyncHttpClient-5-4" java.lang.OutOfMemoryError: Java heap space
Uncaught error from thread [application-akka.actor.default-dispatcher-24925]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
Uncaught error from thread [application-akka.actor.default-dispatcher-24974]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
Exception in thread "elasticsearch[_client_][generic][T#2]" java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
Exception in thread "elasticsearch[_client_][scheduler][T#1]" java.lang.OutOfMemoryError: Java heap space
Uncaught error from thread [application-akka.io.pinned-dispatcher-19]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
Uncaught error from thread [application-akka.actor.default-dispatcher-25863]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
```

**Comment by To-om** [comment]
There are known problem (OOM in particular) when SSL is configured directly on TheHive. It is recommended to  configure SSL on a reverse proxy in front of the service (see https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#101-https-using-a-reverse-proxy).

**Comment by Idriel** [comment]
Thank you. will do that.
