### ISSUE TITLE
Running multiple TheHive instances with one Elasticsearch

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#833]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven
| TheHive version / git hash   | 3.2
| Package Type              | DEB

### Problem Description
I want to run multiple TheHive instances on one host using only one Elastic-search database instance with different indexes.
But I wonder how to set the index prefix (e.g. thehive for index thehive_14).

### Possible Solutions
Thats the question ;)

**Comment by nadouani** [comment]
Each TheHive instance can define its own `search.index` configuration in `application.conf` which will be users to generate the index name `<search.index>_version`.

Is this what you are asking for, or I'm missing something?

**Comment by crackytsi** [comment]
Exactly thats it. No clue why I havent seen it before.
Thank you :-)

**Comment by crackytsi** [comment]
Hi @nadouani 

Running 2 instances of TheHive seems to fail, because Netty binds to a port 2552.
No clue why this port-bind even happens...

regards
Christopher

```
2019-01-08 11:34:50,730 [ERROR] from akka.remote.transport.netty.NettyTransport in application-akka.actor.default-dispatcher-5 - failed to bind to /192.168.200.3:2552, shutting down Netty transport
2019-01-08 11:34:50,746 [ERROR] from akka.remote.Remoting in application-akka.actor.default-dispatcher-5 - Remoting error: [Startup failed] [
akka.remote.RemoteTransportException: Startup failed
        at akka.remote.Remoting.akka$remote$Remoting$$notifyError(Remoting.scala:147)
        at akka.remote.Remoting.start(Remoting.scala:213)
        at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:225)
        at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:31)
        at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:868)
        at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:864)
        at akka.actor.ActorSystemImpl._start(ActorSystem.scala:864)
        at akka.actor.ActorSystemImpl.start(ActorSystem.scala:885)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
        at play.api.libs.concurrent.ActorSystemProvider$.start(Akka.scala:187)
        at play.api.libs.concurrent.ActorSystemProvider$.start(Akka.scala:140)
        at play.api.libs.concurrent.ActorSystemProvider.get$lzycompute(Akka.scala:103)
        at play.api.libs.concurrent.ActorSystemProvider.get(Akka.scala:102)
        at play.api.libs.concurrent.ActorSystemProvider.get(Akka.scala:98)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
        at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:52)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:147)
        at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:71)
        at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:1014)
        at com.google.inject.util.Providers$GuicifiedProviderWithDependencies.initialize(Providers.java:154)
        at com.google.inject.util.Providers$GuicifiedProviderWithDependencies$$FastClassByGuice$$2a7177aa.invoke(<generated>)
        at com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:51)
        at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:85)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:147)
        at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101)
        at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:245)
        at com.google.inject.internal.Initializer.injectAll(Initializer.java:140)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:176)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:78)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: /192.168.200.3:2552
        at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
        at akka.remote.transport.netty.NettyTransport.$anonfun$listen$1(NettyTransport.scala:417)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)

```

**Comment by nadouani** [comment]
2 instances in the same server?

**Comment by crackytsi** [comment]
yes.

**Comment by nadouani** [comment]
Try to customize the `akka.remote.netty.tcp.port` or set it to `0` to make Netty choose a port.

Reference: https://doc.akka.io/docs/akka/2.0.2/java/remoting.html

**Comment by crackytsi** [comment]
WoW, thats it! Thank you :)
