### ISSUE TITLE
Delete user from Thehive:   DELETE /api/user/user1 returned 500 org.elastic4play.InternalError: user can't be removed

### ISSUE THREAD

**Issue by Radi0now** [TheHive-Project/TheHive#844]
Help me please! I'm new to Ubuntu.

Ubuntu 18.04
thehive-3.2.1-1

Cannot delete user by command
root@thehive:# curl -XDELETE -H 'Authorization: Bearer pujTApbw+Ew2EcfyspYdmbwHo9Neakkh'  http://127.0.0.1:9000/api/user/user1
{"type":"InternalError","message":"user can't be removed"}root@thehive:/opt#

application.log

```
2019-01-04 11:09:28,445 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-19 - DELETE /api/user/user1 returned 500
org.elastic4play.InternalError: user can't be removed
        at org.elastic4play.models.BaseModelDef.removeAttribute(ModelDef.scala:62)
        at org.elastic4play.services.DeleteSrv.apply(DeleteSrv.scala:26)
        at org.elastic4play.services.DeleteSrv.$anonfun$apply$1(DeleteSrv.scala:22)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by ErnHem** [comment]
Hello Team,

The same issue

**Comment by nadouani** [comment]
Hello all,

well deleting users from TheHive means, marking them as `Locked`. We don't physically delete the data. As a workaround, you can PATCH the user and setting `{"status": "Locked"}`.

If you feel confident in deleting them from the DB, you can do it from ES directly.

```
curl -XDELETE http://ES_SERVER:ES_PORT/THEHIVE_INDEX/user/USER_LOGIN
```

Thanks

**Comment by Radi0now** [comment]
Hello all,

Thank! You helped me a lot.
How to delete a user in UTF-8 encoding? (Russian coding) 
user: пользователь

$ curl -XDELETE http://localhost:9200/the_hive_14/user/пользователь
{"found":false,"_index":"the_hive_14","_type":"user","_id":"Ð¿Ð¾Ð»Ñ�Ð·Ð¾Ð²Ð°Ñ�ÐµÐ»Ñ�","_version":1,"result":"not_found","_shards":{"total":2,"successful":1,"failed":0}}

application.log
2019-02-14 13:00:52,903 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-6 - Illegal request, responding with status '400 Bad Request': Illegal request-target: Invalid input '\', expected pchar, '/', '?' or 'EOI' (line 1, column 27): /the_hive_14/user/security\Ã^q^bÃ^pÂµÃ^q^aÃ^pÂ¾Ã^pÂ²Ã^pÂµÃ^q^f

**Comment by Radi0now** [comment]
> Hello all,
> 
> well deleting users from TheHive means, marking them as `Locked`. We don't physically delete the data. As a workaround, you can PATCH the user and setting `{"status": "Locked"}`.
> 
> If you feel confident in deleting them from the DB, you can do it from ES directly.
> 
> ```
> curl -XDELETE http://ES_SERVER:ES_PORT/THEHIVE_INDEX/user/USER_LOGIN
> ```
> Thanks

Hello all,

Thank! You helped me a lot.
How to delete a user in UTF-8 encoding? (Russian coding)
user: пользователь

$ curl -XDELETE [http://localhost:9200/the_hive_14/user/пользователь](http://localhost:9200/the_hive_14/user/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C)
{"found":false,"_index":"the_hive_14","_type":"user","_id":"Ð¿Ð¾Ð»Ñ�Ð·Ð¾Ð²Ð°Ñ�ÐµÐ»Ñ�","_version":1,"result":"not_found","_shards":{"total":2,"successful":1,"failed":0}}

application.log
2019-02-14 13:00:52,903 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-6 - Illegal request, responding with status '400 Bad Request': Illegal request-target: Invalid input '', expected pchar, '/', '?' or 'EOI' (line 1, column 27): /the_hive_14/user/security\Ã^q^bÃ^pÂµÃ^q^aÃ^pÂ¾Ã^pÂ²Ã^pÂµÃ^q^f
