### ISSUE TITLE
Java heap space - akka.jvm-exit-on-fatal-error

### ISSUE THREAD

**Issue by joseluratm** [TheHive-Project/TheHive#918]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| TheHive version / git hash   | 3.3.0-rc5
| Package Type              |  Docker

### Problem Description
This morning I realized that my TheHive container was down. When I went to see the log, I saw the following error:
```
Uncaught error from thread [Uncaught error from thread [application-akka.remote.default-remote-dispatcher-5831Uncaught error from thread [application-akka.remote.default-remote-dispatcher-5832]: Uncaught error from thread [application-akka.remote.default-remote-dispatcher-5829]: Java heap spaceUncaught error from thread [application-akka.remote.default-remote-dispatcher-5828]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[Java heap space]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[applicationapplication-akka.remote.default-remote-dispatcher-5830]
, Uncaught error from thread [application-akka.actor.default-dispatcher-25]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
application ActorSystem[application]
]
shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.growArray(ForkJoinPool.java:1090)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1978)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.growArray(ForkJoinPool.java:1090)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1978)

                               
[error] a.a.ActorSystemImpl - Uncaught error from thread [application-akka.remote.default-remote-dispatcher-5830]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.growArray(ForkJoinPool.java:1090)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1978)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] a.a.ActorSystemImpl - Uncaught error from thread [application-akka.remote.default-remote-dispatcher-5831]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
[error] a.a.ActorSystemImpl - Uncaught error from thread [application-akka.remote.default-remote-dispatcher-5828]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.growArray(ForkJoinPool.java:1090)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1978)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] a.a.ActorSystemImpl - Uncaught error from thread [application-akka.remote.default-remote-dispatcher-5832]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
[error] a.a.ActorSystemImpl - Uncaught error from thread [application-akka.actor.default-dispatcher-25]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
                
[error] a.a.ActorSystemImpl - Uncaught error from thread [application-akka.remote.default-remote-dispatcher-5829]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.growArray(ForkJoinPool.java:1090)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1978)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] a.a.OneForOneStrategy - head of empty list
java.util.NoSuchElementException: head of empty list
        at scala.collection.immutable.Nil$.head(List.scala:428)
        at scala.collection.immutable.Nil$.head(List.scala:425)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)

                               [error] o.e.s.a.MultiAuthSrv - Authentication failure
org.elastic4play.AuthenticationError: Authentication using API key is not supported
        at org.elastic4play.services.AuthSrv.authenticate(UserSrv.scala:47)
        at org.elastic4play.services.AuthSrv.authenticate$(UserSrv.scala:47)
        at services.LocalAuthSrv.authenticate(LocalAuthSrv.scala:19)
        at org.elastic4play.services.auth.MultiAuthSrv.$anonfun$authenticate$2(MultiAuthSrv.scala:62)
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$$nestedInanonfun$forAllAuthProvider$1$1.applyOrElse(MultiAuthSrv.scala:46)
        at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$$nestedInanonfun$forAllAuthProvider$1$1.applyOrElse(MultiAuthSrv.scala:44)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:413)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)

```
The machine on which the container is running has 64gb. I don't know if it has been a load problem, or if it is due to a bad configuration on my part.

Has anyone made the same mistake? Possible solutions so that it doesn't happen again?

**Comment by nadouani** [comment]
Hello, do you serve Thehive over https, configured in Thehive config file?

**Comment by joseluratm** [comment]
Hello!!
Yes, we are using https, but from what I have seen in the rest of related issues, the trace of the error is completely different, since in my log is not referred at any time to SSL

**Comment by nadouani** [comment]
There is a known memory leak issue when you configure SSL through PlayFramework. That's why we recommend using a reverse proxy to handle the SSL part.

The fix depends on Akka framework, and seems to not be fixed yet.

**Comment by joseluratm** [comment]
okey! Thanks for the response!!
