### ISSUE TITLE
Datastore initialization fails on Elasticsearch 6.x

### ISSUE THREAD

**Issue by davinerd** [TheHive-Project/TheHive#932]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu AWS
| OS version (client)       | Ubuntu AWS
| TheHive version / git hash   | 3.2.1
| Package Type              | DEB
| Browser type & version    | N/A

### Problem Description
TheHive cannot create the ES indexes at first launch.
This happens when using Elasticsearch 6.6.2 from DEB installation.

### Steps to Reproduce
1. Install TheHive
1. Install Elasticsearch
1. Open the browser and click "Update Database"

### Possible Solutions
It doesn't happen with Elasticsearch 5.x. so maybe stick with that version for first start and then upgrade to Elasticsearch 6.x later.

### Complementary information
```
2019-03-18 17:30:50,033 [INFO] from org.elastic4play.services.MigrationSrv in application-akka.actor.default-dispatcher-3 - Create a new empty database
2019-03-18 17:30:50,033 [INFO] from org.elastic4play.services.MigrationSrv in application-akka.actor.default-dispatcher-3 - Migrate database from version 0, add operations for version 2
2019-03-18 17:30:50,033 [INFO] from org.elastic4play.services.MigrationSrv in application-akka.actor.default-dispatcher-3 - Migrate database from version 0, add operations for version 3
2019-03-18 17:30:50,033 [INFO] from org.elastic4play.services.MigrationSrv in application-akka.actor.default-dispatcher-3 - Migrate database from version 0, add operations for version 4
2019-03-18 17:30:50,033 [INFO] from org.elastic4play.services.MigrationSrv in application-akka.actor.default-dispatcher-3 - Migrate database from version 0, add operations for version 5
2019-03-18 17:30:50,033 [INFO] from org.elastic4play.services.MigrationSrv in application-akka.actor.default-dispatcher-3 - Migrate database from version 0, add operations for version 6
2019-03-18 17:30:50,033 [INFO] from org.elastic4play.services.MigrationSrv in application-akka.actor.default-dispatcher-3 - Migrate database from version 0, add operations for version 7
2019-03-18 17:30:50,033 [INFO] from org.elastic4play.services.MigrationSrv in application-akka.actor.default-dispatcher-3 - Migrate database from version 0, add operations for version 8
2019-03-18 17:30:50,033 [INFO] from org.elastic4play.services.MigrationSrv in application-akka.actor.default-dispatcher-3 - Migrate database from version 0, add operations for version 9
2019-03-18 17:30:50,033 [INFO] from org.elastic4play.services.MigrationSrv in application-akka.actor.default-dispatcher-3 - Migrate database from version 0, add operations for version 10
2019-03-18 17:30:50,033 [INFO] from org.elastic4play.services.MigrationSrv in application-akka.actor.default-dispatcher-3 - Migrate database from version 0, add operations for version 11
2019-03-18 17:30:50,033 [INFO] from org.elastic4play.services.MigrationSrv in application-akka.actor.default-dispatcher-3 - Migrate database from version 0, add operations for version 12
2019-03-18 17:30:50,033 [INFO] from org.elastic4play.services.MigrationSrv in application-akka.actor.default-dispatcher-3 - Migrate database from version 0, add operations for version 13
2019-03-18 17:30:50,033 [INFO] from org.elastic4play.services.MigrationSrv in application-akka.actor.default-dispatcher-3 - Migrate database from version 0, add operations for version 14
2019-03-18 17:30:50,072 [ERROR] from org.elastic4play.services.MigrationSrv in application-akka.actor.default-dispatcher-3 - Migration fail
org.elasticsearch.transport.RemoteTransportException: [ip-10-0-3-207][10.0.3.207:9300][indices:admin/create]
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [case_artifact_job]: [_parent] field is disabled on indices with a single type. Use a [join] field instead.
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:398)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:329)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:452)
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643)
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:272)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:202)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:137)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:844)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: [_parent] field is disabled on indices with a single type. Use a [join] field instead.
        at org.elasticsearch.index.mapper.ParentFieldMapper$Builder.build(ParentFieldMapper.java:101)
        at org.elasticsearch.index.mapper.ParentFieldMapper$Builder.build(ParentFieldMapper.java:74)
        at org.elasticsearch.index.mapper.DocumentMapper$Builder.put(DocumentMapper.java:99)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:127)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:92)
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:395)
        ... 15 common frames omitted
2019-03-18 17:30:50,073 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-3 - POST /api/maintenance/migrate returned 500
org.elasticsearch.transport.RemoteTransportException: [ip-10-0-3-207][10.0.3.207:9300][indices:admin/create]
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [case_artifact_job]: [_parent] field is disabled on indices with a single type. Use a [join] field instead.
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:398)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:329)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:452)
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643)
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:272)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:202)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:137)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:844)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: [_parent] field is disabled on indices with a single type. Use a [join] field instead.
        at org.elasticsearch.index.mapper.ParentFieldMapper$Builder.build(ParentFieldMapper.java:101)
        at org.elasticsearch.index.mapper.ParentFieldMapper$Builder.build(ParentFieldMapper.java:74)
        at org.elasticsearch.index.mapper.DocumentMapper$Builder.put(DocumentMapper.java:99)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:127)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:92)
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:395)
        ... 15 common frames omitted
```

**Comment by crackytsi** [comment]
@davinerd Note that only ES 5 is supported. For the future it is planned to migrate to a different database System. 
So missing ES 6 compatibility is expected ;)

**Comment by davinerd** [comment]
Ah sorry, I may have missed that in the documentation. You can close it.

Thank you.
