### ISSUE TITLE
Hive to Cortex API Authentication Failure

### ISSUE THREAD

**Issue by romans8** [TheHive-Project/TheHive#940]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 3.3
| Package Type              | Docker
| Browser type & version    |  Latest Chrome

### Problem Description
Describe the problem/bug as clearly as possible.

### Steps to Reproduce
1. New Build
2. Make Org in Cortex
3. Add user to Org in Cortex
4. Create API Key
5. Add API Key to Config Map
6. Rebuild the Hive

Config Map
play.modules.enabled += connectors.cortex.CortexConnector

cortex {
  "CORTEX-SERVER-ID" {
  url = "http://[URL HERE]"
  key = "[KEY HERE]"
  #  # HTTP client configuration (SSL and proxy)
  #  ws {}
  }
}

Hive Error Log
[error] c.c.s.CortexActionSrv - Request to Cortex fails
connectors.cortex.services.CortexError: Cortex error on http://[IP HERE]:9001/api/responder/_search?range=all (401)
{"type":"AuthenticationError","message":"Authentication failure"}
at connectors.cortex.services.CortexClient.$anonfun$request$3(CortexClient.scala:95)
at scala.util.Success.$anonfun$map$1(Try.scala:251)
at scala.util.Success.map(Try.scala:209)
at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)

Cortex Error Log
[error] o.e.c.Authenticated - Authentication failure:
session: AuthenticationError User session not found
pki: AuthenticationError Certificate authentication is not configured
key: AuthenticationError Authentication header not found
init: AuthenticationError Use of initial user is forbidden because users exist in database
[info] o.t.c.s.ErrorHandler - GET /api/user/current returned 401
org.elastic4play.AuthenticationError: Authentication failure
at org.elastic4play.controllers.Authenticated.$anonfun$getContext$4(Authenticated.scala:254)
at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)

**Comment by romans8** [comment]
updated to Cortex 2.1 and it was fixed.

**Comment by Daisho624** [comment]
I have latest cortex 3.1.8-1 and elasticsearch 7.11.1. my cortex and elasticsearch is working well. but i cant add or create organisation and users. log is same as yours.
my part of cortex from docker is 
cortex:
    image: 'thehiveproject/cortex:latest'
    container_name: cortex
    restart: unless-stopped
    environment:
      - job_directory=/opt/cortex/jobs
    volumes:
      - './vol/cortex/application.conf:/etc/cortex/application.conf'
      - './vol/cortex/log/:/var/log/cortex'
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - elasticsearch
    ports:
      - '0.0.0.0:9001:9001'


its my application.conf 
play.http.secret.key="**************"
search {
  index = cortex
  uri = "http://elasticsearch:9200"
}

auth {
  providers = [
    {
      type = "basic"
      realm = "Cortex"
      file = "/etc/cortex/passwords"
    },
  ]
}

## Cache
cache.job = 10 minutes

job {
  runner = [docker, process]
}

analyzer {
  urls = [
    "https://download.thehive-project.org/analyzers.json"
    #"/absolute/path/of/analyzers"
  ]
}

responder {
  urls = [
    "https://download.thehive-project.org/responders.json"
    #"/absolute/path/of/responders"
  ]
}
logger {
  application = "DEBUG"




this is the error:  Hope someone can help me or suggest the way to fix this error.
ps: sorry for my broken english

2023-12-19 01:15:58 [error] o.e.c.Authenticated - Authentication failure:
2023-12-19 01:15:58     session: AuthenticationError User session not found
2023-12-19 01:15:58     pki: AuthenticationError Certificate authentication is not configured
2023-12-19 01:15:58     key: AuthenticationError Authentication failure
2023-12-19 01:15:58     init: AuthenticationError Use of initial user is forbidden because users exist in database
2023-12-19 01:15:58 [info] o.t.c.s.AccessLogFilter - 172.18.0.5 GET /api/user/current took 41ms and returned 401 65 bytes
2023-12-19 01:16:06 [warn] o.t.c.s.ErrorHandler - GET /api/alert returned 403
2023-12-19 01:16:06 [info] o.t.c.s.AccessLogFilter - 172.18.0.1 GET /api/alert took 137ms and returned 403 84 bytes
2023-12-19 01:16:23 [info] o.t.c.s.AccessLogFilter - 172.18.0.5 GET /api/status took 4ms and returned 200 278 bytes
2023-12-19 01:16:28 [info] o.t.c.s.AccessLogFilter - 172.18.0.5 GET /api/status took 1ms and returned 200 278 bytes
2023-12-19 01:16:28 [error] o.e.s.a.MultiAuthSrv - Authentication failure
2023-12-19 01:16:28 org.elastic4play.AuthenticationError: Authentication using API key is not supported
2023-12-19 01:16:28     at org.elastic4play.services.AuthSrv.authenticate(UserSrv.scala:48)
2023-12-19 01:16:28     at org.elastic4play.services.AuthSrv.authenticate$(UserSrv.scala:47)
2023-12-19 01:16:28     at org.thp.cortex.services.LocalAuthSrv.authenticate(LocalAuthSrv.scala:15)
2023-12-19 01:16:28     at org.elastic4play.services.auth.MultiAuthSrv.$anonfun$authenticate$3(MultiAuthSrv.scala:58)
2023-12-19 01:16:28     at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$$nestedInanonfun$forAllAuthProvider$1$1.applyOrElse(MultiAuthSrv.scala:43)
2023-12-19 01:16:28     at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$$nestedInanonfun$forAllAuthProvider$1$1.applyOrElse(MultiAuthSrv.scala:41)
2023-12-19 01:16:28     at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
2023-12-19 01:16:28     at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
2023-12-19 01:16:28     at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
2023-12-19 01:16:28     at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
