### ISSUE TITLE
Cortex "Error: user init not found" on first run

### ISSUE THREAD

**Issue by yaleman** [TheHive-Project/TheHive#961]
### Request Type

Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 
| OS version (client)       | 18.04.2 LTS
| TheHive version / git hash   | 2.1.3-1
| Package Type              | DEB
| Browser type & version    | Tested on Firefox and Chrome

### Problem Description

FIrst install, clicked the "update database" prompt and it just sat there. I tried refreshing the page after a few minutes and it took me to a grey screen with a small red box with "Error: user init not found"

### Steps to Reproduce
1. Install Cortex on same box as Hive, use the same play key
1. Open in browser
1. Error appears

### Complementary information

Log that appears when you access the page:

```
^[`2019-04-26 06:17:26,707 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-19 - GET /api/user/current returned 404
org.elastic4play.NotFoundError: user init not found
        at org.elastic4play.database.DBGet.$anonfun$apply$2(DBGet.scala:38)
        at scala.Option.fold(Option.scala:158)
        at org.elastic4play.database.DBGet.$anonfun$apply$1(DBGet.scala:38)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by yaleman** [comment]
Wrong project, sorry
