### ISSUE TITLE
Unable To Start Service After Install

### ISSUE THREAD

**Issue by debunk78** [TheHive-Project/TheHive#985]
# Unable To Start Service After Install

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04.2 LTS
| OS version (client)       | Windows 10, 1803
| TheHive version / git hash   | 3.3.1-1
| Package Type              | Binary
| Browser type & version    | Google Chrome

### Problem Description
I followed the instructions provided here (mainly section 5):  https://github.com/TheHive-Project/TheHiveDocs/blob/master/installation/install-guide.md#binary

But when I run this command from /opt/thehive:
bin/thehive -Dconfig.file=/etc/thehive/application.conf

I get:

```
Oops, cannot start the server.
java.nio.file.AccessDeniedException: /opt/thehive-3.3.1-1/RUNNING_PID
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:219)
        at play.core.server.ProdServerStart$.createPidFile(ProdServerStart.scala:136)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:43)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

I opted to start thehive as a service account

### Steps to Reproduce
1. Disabled thehive service
2. Removed all files / directories
3. Ran through instructions again
4. Same error on last command

### Complementary information

```
/opt$ sudo ln -s thehive-3.3.1-1 thehive
/opt$
/opt$
/opt$ sudo addgroup thehive
/opt$ sudo adduser --system thehive
/opt$ sudo cp /opt/thehive/package/thehive.service /usr/lib/systemd/system
/opt$ sudo chown -R thehive:thehive /opt/thehive
/opt$ sudo chgrp thehive /etc/thehive/application.conf
chgrp: cannot access '/etc/thehive/application.conf': No such file or directory
/opt$ sudo chmod 640 /etc/thehive/application.conf
chmod: cannot access '/etc/thehive/application.conf': No such file or directory
/opt$
/opt$ sudo mkdir /etc/thehive
(cat << _EOF_
# Secret key
# ~~~~~
# The secret key is used to secure cryptographics functions.
/opt$ (cat << _EOF_
> # Secret key
> # ~~~~~
> # The secret key is used to secure cryptographics functions.
> # If you deploy your application to several instances be sure to use the same key!
> play.http.secret.key="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)"
> _EOF_
> ) | sudo tee -a /etc/thehive/application.conf
# Secret key
# ~~~~~
# The secret key is used to secure cryptographics functions.
# If you deploy your application to several instances be sure to use the same key!
play.http.secret.key="dmeVF1ySZQYF17eOf3lWjhDArilF5mEXqtNUZTT44fu7Xs3isrcsz4IZdGkJHDLp"
/opt$
/opt$
/opt$
/opt$
/opt$ sudo chown -R thehive:thehive /opt/thehive
/opt$ sudo chgrp thehive /etc/thehive/application.conf
/opt$ sudo chmod 640 /etc/thehive/application.conf
/opt$ sudo systemctl enable thehive
Created symlink /etc/systemd/system/multi-user.target.wants/thehive.service → /usr/lib/systemd/system/thehive.service.
/opt$ sudo service thehive start
/opt$ cd thehive
/opt/thehive$ bin/thehive -Dconfig.file=/etc/thehive/application.conf
Oops, cannot start the server.
java.nio.file.AccessDeniedException: /opt/thehive-3.3.1-1/RUNNING_PID
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:219)
        at play.core.server.ProdServerStart$.createPidFile(ProdServerStart.scala:136)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:43)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

**Comment by crackytsi** [comment]
Looks linke something ist still running... maybe akka?
Or Ares you trying to bind an privileged Port?

**Comment by nadouani** [comment]
What's the `/opt/thehive-3.3.1-1` folder?

**Comment by nadouani** [comment]
Oh my bad, I didn't see the `ln -s` command up there :)

**Comment by nadouani** [comment]
You are running TheHive as a service and then you are starting it from the binaries.

Something is wrong here. What do you want to achieve ?

**Comment by debunk78** [comment]
Hi nadouani, I have very limited linux skills, but really liked this product (saw it during a demo) and it came highly recommended. I was unaware of how to properly set permissions on the folders that the account needed access to, so I decided to use the configurations supplied to make a service account. Honestly, I am just trying to get the service start - so if I can revert these changes and start thehive as my actual linux account - Id be okay with that. I know it's not the most secure way, but I'll need to get this running for demonstration purposes. Any help would be greatly appreciated.

**Comment by nadouani** [comment]
If you need to make a demo, you can use the training VM. IT's hard to troubleshoot your custom install process.
